HSK2_CHARACTERS = {
    '吧': {'pinyin': 'ba', 'meaning': 'частица, выражающая предложение или просьбу'},
    '白': {'pinyin': 'bái', 'meaning': 'белый'},
    '班': {'pinyin': 'bān', 'meaning': 'класс; группа'},
    '百': {'pinyin': 'bǎi', 'meaning': 'сто'},
    '帮助': {'pinyin': 'bāngzhù', 'meaning': 'помогать; помощь'},
    '包': {'pinyin': 'bāo', 'meaning': 'сумка; пакет'},
    '报纸': {'pinyin': 'bàozhǐ', 'meaning': 'газета'},
    '北京': {'pinyin': 'Běijīng', 'meaning': 'Пекин'},
    '本': {'pinyin': 'běn', 'meaning': 'книга; мера для книг'},
    '比': {'pinyin': 'bǐ', 'meaning': 'сравнивать; чем'},
    '不客气': {'pinyin': 'bù kèqì', 'meaning': 'не за что; пожалуйста'},
    '菜': {'pinyin': 'cài', 'meaning': 'овощ; блюдо'},
    '茶': {'pinyin': 'chá', 'meaning': 'чай'},
    '差': {'pinyin': 'chà', 'meaning': 'плохой; хуже'},
    '超市': {'pinyin': 'chāoshì', 'meaning': 'супермаркет'},
    '城市': {'pinyin': 'chéngshì', 'meaning': 'город'},
    '出租车': {'pinyin': 'chūzūchē', 'meaning': 'такси'},
    '打': {'pinyin': 'dǎ', 'meaning': 'бить; ударять'},
    '打电话': {'pinyin': 'dǎ diànhuà', 'meaning': 'звонить по телефону'},
    '大': {'pinyin': 'dà', 'meaning': 'большой'},
    '大家': {'pinyin': 'dàjiā', 'meaning': 'все; каждый'},
    '蛋糕': {'pinyin': 'dàngāo', 'meaning': 'торт'},
    '当然': {'pinyin': 'dāngrán', 'meaning': 'конечно'},
    '得': {'pinyin': 'děi', 'meaning': 'должен; нужно'},
    '点': {'pinyin': 'diǎn', 'meaning': 'час; точка'},
    '电脑': {'pinyin': 'diànnǎo', 'meaning': 'компьютер'},
    '电视': {'pinyin': 'diànshì', 'meaning': 'телевизор'},
    '电影': {'pinyin': 'diànyǐng', 'meaning': 'фильм'},
    '东西': {'pinyin': 'dōngxī', 'meaning': 'вещь; предмет'},
    '冬': {'pinyin': 'dōng', 'meaning': 'зима'},
    '动物': {'pinyin': 'dòngwù', 'meaning': 'животное'},
    '懂': {'pinyin': 'dǒng', 'meaning': 'понимать'},
    '短': {'pinyin': 'duǎn', 'meaning': 'короткий'},
    '段': {'pinyin': 'duàn', 'meaning': 'отрезок; часть'},
    '锻炼': {'pinyin': 'duànliàn', 'meaning': 'тренироваться; упражняться'},
    '多': {'pinyin': 'duō', 'meaning': 'много'},
    '多少': {'pinyin': 'duōshǎo', 'meaning': 'сколько'},
    '饿': {'pinyin': 'è', 'meaning': 'голодный'},
    '耳朵': {'pinyin': 'ěrduǒ', 'meaning': 'ухо'},
    '放': {'pinyin': 'fàng', 'meaning': 'класть; выпускать'},
    '放心': {'pinyin': 'fàngxīn', 'meaning': 'быть спокойным'},
    '非常': {'pinyin': 'fēicháng', 'meaning': 'очень; чрезвычайно'},
    '飞机': {'pinyin': 'fēijī', 'meaning': 'самолет'},
    '分钟': {'pinyin': 'fēnzhōng', 'meaning': 'минута'},
    '服务员': {'pinyin': 'fúwùyuán', 'meaning': 'официант; обслуживающий персонал'},
    '附近': {'pinyin': 'fùjìn', 'meaning': 'поблизости'},
    '复习': {'pinyin': 'fùxí', 'meaning': 'повторять;复习ать'},
    '干': {'pinyin': 'gān', 'meaning': 'сухой'},
    '干净': {'pinyin': 'gānjìng', 'meaning': 'чистый'},
    '刚': {'pinyin': 'gāng', 'meaning': 'только что'},
    '高': {'pinyin': 'gāo', 'meaning': 'высокий'},
    '告诉': {'pinyin': 'gàosù', 'meaning': 'сказать; сообщить'},
    '感觉': {'pinyin': 'gǎnjué', 'meaning': 'чувствовать; ощущение'},
    '感兴趣': {'pinyin': 'gǎn xìngqù', 'meaning': 'быть заинтересованным'},
    '各': {'pinyin': 'gè', 'meaning': 'каждый; различный'},
    '给': {'pinyin': 'gěi', 'meaning': 'давать'},
    '跟': {'pinyin': 'gēn', 'meaning': 'с; за'},
    '哥哥': {'pinyin': 'gēgē', 'meaning': 'старший брат'},
    '更': {'pinyin': 'gèng', 'meaning': 'более'},
    '公共汽车': {'pinyin': 'gōnggòng qìchē', 'meaning': 'автобус'},
    '公司': {'pinyin': 'gōngsī', 'meaning': 'компания'},
    '贵': {'pinyin': 'guì', 'meaning': 'дорогой'},
    '过': {'pinyin': 'guò', 'meaning': 'проходить; миновать'},
    '还': {'pinyin': 'hái', 'meaning': 'еще'},
    '孩子': {'pinyin': 'háizi', 'meaning': 'ребенок'},
    '好吃': {'pinyin': 'hǎochī', 'meaning': 'вкусный'},
    '号': {'pinyin': 'hào', 'meaning': 'номер; число'},
    '黑': {'pinyin': 'hēi', 'meaning': 'черный'},
    '红': {'pinyin': 'hóng', 'meaning': 'красный'},
    '花': {'pinyin': 'huā', 'meaning': 'цветок'},
    '画': {'pinyin': 'huà', 'meaning': 'рисовать; картина'},
    '坏': {'pinyin': 'huài', 'meaning': 'плохой'},
    '欢迎': {'pinyin': 'huānyíng', 'meaning': 'приветствовать'},
    '环境': {'pinyin': 'huánjìng', 'meaning': 'окружающая среда'},
    '回答': {'pinyin': 'huídá', 'meaning': 'отвечать'},
    '会议': {'pinyin': 'huìyì', 'meaning': 'собрание; встреча'},
    '或者': {'pinyin': 'huòzhě', 'meaning': 'или'},
    '机场': {'pinyin': 'jīchǎng', 'meaning': 'аэропорт'},
    '鸡蛋': {'pinyin': 'jīdàn', 'meaning': 'яйцо'},
    '几乎': {'pinyin': 'jīhū', 'meaning': 'почти'},
    '机会': {'pinyin': 'jīhuì', 'meaning': 'возможность'},
    '极': {'pinyin': 'jí', 'meaning': 'чрезвычайно'},
    '记得': {'pinyin': 'jìde', 'meaning': 'помнить'},
    '季节': {'pinyin': 'jìjié', 'meaning': 'сезон'},
    '检查': {'pinyin': 'jiǎnchá', 'meaning': 'проверять'},
    '简单': {'pinyin': 'jiǎndān', 'meaning': 'простой'},
    '见面': {'pinyin': 'jiànmiàn', 'meaning': 'встречаться'},
    '健康': {'pinyin': 'jiànkāng', 'meaning': 'здоровый'},
    '介绍': {'pinyin': 'jièshào', 'meaning': 'представлять; знакомить'},
    '结束': {'pinyin': 'jiéshù', 'meaning': 'заканчивать'},
    '决定': {'pinyin': 'juédìng', 'meaning': 'решать'},
    '觉得': {'pinyin': 'juéde', 'meaning': 'считать; думать'},
    '句子': {'pinyin': 'jùzi', 'meaning': 'предложение'},
    '咖啡': {'pinyin': 'kāfēi', 'meaning': 'кофе'},
    '开始': {'pinyin': 'kāishǐ', 'meaning': 'начинать'},
    '考试': {'pinyin': 'kǎoshì', 'meaning': 'экзамен'},
    '可爱': {'pinyin': 'kě\'ài', 'meaning': 'милый'},
    '可能': {'pinyin': 'kěnéng', 'meaning': 'возможно'},
    '课': {'pinyin': 'kè', 'meaning': 'урок'},
    '快乐': {'pinyin': 'kuàilè', 'meaning': 'счастливый'},
    '累': {'pinyin': 'lèi', 'meaning': 'усталый'},
    '离': {'pinyin': 'lí', 'meaning': 'от; далеко'},
    '离开': {'pinyin': 'líkāi', 'meaning': 'покидать'},
    '里': {'pinyin': 'lǐ', 'meaning': 'внутри'},
    '礼拜': {'pinyin': 'lǐbài', 'meaning': 'неделя'},
    '礼物': {'pinyin': 'lǐwù', 'meaning': 'подарок'},
    '脸': {'pinyin': 'liǎn', 'meaning': 'лицо'},
    '练习': {'pinyin': 'liànxí', 'meaning': 'упражняться'},
    '邻居': {'pinyin': 'línjū', 'meaning': 'сосед'},
    '路': {'pinyin': 'lù', 'meaning': 'дорога'},
    '旅游': {'pinyin': 'lǚyóu', 'meaning': 'путешествовать'},
    '慢': {'pinyin': 'màn', 'meaning': 'медленный'},
    '忙': {'pinyin': 'máng', 'meaning': 'занятый'},
    '猫': {'pinyin': 'māo', 'meaning': 'кошка'},
    '没关系': {'pinyin': 'méi guānxì', 'meaning': 'ничего страшного'},
    '门': {'pinyin': 'mén', 'meaning': 'дверь'},
    '米': {'pinyin': 'mǐ', 'meaning': 'рис'},
    '面': {'pinyin': 'miàn', 'meaning': 'лапша'},
    '面包': {'pinyin': 'miànbāo', 'meaning': 'хлеб'},
    '男': {'pinyin': 'nán', 'meaning': 'мужской'},
    '难': {'pinyin': 'nán', 'meaning': 'трудный'},
    '鸟': {'pinyin': 'niǎo', 'meaning': 'птица'},
    '牛奶': {'pinyin': 'niúnǎi', 'meaning': 'молоко'},
    '胖': {'pinyin': 'pàng', 'meaning': 'толстый'},
    '跑': {'pinyin': 'pǎo', 'meaning': 'бежать'},
    '便宜': {'pinyin': 'piányí', 'meaning': 'дешевый'},
    '票': {'pinyin': 'piào', 'meaning': 'билет'},
    '漂亮': {'pinyin': 'piàoliàng', 'meaning': 'красивый'},
    '苹果': {'pinyin': 'píngguǒ', 'meaning': 'яблоко'},
    '葡萄': {'pinyin': 'pútáo', 'meaning': 'виноград'},
    '普通话': {'pinyin': 'pǔtōnghuà', 'meaning': 'мандаринский китайский'},
    '其实': {'pinyin': 'qíshí', 'meaning': 'на самом деле'},
    '其他': {'pinyin': 'qítā', 'meaning': 'другие'},
    '骑': {'pinyin': 'qí', 'meaning': 'ездить верхом'},
    '起床': {'pinyin': 'qǐchuáng', 'meaning': 'вставать с постели'},
    '气': {'pinyin': 'qì', 'meaning': 'воздух; энергия'},
    '汽车': {'pinyin': 'qìchē', 'meaning': 'автомобиль'},
    '千': {'pinyin': 'qiān', 'meaning': 'тысяча'},
    '钱': {'pinyin': 'qián', 'meaning': 'деньги'},
    '前': {'pinyin': 'qián', 'meaning': 'перед'},
    '清楚': {'pinyin': 'qīngchǔ', 'meaning': 'ясный'},
    '请': {'pinyin': 'qǐng', 'meaning': 'пожалуйста'},
    '容易': {'pinyin': 'róngyì', 'meaning': 'легкий'},
    '如果': {'pinyin': 'rúguǒ', 'meaning': 'если'},
    '伞': {'pinyin': 'sǎn', 'meaning': 'зонт'},
    '上': {'pinyin': 'shàng', 'meaning': 'наверху; подниматься'},
    '声音': {'pinyin': 'shēngyīn', 'meaning': 'звук; голос'},
    '生气': {'pinyin': 'shēngqì', 'meaning': 'злиться'},
    '身体': {'pinyin': 'shēntǐ', 'meaning': 'тело'},
    '生日': {'pinyin': 'shēngrì', 'meaning': 'день рождения'},
    '时间': {'pinyin': 'shíjiān', 'meaning': 'время'},
    '试': {'pinyin': 'shì', 'meaning': 'пробовать'},
    '市场': {'pinyin': 'shìchǎng', 'meaning': 'рынок'},
    '事情': {'pinyin': 'shìqíng', 'meaning': 'дело; событие'},
    '手表': {'pinyin': 'shǒubiǎo', 'meaning': 'наручные часы'},
    '手机': {'pinyin': 'shǒujī', 'meaning': 'мобильный телефон'},
    '书店': {'pinyin': 'shūdiàn', 'meaning': 'книжный магазин'},
    '树': {'pinyin': 'shù', 'meaning': 'дерево'},
    '舒服': {'pinyin': 'shūfu', 'meaning': 'удобный'},
    '水': {'pinyin': 'shuǐ', 'meaning': 'вода'},
    '睡': {'pinyin': 'shuì', 'meaning': 'спать'},
    '所以': {'pinyin': 'suǒyǐ', 'meaning': 'поэтому'},
    '虽然': {'pinyin': 'suīrán', 'meaning': 'хотя'},
    '岁': {'pinyin': 'suì', 'meaning': 'год (возраст)'},
    '他': {'pinyin': 'tā', 'meaning': 'он'},
    '她': {'pinyin': 'tā', 'meaning': 'она'},
    '它': {'pinyin': 'tā', 'meaning': 'оно'},
    '太': {'pinyin': 'tài', 'meaning': 'слишком'},
    '特别': {'pinyin': 'tèbié', 'meaning': 'особенный'},
    '题': {'pinyin': 'tí', 'meaning': 'вопрос; тема'},
    '提': {'pinyin': 'tí', 'meaning': 'поднимать'},
    '跳舞': {'pinyin': 'tiàowǔ', 'meaning': 'танцевать'},
    '甜': {'pinyin': 'tián', 'meaning': 'сладкий'},
    '条': {'pinyin': 'tiáo', 'meaning': 'мера для длинных тонких предметов'},
    '听': {'pinyin': 'tīng', 'meaning': 'слушать'},
    '同': {'pinyin': 'tóng', 'meaning': 'одинаковый'},
    '同事': {'pinyin': 'tóngshì', 'meaning': 'коллега'},
    '同意': {'pinyin': 'tóngyì', 'meaning': 'соглашаться'},
    '头': {'pinyin': 'tóu', 'meaning': 'голова'},
    '突然': {'pinyin': 'tūrán', 'meaning': 'вдруг'},
    '图书馆': {'pinyin': 'túshūguǎn', 'meaning': 'библиотека'},
    '腿': {'pinyin': 'tuǐ', 'meaning': 'нога'},
    '外': {'pinyin': 'wài', 'meaning': 'внешний'},
    '完': {'pinyin': 'wán', 'meaning': 'заканчивать'},
    '玩': {'pinyin': 'wán', 'meaning': 'играть'},
    '晚上': {'pinyin': 'wǎnshàng', 'meaning': 'вечер'},
    '忘': {'pinyin': 'wàng', 'meaning': 'забывать'},
    '为什么': {'pinyin': 'wèishénme', 'meaning': 'почему'},
    '问': {'pinyin': 'wèn', 'meaning': 'спрашивать'},
    '问题': {'pinyin': 'wèntí', 'meaning': 'вопрос; проблема'},
    '西': {'pinyin': 'xī', 'meaning': 'запад'},
    '洗': {'pinyin': 'xǐ', 'meaning': 'мыть'},
    '喜欢': {'pinyin': 'xǐhuān', 'meaning': 'любить; нравиться'},
    '笑': {'pinyin': 'xiào', 'meaning': 'смеяться'},
    '小': {'pinyin': 'xiǎo', 'meaning': 'маленький'},
    '小姐': {'pinyin': 'xiǎojiě', 'meaning': 'мисс'},
    '小时': {'pinyin': 'xiǎoshí', 'meaning': 'час'},
    '鞋': {'pinyin': 'xié', 'meaning': 'обувь'},
    '写': {'pinyin': 'xiě', 'meaning': 'писать'},
    '信': {'pinyin': 'xìn', 'meaning': 'письмо'},
    '新': {'pinyin': 'xīn', 'meaning': 'новый'},
    '星期': {'pinyin': 'xīngqī', 'meaning': 'неделя'},
    '行': {'pinyin': 'xíng', 'meaning': 'идти; годиться'},
    '行李': {'pinyin': 'xínglǐ', 'meaning': 'багаж'},
    '姓': {'pinyin': 'xìng', 'meaning': 'фамилия'},
    '兴趣': {'pinyin': 'xìngqù', 'meaning': 'интерес'},
    '熊猫': {'pinyin': 'xióngmāo', 'meaning': 'панда'},
    '休息': {'pinyin': 'xiūxí', 'meaning': 'отдыхать'},
    '需要': {'pinyin': 'xūyào', 'meaning': 'нуждаться'},
    '选择': {'pinyin': 'xuǎnzé', 'meaning': 'выбирать'},
    '眼镜': {'pinyin': 'yǎnjìng', 'meaning': 'очки'},
    '颜色': {'pinyin': 'yánsè', 'meaning': 'цвет'},
    '药': {'pinyin': 'yào', 'meaning': 'лекарство'},
    '要': {'pinyin': 'yào', 'meaning': 'хотеть; нужно'},
    '也': {'pinyin': 'yě', 'meaning': 'тоже'},
    '已经': {'pinyin': 'yǐjīng', 'meaning': 'уже'},
    '一起': {'pinyin': 'yīqǐ', 'meaning': 'вместе'},
    '意思': {'pinyin': 'yìsi', 'meaning': 'значение; смысл'},
    '饮料': {'pinyin': 'yǐnliào', 'meaning': 'напиток'},
    '因为': {'pinyin': 'yīnwèi', 'meaning': 'потому что'},
    '音乐': {'pinyin': 'yīnyuè', 'meaning': 'музыка'},
    '银行': {'pinyin': 'yínháng', 'meaning': 'банк'},
    '应该': {'pinyin': 'yīnggāi', 'meaning': 'должен'},
    '影响': {'pinyin': 'yǐngxiǎng', 'meaning': 'влиять'},
    '用': {'pinyin': 'yòng', 'meaning': 'использовать'},
    '游戏': {'pinyin': 'yóuxì', 'meaning': 'игра'},
    '有': {'pinyin': 'yǒu', 'meaning': 'иметь'},
    '有名': {'pinyin': 'yǒumíng', 'meaning': 'известный'},
    '又': {'pinyin': 'yòu', 'meaning': 'снова'},
    '右': {'pinyin': 'yòu', 'meaning': 'правый'},
    '鱼': {'pinyin': 'yú', 'meaning': 'рыба'},
    '遇见': {'pinyin': 'yùjiàn', 'meaning': 'встречать'},
    '远': {'pinyin': 'yuǎn', 'meaning': 'далекий'},
    '运动': {'pinyin': 'yùndòng', 'meaning': 'спорт'},
    '再': {'pinyin': 'zài', 'meaning': 'снова; еще раз'},
    '早上': {'pinyin': 'zǎoshàng', 'meaning': 'утро'},
    '丈夫': {'pinyin': 'zhàngfū', 'meaning': 'муж'},
    '找': {'pinyin': 'zhǎo', 'meaning': 'искать'},
    '着': {'pinyin': 'zhe', 'meaning': 'частица для продолжающегося действия'},
    '真': {'pinyin': 'zhēn', 'meaning': 'настоящий'},
    '正在': {'pinyin': 'zhèngzài', 'meaning': 'в процессе'},
    '知道': {'pinyin': 'zhīdào', 'meaning': 'знать'},
    '准备': {'pinyin': 'zhǔnbèi', 'meaning': 'готовиться'},
    '走': {'pinyin': 'zǒu', 'meaning': 'идти'},
    '最': {'pinyin': 'zuì', 'meaning': 'самый'},
    '最后': {'pinyin': 'zuìhòu', 'meaning': 'последний'},
    '最近': {'pinyin': 'zuìjìn', 'meaning': 'недавно'},
    '足球': {'pinyin': 'zúqiú', 'meaning': 'футбол'},
    '坐': {'pinyin': 'zuò', 'meaning': 'сидеть'},
    '做': {'pinyin': 'zuò', 'meaning': 'делать'},
}