HSK2_CHARACTERS = {
    '啊': {'pinyin': 'ā; á; ǎ; à; a', 'meaning': 'выражает удивление, восхищение, вопрос'},
    '爱情': {'pinyin': 'àiqíng', 'meaning': 'любовь'},
    '爱人': {'pinyin': 'àiren', 'meaning': 'муж, жена; любимый человек'},
    '安静': {'pinyin': 'ānjìng', 'meaning': 'покойный, тихий; тишина'},
    '安全': {'pinyin': 'ānquán', 'meaning': 'безопасность; безопасный'},
    '白色': {'pinyin': 'báisè', 'meaning': 'белый цвет'},
    '班长': {'pinyin': 'bānzhǎng', 'meaning': 'староста; бригадир; командир'},
    '办': {'pinyin': 'bàn', 'meaning': 'делать, заниматься; основывать'},
    '办法': {'pinyin': 'bànfǎ', 'meaning': 'способ, метод, решение'},
    '办公室': {'pinyin': 'bàngōngshì', 'meaning': 'офис, бюро, кабинет'},
    '半夜': {'pinyin': 'bànyè', 'meaning': 'полночь, середина ночи'},
    '帮助': {'pinyin': 'bāngzhù', 'meaning': 'помогать, помощь'},
    '饱': {'pinyin': 'bǎo', 'meaning': 'сытый'},
    '报名': {'pinyin': 'bàomíng', 'meaning': 'зарегистрироваться; записаться'},
    '报纸': {'pinyin': 'bàozhǐ', 'meaning': 'газета'},
    '北方': {'pinyin': 'běifāng', 'meaning': 'север; северная сторона'},
    '背': {'pinyin': 'bēi', 'meaning': 'нести на спине; взваливать на плечи'},
    '比如': {'pinyin': 'bǐrú', 'meaning': 'например'},
    '比如说': {'pinyin': 'bǐrúshuō', 'meaning': 'например, к примеру'},
    '笔': {'pinyin': 'bǐ', 'meaning': 'ручка, карандаш'},
    '笔记': {'pinyin': 'bǐjì', 'meaning': 'запись; делать запись'},
    '笔记本': {'pinyin': 'bǐjìběn', 'meaning': 'блокнот; ноутбук'},
    '必须': {'pinyin': 'bìxū', 'meaning': 'должен, необходимо, обязательно'},
    '边': {'pinyin': 'biān', 'meaning': 'сторона, край, граница'},
    '变': {'pinyin': 'biàn', 'meaning': 'изменяться, становиться'},
    '变成': {'pinyin': 'biànchéng', 'meaning': 'превратиться в; становиться кем-то'},
    '遍': {'pinyin': 'biàn', 'meaning': 'повсюду, везде'},
    '表': {'pinyin': 'biǎo', 'meaning': 'часы; выражать, показывать'},
    '表示': {'pinyin': 'biǎoshì', 'meaning': 'выражать, показывать'},
    '不错': {'pinyin': 'búcuò', 'meaning': 'хороший, неплохой'},
    '不但': {'pinyin': 'búdàn', 'meaning': 'не только'},
    '不够': {'pinyin': 'búgòu', 'meaning': 'не хватать; недостаточно'},
    '不过': {'pinyin': 'búguò', 'meaning': 'но; однако'},
    '不太': {'pinyin': 'bú tài', 'meaning': 'не очень, не слишком'},
    '不要': {'pinyin': 'búyào', 'meaning': 'не нужно, нельзя'},
    '不好意思': {'pinyin': 'bùhǎoyìsi', 'meaning': 'прошу прощения; неловко'},
    '不久': {'pinyin': 'bùjiǔ', 'meaning': 'скоро, недолго, недавно'},
    '不满': {'pinyin': 'bùmǎn', 'meaning': 'недовольный; быть недовольным'},
    '不如': {'pinyin': 'bùrú', 'meaning': 'уступать чему-либо; лучше уж'},
    '不少': {'pinyin': 'bù shǎo', 'meaning': 'много, немало'},
    '不同': {'pinyin': 'bù tóng', 'meaning': 'разный, различный'},
    '不行': {'pinyin': 'bùxíng', 'meaning': 'не годится, нельзя'},
    '不一定': {'pinyin': 'bùyídìng', 'meaning': 'не всегда, необязательно'},
    '不一会儿': {'pinyin': 'bù yīhuìér', 'meaning': 'в один момент'},
    '部分': {'pinyin': 'bùfen', 'meaning': 'часть, доля'},
    '才': {'pinyin': 'cái', 'meaning': 'только что, только-только'},
    '菜单': {'pinyin': 'càidān', 'meaning': 'меню'},
    '参观': {'pinyin': 'cānguān', 'meaning': 'посещать, осматривать'},
    '参加': {'pinyin': 'cānjiā', 'meaning': 'принимать участие'},
    '草': {'pinyin': 'cǎo', 'meaning': 'трава'},
    '草地': {'pinyin': 'cǎodì', 'meaning': 'газон; луг'},
    '层': {'pinyin': 'céng', 'meaning': 'этаж, слой'},
    '查': {'pinyin': 'chá', 'meaning': 'проверять, исследовать'},
    '差不多': {'pinyin': 'chàbuduō', 'meaning': 'почти'},
    '长': {'pinyin': 'zhǎng', 'meaning': 'старший; расти; увеличиваться'},
    '常见': {'pinyin': 'cháng jiàn', 'meaning': 'обычный; часто встречающийся'},
    '常用': {'pinyin': 'cháng yòng', 'meaning': 'общеупотребительный'},
    '场': {'pinyin': 'chǎng', 'meaning': 'площадь; площадка; сцена; счётное слово для зрелищ'},
    '超过': {'pinyin': 'chāoguò', 'meaning': 'опередить; превзойти'},
    '超市': {'pinyin': 'chāoshì', 'meaning': 'супермаркет'},
    '车辆': {'pinyin': 'chēliàng', 'meaning': 'транспортное средство'},
    '称': {'pinyin': 'chēng', 'meaning': 'взвешивать; отвешивать'},
    '成': {'pinyin': 'chéng', 'meaning': 'становиться, превращаться в'},
    '成绩': {'pinyin': 'chéngjì', 'meaning': 'оценки; достижения, успехи'},
    '成为': {'pinyin': 'chéngwéi', 'meaning': 'становиться'},
    '重复': {'pinyin': 'chóngfù', 'meaning': 'повторять; повторный'},
    '重新': {'pinyin': 'chóngxīn', 'meaning': 'снова, заново'},
    '出发': {'pinyin': 'chūfā', 'meaning': 'отправляться в путь'},
    '出国': {'pinyin': 'chūguó', 'meaning': 'ехать за границу'},
    '出口': {'pinyin': 'chūkǒu', 'meaning': 'выход'},
    '出门': {'pinyin': 'chūmén', 'meaning': 'выходить из дома'},
    '出生': {'pinyin': 'chūshēng', 'meaning': 'рождаться'},
    '出现': {'pinyin': 'chūxiàn', 'meaning': 'появляться'},
    '出院': {'pinyin': 'chūyuàn', 'meaning': 'выписываться из больницы'},
    '出租': {'pinyin': 'chūzū', 'meaning': 'сдавать в аренду'},
    '出租车': {'pinyin': 'chūzūchē', 'meaning': 'такси'},
    '船': {'pinyin': 'chuán', 'meaning': 'корабль, лодка'},
    '吹': {'pinyin': 'chuī', 'meaning': 'дуть; играть на духовых инструментах'},
    '春节': {'pinyin': 'Chūnjié', 'meaning': 'Китайский Новый год'},
    '春天': {'pinyin': 'chūntiān', 'meaning': 'весна'},
    '词': {'pinyin': 'cí', 'meaning': 'слово'},
    '词典': {'pinyin': 'cídiǎn', 'meaning': 'словарь'},
    '词语': {'pinyin': 'cíyǔ', 'meaning': 'слова, выражения'},
    '从小': {'pinyin': 'cóngxiǎo', 'meaning': 'с детства'},
    '答应': {'pinyin': 'dāying', 'meaning': 'откликаться; согласиться; обещать'},
    '打工': {'pinyin': 'dǎgōng', 'meaning': 'подрабатывать; работать временно'},
    '打算': {'pinyin': 'dǎsuàn', 'meaning': 'планировать, план'},
    '打印': {'pinyin': 'dǎyìn', 'meaning': 'распечатать; печать'},
    '大部分': {'pinyin': 'dàbùfen', 'meaning': 'большая часть, большинство'},
    '大大': {'pinyin': 'dàdà', 'meaning': 'сильно, значительно'},
    '大多数': {'pinyin': 'dàduōshù', 'meaning': 'большинство'},
    '大海': {'pinyin': 'dàhǎi', 'meaning': 'море, океан'},
    '大家': {'pinyin': 'dàjiā', 'meaning': 'все'},
    '大量': {'pinyin': 'dàliàng', 'meaning': 'большое количество; многочисленный'},
    '大门': {'pinyin': 'dàmén', 'meaning': 'главный вход, ворота'},
    '大人': {'pinyin': 'dàren', 'meaning': 'взрослый'},
    '大声': {'pinyin': 'dà shēng', 'meaning': 'громко, шумно'},
    '大小': {'pinyin': 'dàxiǎo', 'meaning': 'размер; большой или маленький'},
    '大衣': {'pinyin': 'dàyī', 'meaning': 'пальто, куртка'},
    '大自然': {'pinyin': 'dàzìrán', 'meaning': 'природа'},
    '带': {'pinyin': 'dài', 'meaning': 'носить; вести за собой; пояс'},
    '带来': {'pinyin': 'dàilái', 'meaning': 'приносить; вызывать'},
    '单位': {'pinyin': 'dānwèi', 'meaning': 'единица измерения; учреждение'},
    '但': {'pinyin': 'dàn', 'meaning': 'но, однако; только'},
    '但是': {'pinyin': 'dànshì', 'meaning': 'но, однако'},
    '蛋': {'pinyin': 'dàn', 'meaning': 'яйцо'},
    '当': {'pinyin': 'dāng', 'meaning': 'быть, являться; состоять'},
    '当时': {'pinyin': 'dāngshí', 'meaning': 'тогда, в то время'},
    '倒': {'pinyin': 'dào', 'meaning': 'наоборот; вверх дном'},
    '到处': {'pinyin': 'dàochù', 'meaning': 'повсюду, везде'},
    '道': {'pinyin': 'dào', 'meaning': 'счётное слово для рек, стен, дверей, блюд'},
    '道理': {'pinyin': 'dàolǐ', 'meaning': 'здравый смысл; основание, причина'},
    '道路': {'pinyin': 'dàolù', 'meaning': 'дорога, путь'},
    '得': {'pinyin': 'de', 'meaning': 'модификатор результативных глаголов'},
    '得出': {'pinyin': 'déchū', 'meaning': 'получить результат; приходить к заключению'},
    '的话': {'pinyin': 'dehuà', 'meaning': 'если; в случае, если'},
    '灯': {'pinyin': 'dēng', 'meaning': 'лампа, люстра; свет'},
    '等': {'pinyin': 'děng', 'meaning': 'и так далее, и тому подобное'},
    '等到': {'pinyin': 'děngdào', 'meaning': 'ко времени, когда'},
    '等于': {'pinyin': 'děngyú', 'meaning': 'быть равным, равняться'},
    '低': {'pinyin': 'dī', 'meaning': 'низкий'},
    '地球': {'pinyin': 'dìqiú', 'meaning': 'Земля, земной шар'},
    '地铁': {'pinyin': 'dìtiě', 'meaning': 'метро'},
    '地铁站': {'pinyin': 'dìtiězhàn', 'meaning': 'станция метро'},
    '点头': {'pinyin': 'diǎntóu', 'meaning': 'кивать'},
    '店': {'pinyin': 'diàn', 'meaning': 'магазин; гостиница'},
    '掉': {'pinyin': 'diào', 'meaning': 'падать; ронять; терять'},
    '东北': {'pinyin': 'dōngběi', 'meaning': 'северо-восток'},
    '东方': {'pinyin': 'dōngfāng', 'meaning': 'восток, Восток'},
    '东南': {'pinyin': 'dōngnán', 'meaning': 'юго-восток'},
    '冬天': {'pinyin': 'dōngtiān', 'meaning': 'зима'},
    '懂': {'pinyin': 'dǒng', 'meaning': 'понимать'},
    '懂得': {'pinyin': 'dǒngde', 'meaning': 'понимать, разбираться в'},
    '动物': {'pinyin': 'dòngwù', 'meaning': 'животное'},
    '动物园': {'pinyin': 'dòngwùyuán', 'meaning': 'зоопарк'},
    '读音': {'pinyin': 'dúyīn', 'meaning': 'произношение, чтение слова'},
    '度': {'pinyin': 'dù', 'meaning': 'степень; правило; градус'},
    '短': {'pinyin': 'duǎn', 'meaning': 'короткий'},
    '短信': {'pinyin': 'duǎnxìn', 'meaning': 'СМС, сообщение'},
    '段': {'pinyin': 'duàn', 'meaning': 'параграф; период времени; счётное слово'},
    '队': {'pinyin': 'duì', 'meaning': 'команда'},
    '队长': {'pinyin': 'duìzhǎng', 'meaning': 'капитан, лидер команды'},
    '对': {'pinyin': 'duì', 'meaning': 'стоять лицом к; сравнивать; противостоять'},
    '对话': {'pinyin': 'duìhuà', 'meaning': 'диалог'},
    '对面': {'pinyin': 'duìmiàn', 'meaning': 'напротив; противоположная сторона'},
    '多': {'pinyin': 'duō', 'meaning': 'много'},
    '多久': {'pinyin': 'duōjiǔ', 'meaning': 'как долго; как часто'},
    '多么': {'pinyin': 'duōme', 'meaning': 'так, до такой степени; насколько!'},
    '多数': {'pinyin': 'duōshù', 'meaning': 'большинство'},
    '多云': {'pinyin': 'duōyún', 'meaning': 'облачный'},
    '而且': {'pinyin': 'érqiě', 'meaning': 'но и; к тому же'},
    '发': {'pinyin': 'fā', 'meaning': 'посылать; испускать; развивать'},
    '发现': {'pinyin': 'fāxiàn', 'meaning': 'обнаружить'},
    '饭馆': {'pinyin': 'fànguǎn', 'meaning': 'ресторан, закусочная'},
    '方便': {'pinyin': 'fāngbiàn', 'meaning': 'удобный'},
    '方便面': {'pinyin': 'fāngbiànmiàn', 'meaning': 'лапша быстрого приготовления'},
    '方法': {'pinyin': 'fāngfǎ', 'meaning': 'способ, метод'},
    '方面': {'pinyin': 'fāngmiàn', 'meaning': 'сторона; аспект'},
    '方向': {'pinyin': 'fāngxiàng', 'meaning': 'направление; ориентация'},
    '放下': {'pinyin': 'fàngxia', 'meaning': 'класть, складывать'},
    '放心': {'pinyin': 'fàngxīn', 'meaning': 'успокаиваться; быть спокойным'},
    '分': {'pinyin': 'fēn', 'meaning': 'делить, отделять; распределять'},
    '分开': {'pinyin': 'fēnkāi', 'meaning': 'делить, разделять, расставаться'},
    '分数': {'pinyin': 'fēnshù', 'meaning': 'балл, оценка; дробь'},
    '分钟': {'pinyin': 'fēnzhōng', 'meaning': 'минута'},
    '份': {'pinyin': 'fèn', 'meaning': 'часть, доля; порция; экземпляр'},
    '封': {'pinyin': 'fēng', 'meaning': 'счётное слово для писем'},
    '服务': {'pinyin': 'fúwù', 'meaning': 'служить; услуга'},
    '复习': {'pinyin': 'fùxí', 'meaning': 'повторять'},
    '该': {'pinyin': 'gāi', 'meaning': 'должен, следует'},
    '改': {'pinyin': 'gǎi', 'meaning': 'изменяться; исправляться'},
    '改变': {'pinyin': 'gǎibiàn', 'meaning': 'изменять; изменение'},
    '干杯': {'pinyin': 'gānbēi', 'meaning': 'выпить до дна; ваше здоровье!'},
    '感到': {'pinyin': 'gǎndào', 'meaning': 'чувствовать, ощущать'},
    '感动': {'pinyin': 'gǎndòng', 'meaning': 'растрогаться; растрогать'},
    '感觉': {'pinyin': 'gǎnjué', 'meaning': 'чувство; ощущение; чувствовать'},
    '感谢': {'pinyin': 'gǎnxiè', 'meaning': 'быть благодарным; чувствительно благодарить'},
    '干活儿': {'pinyin': 'gànhuór', 'meaning': 'работать, трудиться'},
    '刚': {'pinyin': 'gāng', 'meaning': 'только что; твёрдый, стойкий'},
    '刚才': {'pinyin': 'gāngcái', 'meaning': 'только что'},
    '刚刚': {'pinyin': 'gānggāng', 'meaning': 'только что, только сейчас'},
    '高级': {'pinyin': 'gāojí', 'meaning': 'высшей ступени; первоклассный'},
    '高中': {'pinyin': 'gāozhōng', 'meaning': 'старшая ступень средней школы'},
    '个子': {'pinyin': 'gèzi', 'meaning': 'рост, комплекция, телосложение'},
    '更': {'pinyin': 'gèng', 'meaning': 'более'},
    '公共汽车': {'pinyin': 'gōnggòngqìchē', 'meaning': 'общественный автобус'},
    '公交车': {'pinyin': 'gōngjiāochē', 'meaning': 'автобус общественного транспорта'},
    '公斤': {'pinyin': 'gōngjīn', 'meaning': 'килограмм'},
    '公里': {'pinyin': 'gōnglǐ', 'meaning': 'километр'},
    '公路': {'pinyin': 'gōnglù', 'meaning': 'шоссе, автотрасса'},
    '公平': {'pinyin': 'gōngpíng', 'meaning': 'честный, справедливый'},
    '公司': {'pinyin': 'gōngsī', 'meaning': 'фирма, компания'},
    '公园': {'pinyin': 'gōngyuán', 'meaning': 'парк'},
    '狗': {'pinyin': 'gǒu', 'meaning': 'собака'},
    '够': {'pinyin': 'gòu', 'meaning': 'достаточно, хватает'},
    '故事': {'pinyin': 'gùshi', 'meaning': 'история, рассказ'},
    '故意': {'pinyin': 'gùyì', 'meaning': 'намеренно, умышленно'},
    '顾客': {'pinyin': 'gùkè', 'meaning': 'клиент, покупатель'},
    '关机': {'pinyin': 'guānjī', 'meaning': 'выключать (технику)'},
    '关心': {'pinyin': 'guānxīn', 'meaning': 'заботиться; забота'},
    '观点': {'pinyin': 'guāndiǎn', 'meaning': 'точка зрения; взгляд'},
    '广场': {'pinyin': 'guǎngchǎng', 'meaning': 'площадь; открытое пространство'},
    '广告': {'pinyin': 'guǎnggào', 'meaning': 'объявление; реклама'},
    '国际': {'pinyin': 'guójì', 'meaning': 'международный'},
    '过来': {'pinyin': 'guòlái', 'meaning': 'подходить, приходить'},
    '过年': {'pinyin': 'guònián', 'meaning': 'праздновать китайский Новый год'},
    '过去': {'pinyin': 'guòqù', 'meaning': 'пройти, сходить'},
    '过': {'pinyin': 'guo', 'meaning': 'глагольный суффикс прошедшего времени'},
    '海': {'pinyin': 'hǎi', 'meaning': 'море; крупное озеро'},
    '海边': {'pinyin': 'hǎibiān', 'meaning': 'берег моря, морское побережье'},
    '喊': {'pinyin': 'hǎn', 'meaning': 'кричать; окликать; звать'},
    '好': {'pinyin': 'hǎo', 'meaning': 'хорошо, хорошенько'},
    '好处': {'pinyin': 'hǎochù', 'meaning': 'преимущество; польза; выгода'},
    '好多': {'pinyin': 'hǎoduō', 'meaning': 'очень много'},
    '好久': {'pinyin': 'hǎojiǔ', 'meaning': 'долгое время'},
    '好人': {'pinyin': 'hǎorén', 'meaning': 'хороший, добрый человек'},
    '好事': {'pinyin': 'hǎoshì', 'meaning': 'доброе дело; радостное событие'},
    '好像': {'pinyin': 'hǎoxiàng', 'meaning': 'похоже, что; кажется'},
    '合适': {'pinyin': 'héshì', 'meaning': 'удобный, подходящий'},
    '河': {'pinyin': 'hé', 'meaning': 'река'},
    '黑': {'pinyin': 'hēi', 'meaning': 'черный, темный'},
    '黑板': {'pinyin': 'hēibǎn', 'meaning': 'доска (классная)'},
    '黑色': {'pinyin': 'hēisè', 'meaning': 'черный цвет'},
    '红': {'pinyin': 'hóng', 'meaning': 'красный; популярный'},
    '红色': {'pinyin': 'hóngsè', 'meaning': 'красный цвет'},
    '后来': {'pinyin': 'hòulái', 'meaning': 'впоследствии; потом, затем'},
    '忽然': {'pinyin': 'hūrán', 'meaning': 'вдруг, внезапно'},
    '湖': {'pinyin': 'hú', 'meaning': 'озеро'},
    '护照': {'pinyin': 'hùzhào', 'meaning': 'паспорт'},
    '花': {'pinyin': 'huā', 'meaning': 'тратить, расходовать'},
    '花园': {'pinyin': 'huāyuán', 'meaning': 'сад'},
    '画': {'pinyin': 'huà', 'meaning': 'рисовать; картина'},
    '画家': {'pinyin': 'huàjiā', 'meaning': 'художник, живописец'},
    '画儿': {'pinyin': 'huàr', 'meaning': 'картина, картинка, рисунок'},
    '坏处': {'pinyin': 'huàichù', 'meaning': 'недостаток, вред'},
    '坏人': {'pinyin': 'huàirén', 'meaning': 'плохой человек, злодей'},
    '欢迎': {'pinyin': 'huānyíng', 'meaning': 'добро пожаловать; приветствовать'},
    '换': {'pinyin': 'huàn', 'meaning': 'обменять, менять'},
    '黄': {'pinyin': 'huáng', 'meaning': 'желтый'},
    '黄色': {'pinyin': 'huángsè', 'meaning': 'желтый цвет'},
    '回': {'pinyin': 'huí', 'meaning': 'счётное слово для повторений'},
    '回国': {'pinyin': 'huíguó', 'meaning': 'возвращаться на родину'},
    '会': {'pinyin': 'huì', 'meaning': 'встреча, конференция'},
    '活动': {'pinyin': 'huódòng', 'meaning': 'мероприятие; деятельность; двигаться'},
    '或': {'pinyin': 'huò', 'meaning': 'или, либо; возможно'},
    '或者': {'pinyin': 'huòzhě', 'meaning': 'или'},
    '机会': {'pinyin': 'jīhuì', 'meaning': 'возможность, шанс'},
    '鸡': {'pinyin': 'jī', 'meaning': 'петух, курица'},
    '级': {'pinyin': 'jí', 'meaning': 'ранг, уровень; класс, год обучения'},
    '急': {'pinyin': 'jí', 'meaning': 'испытывать нетерпение; беспокоиться'},
    '计划': {'pinyin': 'jìhuà', 'meaning': 'план; планировать'},
    '计算机': {'pinyin': 'jìsuànjī', 'meaning': 'компьютер'},
    '加': {'pinyin': 'jiā', 'meaning': 'добавлять, увеличивать'},
    '加油': {'pinyin': 'jiāyóu', 'meaning': 'заправлять; поднажать, стараться'},
    '家': {'pinyin': 'jiā', 'meaning': 'суффикс существительных для представителей профессий'},
    '家庭': {'pinyin': 'jiātíng', 'meaning': 'семья; домашний'},
    '家长': {'pinyin': 'jiāzhǎng', 'meaning': 'родитель'},
    '假': {'pinyin': 'jiǎ', 'meaning': 'ложный; фальшивый; поддельный'},
    '假期': {'pinyin': 'jiàqī', 'meaning': 'каникулы, отпуск'},
    '检查': {'pinyin': 'jiǎnchá', 'meaning': 'проверять, проверка'},
    '见到': {'pinyin': 'jiàndào', 'meaning': 'увидеть, встретиться'},
    '见过': {'pinyin': 'jiànguo', 'meaning': 'видал, встречал'},
    '件': {'pinyin': 'jiàn', 'meaning': 'сч. слово для вещей, одежды, событий'},
    '健康': {'pinyin': 'jiànkāng', 'meaning': 'здоровый, здоровье'},
    '讲': {'pinyin': 'jiǎng', 'meaning': 'говорить, объяснять'},
    '讲话': {'pinyin': 'jiǎnghuà', 'meaning': 'говорить, разговаривать'},
    '交': {'pinyin': 'jiāo', 'meaning': 'сдавать; отдавать; водить знакомство'},
    '交给': {'pinyin': 'jiāogěi', 'meaning': 'давать; передавать, вручать'},
    '交朋友': {'pinyin': 'jiāopéngyou', 'meaning': 'дружить, заводить друзей'},
    '交通': {'pinyin': 'jiāotōng', 'meaning': 'движение; пути сообщения'},
    '角': {'pinyin': 'jiǎo', 'meaning': 'угол, рог'},
    '角度': {'pinyin': 'jiǎodù', 'meaning': 'угол; точка зрения'},
    '饺子': {'pinyin': 'jiǎozi', 'meaning': 'пельмени'},
    '脚': {'pinyin': 'jiǎo', 'meaning': 'нога; ступня'},
    '叫作': {'pinyin': 'jiàozuò', 'meaning': 'называть; называться'},
    '教师': {'pinyin': 'jiàoshī', 'meaning': 'учитель, преподаватель'},
    '教室': {'pinyin': 'jiàoshì', 'meaning': 'аудитория, класс'},
    '教学': {'pinyin': 'jiàoxué', 'meaning': 'обучение и учёба; учебный процесс'},
    '教育': {'pinyin': 'jiàoyù', 'meaning': 'образование; воспитывать'},
    '接': {'pinyin': 'jiē', 'meaning': 'встречать; получать; соединять'},
    '接到': {'pinyin': 'jiēdào', 'meaning': 'получить; подключить'},
    '接受': {'pinyin': 'jiēshòu', 'meaning': 'принимать; воспринять'},
    '接下来': {'pinyin': 'jiēxiàlái', 'meaning': 'следующий; далее'},
    '接着': {'pinyin': 'jiēzhe', 'meaning': 'затем, вслед затем; продолжать'},
    '街': {'pinyin': 'jiē', 'meaning': 'улица'},
    '节': {'pinyin': 'jié', 'meaning': 'сустав; узел; счётное слово'},
    '节目': {'pinyin': 'jiémù', 'meaning': 'программа'},
    '节日': {'pinyin': 'jiérì', 'meaning': 'праздник'},
    '结果': {'pinyin': 'jiéguǒ', 'meaning': 'результат, итог'},
    '借': {'pinyin': 'jiè', 'meaning': 'одалживать, занимать'},
    '斤': {'pinyin': 'jīn', 'meaning': 'цзинь (500 г); полкилограмма'},
    '今后': {'pinyin': 'jīnhòu', 'meaning': 'отныне, в дальнейшем'},
    '进入': {'pinyin': 'jìnrù', 'meaning': 'войти, вступить'},
    '进行': {'pinyin': 'jìnxíng', 'meaning': 'проводить; осуществлять'},
    '近': {'pinyin': 'jìn', 'meaning': 'ближний; близкий'},
    '经常': {'pinyin': 'jīngcháng', 'meaning': 'часто, регулярно'},
    '经过': {'pinyin': 'jīngguò', 'meaning': 'проходить через; испытывать'},
    '经理': {'pinyin': 'jīnglǐ', 'meaning': 'директор, менеджер'},
    '酒': {'pinyin': 'jiǔ', 'meaning': 'вино, алкоголь'},
    '酒店': {'pinyin': 'jiǔdiàn', 'meaning': 'гостиница, отель'},
    '就要': {'pinyin': 'jiùyào', 'meaning': 'вот-вот случится; следует'},
    '举': {'pinyin': 'jǔ', 'meaning': 'поднимать; приводить (пример)'},
    '举手': {'pinyin': 'jǔshǒu', 'meaning': 'поднимать руку'},
    '举行': {'pinyin': 'jǔxíng', 'meaning': 'проводить, устраивать'},
    '句': {'pinyin': 'jù', 'meaning': 'фраза, предложение'},
    '句子': {'pinyin': 'jùzi', 'meaning': 'предложение'},
    '卡': {'pinyin': 'kǎ', 'meaning': 'карта, карточка'},
    '开机': {'pinyin': 'kāijī', 'meaning': 'включать (технику)'},
    '开心': {'pinyin': 'kāixīn', 'meaning': 'весело; радоваться'},
    '开学': {'pinyin': 'kāixué', 'meaning': 'начало занятий; начать учёбу'},
    '看法': {'pinyin': 'kànfǎ', 'meaning': 'точка зрения, мнение'},
    '考生': {'pinyin': 'kǎoshēng', 'meaning': 'экзаменующийся'},
    '靠': {'pinyin': 'kào', 'meaning': 'находиться вплотную к; прилегать к'},
    '科': {'pinyin': 'kē', 'meaning': 'учебный предмет; дисциплина; кафедра'},
    '科学': {'pinyin': 'kēxué', 'meaning': 'наука; научный'},
    '可爱': {'pinyin': 'kěài', 'meaning': 'милый'},
    '可能': {'pinyin': 'kěnéng', 'meaning': 'возможно; возможность'},
    '可怕': {'pinyin': 'kěpà', 'meaning': 'страшный; ужасный'},
    '可是': {'pinyin': 'kěshì', 'meaning': 'но, однако'},
    '可以': {'pinyin': 'kěyǐ', 'meaning': 'мочь (разрешено)'},
    '克': {'pinyin': 'kè', 'meaning': 'грамм; справиться'},
    '刻': {'pinyin': 'kè', 'meaning': 'четверть (часа); момент'},
    '客人': {'pinyin': 'kèrén', 'meaning': 'гость'},
    '课堂': {'pinyin': 'kètáng', 'meaning': 'классная комната'},
    '空气': {'pinyin': 'kōngqì', 'meaning': 'воздух, атмосфера'},
    '哭': {'pinyin': 'kū', 'meaning': 'плакать'},
    '快餐': {'pinyin': 'kuàicān', 'meaning': 'быстрая еда, фаст-фуд'},
    '快点儿': {'pinyin': 'kuài diǎnr', 'meaning': 'поторопись, побыстрее'},
    '快乐': {'pinyin': 'kuàilè', 'meaning': 'весёлый'},
    '快要': {'pinyin': 'kuàiyào', 'meaning': 'вот-вот, скоро'},
    '筷子': {'pinyin': 'kuàizi', 'meaning': 'палочки для еды'},
    '拉': {'pinyin': 'lā', 'meaning': 'тянуть; вести за собой'},
    '来自': {'pinyin': 'láizì', 'meaning': 'происходить из; от (чего-либо)'},
    '蓝': {'pinyin': 'lán', 'meaning': 'голубой; синий'},
    '蓝色': {'pinyin': 'lánsè', 'meaning': 'синий цвет'},
    '篮球': {'pinyin': 'lánqiú', 'meaning': 'баскетбол'},
    '老': {'pinyin': 'lǎo', 'meaning': 'вежливый префикс перед именами'},
    '老年': {'pinyin': 'lǎonián', 'meaning': 'старость, преклонный возраст'},
    '老朋友': {'pinyin': 'lǎopéngyou', 'meaning': 'старый друг'},
    '老是': {'pinyin': 'lǎoshì', 'meaning': 'всегда'},
    '离': {'pinyin': 'lí', 'meaning': 'разлучаться; отстоять на расстоянии'},
    '离开': {'pinyin': 'líkāi', 'meaning': 'покидать, уходить'},
    '礼物': {'pinyin': 'lǐwù', 'meaning': 'подарок'},
    '里头': {'pinyin': 'lǐtou', 'meaning': 'внутри'},
    '理想': {'pinyin': 'lǐxiǎng', 'meaning': 'идеал, мечта'},
    '例如': {'pinyin': 'lìrú', 'meaning': 'например'},
    '例子': {'pinyin': 'lìzi', 'meaning': 'пример'},
    '脸': {'pinyin': 'liǎn', 'meaning': 'лицо'},
    '练': {'pinyin': 'liàn', 'meaning': 'практиковать'},
    '练习': {'pinyin': 'liànxí', 'meaning': 'упражняться, упражнение'},
    '凉': {'pinyin': 'liáng', 'meaning': 'прохладный; студёный'},
    '凉快': {'pinyin': 'liángkuai', 'meaning': 'прохладный; прохлада'},
    '两': {'pinyin': 'liǎng', 'meaning': 'сч. слово: пятьдесят граммов'},
    '亮': {'pinyin': 'liàng', 'meaning': 'светлый, яркий; блестеть'},
    '辆': {'pinyin': 'liàng', 'meaning': 'счётное слово для наземного транспорта'},
    '零下': {'pinyin': 'líng xià', 'meaning': 'ниже нуля'},
    '留': {'pinyin': 'liú', 'meaning': 'остаться; задержать; сохранить'},
    '留下': {'pinyin': 'liúxià', 'meaning': 'оставлять; оставаться'},
    '留学生': {'pinyin': 'liúxuéshēng', 'meaning': 'студент за рубежом; иностранный студент'},
    '流': {'pinyin': 'liú', 'meaning': 'литься'},
    '流利': {'pinyin': 'liúlì', 'meaning': 'свободный, беглый'},
    '流行': {'pinyin': 'liúxíng', 'meaning': 'модный; популярный'},
    '路边': {'pinyin': 'lùbiān', 'meaning': 'обочина; край дороги'},
    '旅客': {'pinyin': 'lǚkè', 'meaning': 'пассажир; путешественник'},
    '旅行': {'pinyin': 'lǚxíng', 'meaning': 'путешествовать; путешествие'},
    '旅游': {'pinyin': 'lǚyóu', 'meaning': 'путешествовать'},
    '绿': {'pinyin': 'lǜ', 'meaning': 'зеленый'},
    '绿色': {'pinyin': 'lǜsè', 'meaning': 'зеленый цвет'},
    '卖': {'pinyin': 'mài', 'meaning': 'продавать'},
    '满': {'pinyin': 'mǎn', 'meaning': 'полный; наполнять; довольный'},
    '满意': {'pinyin': 'mǎnyì', 'meaning': 'удовлетворённый'},
    '猫': {'pinyin': 'māo', 'meaning': 'кошка'},
    '米': {'pinyin': 'mǐ', 'meaning': 'метр (счётное слово)'},
    '面': {'pinyin': 'miàn', 'meaning': 'лапша; лицо; поверхность'},
    '面前': {'pinyin': 'miànqián', 'meaning': 'перед лицом, в присутствии'},
    '名': {'pinyin': 'míng', 'meaning': 'имя; называться'},
    '名称': {'pinyin': 'míngchēng', 'meaning': 'имя, название'},
    '名单': {'pinyin': 'míngdān', 'meaning': 'список с именами'},
    '明星': {'pinyin': 'míngxīng', 'meaning': 'звезда; знаменитость'},
    '目的': {'pinyin': 'mùdì', 'meaning': 'цель; намерение'},
    '拿出': {'pinyin': 'náchū', 'meaning': 'вынимать, доставать'},
    '拿到': {'pinyin': 'nádào', 'meaning': 'приносить; получать'},
    '那': {'pinyin': 'nà', 'meaning': 'в таком случае; следовательно'},
    '那会儿': {'pinyin': 'nàhuìr', 'meaning': 'в тот момент, тогда'},
    '那么': {'pinyin': 'nàme', 'meaning': 'так, таким образом; тогда'},
    '那时候': {'pinyin': 'nà shíhou', 'meaning': 'тогда, в то время'},
    '那样': {'pinyin': 'nàyàng', 'meaning': 'такой; так; таким образом'},
    '南方': {'pinyin': 'nánfāng', 'meaning': 'южная часть страны'},
    '难过': {'pinyin': 'nánguò', 'meaning': 'грустить; тяжело переживать'},
    '难看': {'pinyin': 'nánkàn', 'meaning': 'некрасивый, уродливый'},
    '难受': {'pinyin': 'nánshòu', 'meaning': 'страдать; чувствовать себя плохо'},
    '难题': {'pinyin': 'nántí', 'meaning': 'сложная проблема'},
    '难听': {'pinyin': 'nántīng', 'meaning': 'неприятный для уха'},
    '能够': {'pinyin': 'nénggòu', 'meaning': 'быть в состоянии, мочь'},
    '年级': {'pinyin': 'niánjí', 'meaning': 'класс, курс (учебный)'},
    '年轻': {'pinyin': 'niánqīng', 'meaning': 'молодой'},
    '鸟': {'pinyin': 'niǎo', 'meaning': 'птица'},
    '弄': {'pinyin': 'nòng', 'meaning': 'делать; достать; добыть'},
    '努力': {'pinyin': 'nǔlì', 'meaning': 'стараться; усердие'},
    '爬': {'pinyin': 'pá', 'meaning': 'ползать; карабкаться'},
    '爬山': {'pinyin': 'páshān', 'meaning': 'ходить в горы; лазить по горам'},
    '怕': {'pinyin': 'pà', 'meaning': 'бояться, опасаться'},
    '排': {'pinyin': 'pái', 'meaning': 'ряд, линия; взвод'},
    '排队': {'pinyin': 'páiduì', 'meaning': 'стоять в очереди'},
    '排球': {'pinyin': 'páiqiú', 'meaning': 'волейбол'},
    '碰': {'pinyin': 'pèng', 'meaning': 'встречаться с; наталкиваться на'},
    '碰到': {'pinyin': 'pèngdào', 'meaning': 'встречаться с; дотрагиваться до'},
    '碰见': {'pinyin': 'pèngjiàn', 'meaning': 'встречаться, сталкиваться с'},
    '篇': {'pinyin': 'piān', 'meaning': 'глава; сч. слово для статей'},
    '便宜': {'pinyin': 'piányi', 'meaning': 'дешевый'},
    '片': {'pinyin': 'piàn', 'meaning': 'карточка; таблетка; ломтик; сч. слово'},
    '漂亮': {'pinyin': 'piàoliang', 'meaning': 'красивый, прекрасный'},
    '平': {'pinyin': 'píng', 'meaning': 'ровный; горизонтальный; плоский'},
    '平安': {'pinyin': 'píngān', 'meaning': 'благополучный; спокойствие'},
    '平常': {'pinyin': 'píngcháng', 'meaning': 'обычный; нормальный'},
    '平等': {'pinyin': 'píngděng', 'meaning': 'равенство; равноправный'},
    '平时': {'pinyin': 'píngshí', 'meaning': 'обычно; в обычное время'},
    '瓶': {'pinyin': 'píng', 'meaning': 'бутылка; ваза'},
    '瓶子': {'pinyin': 'píngzi', 'meaning': 'бутылка'},
    '普通': {'pinyin': 'pǔtōng', 'meaning': 'обычный, простой'},
    '普通话': {'pinyin': 'pǔtōnghuà', 'meaning': 'путунхуа — официальный китайский язык'},
    '其他': {'pinyin': 'qítā', 'meaning': 'другой; остальной'},
    '其中': {'pinyin': 'qízhōng', 'meaning': 'среди них; в том числе'},
    '骑': {'pinyin': 'qí', 'meaning': 'ездить верхом (на коне, велосипеде)'},
    '骑车': {'pinyin': 'qíchē', 'meaning': 'ездить на велосипеде'},
    '起飞': {'pinyin': 'qǐfēi', 'meaning': 'взлетать'},
    '气': {'pinyin': 'qì', 'meaning': 'газ; воздух; злиться; злить'},
    '气温': {'pinyin': 'qìwēn', 'meaning': 'температура воздуха'},
    '千': {'pinyin': 'qiān', 'meaning': 'тысяча'},
    '千克': {'pinyin': 'qiānkè', 'meaning': 'килограмм'},
    '前年': {'pinyin': 'qiánnián', 'meaning': 'позапрошлый год'},
    '墙': {'pinyin': 'qiáng', 'meaning': 'стена; ограда'},
    '青年': {'pinyin': 'qīngnián', 'meaning': 'молодёжь'},
    '青少年': {'pinyin': 'qīngshàonián', 'meaning': 'подростки; подрастающее поколение'},
    '轻': {'pinyin': 'qīng', 'meaning': 'лёгкий; легко'},
    '清楚': {'pinyin': 'qīngchu', 'meaning': 'ясный, понятный, отчётливый'},
    '晴': {'pinyin': 'qíng', 'meaning': 'солнечный, ясный'},
    '晴天': {'pinyin': 'qíngtiān', 'meaning': 'солнечный день'},
    '请客': {'pinyin': 'qǐngkè', 'meaning': 'приглашать в гости, угощать'},
    '请求': {'pinyin': 'qǐngqiú', 'meaning': 'просить; просьба'},
    '秋天': {'pinyin': 'qiūtiān', 'meaning': 'осень'},
    '求': {'pinyin': 'qiú', 'meaning': 'просить; искать; требовать'},
    '球场': {'pinyin': 'qiúchǎng', 'meaning': 'спортивная площадка; стадион'},
    '球队': {'pinyin': 'qiúduì', 'meaning': 'команда (в играх с мячом)'},
    '球鞋': {'pinyin': 'qiúxié', 'meaning': 'спортивная обувь; кроссовки'},
    '取': {'pinyin': 'qǔ', 'meaning': 'брать; получить'},
    '取得': {'pinyin': 'qǔdé', 'meaning': 'достигать, получать'},
    '全': {'pinyin': 'quán', 'meaning': 'полный; целый; весь; полностью'},
    '全部': {'pinyin': 'quánbù', 'meaning': 'целиком; полностью; весь'},
    '全国': {'pinyin': 'quánguó', 'meaning': 'вся страна'},
    '全家': {'pinyin': 'quánjiā', 'meaning': 'вся семья'},
    '全年': {'pinyin': 'quánnián', 'meaning': 'целый год'},
    '全身': {'pinyin': 'quánshēn', 'meaning': 'весь; с головы до ног'},
    '全体': {'pinyin': 'quántǐ', 'meaning': 'все сотрудники; полный состав'},
    '然后': {'pinyin': 'ránhòu', 'meaning': 'а потом, а затем; только после'},
    '让': {'pinyin': 'ràng', 'meaning': 'позволять; просить; заставить'},
    '热情': {'pinyin': 'rèqíng', 'meaning': 'сердечность; пылкость; энтузиазм'},
    '人口': {'pinyin': 'rénkǒu', 'meaning': 'население'},
    '人们': {'pinyin': 'rénmen', 'meaning': 'люди'},
    '人数': {'pinyin': 'rénshù', 'meaning': 'количество людей'},
    '认为': {'pinyin': 'rènwéi', 'meaning': 'считать, полагать'},
    '日报': {'pinyin': 'rìbào', 'meaning': 'ежедневная газета'},
    '日子': {'pinyin': 'rìzi', 'meaning': 'день; срок; дата'},
    '如果': {'pinyin': 'rúguǒ', 'meaning': 'если; если бы'},
    '入口': {'pinyin': 'rùkǒu', 'meaning': 'вход'},
    '商量': {'pinyin': 'shāngliang', 'meaning': 'консультироваться; совещаться'},
    '商人': {'pinyin': 'shāngrén', 'meaning': 'коммерсант, бизнесмен'},
    '上周': {'pinyin': 'shàngzhōu', 'meaning': 'прошлая неделя'},
    '少数': {'pinyin': 'shǎoshù', 'meaning': 'немногие; меньшинство'},
    '少年': {'pinyin': 'shàonián', 'meaning': 'подросток, молодой человек'},
    '身边': {'pinyin': 'shēnbiān', 'meaning': 'около себя; при себе'},
    '什么样': {'pinyin': 'shénmeyàng', 'meaning': 'какой; какого рода'},
    '生': {'pinyin': 'shēng', 'meaning': 'рождать; расти; возникать'},
    '生词': {'pinyin': 'shēngcí', 'meaning': 'новое слово'},
    '生活': {'pinyin': 'shēnghuó', 'meaning': 'жизнь; жить; быт'},
    '声音': {'pinyin': 'shēngyīn', 'meaning': 'голос, звук'},
    '省': {'pinyin': 'shěng', 'meaning': 'экономить; сокращать'},
    '十分': {'pinyin': 'shífēn', 'meaning': 'в полной мере; весьма, очень'},
    '实际': {'pinyin': 'shíjì', 'meaning': 'реальный; реальность; действительность'},
    '实习': {'pinyin': 'shíxí', 'meaning': 'стажироваться; практика'},
    '实现': {'pinyin': 'shíxiàn', 'meaning': 'реализовать; претворить в жизнь'},
    '实在': {'pinyin': 'shízai', 'meaning': 'крепкий; основательный'},
    '食物': {'pinyin': 'shíwù', 'meaning': 'пища; еда'},
    '使用': {'pinyin': 'shǐyòng', 'meaning': 'использовать; применять'},
    '市': {'pinyin': 'shì', 'meaning': 'город; рынок'},
    '市长': {'pinyin': 'shìzhǎng', 'meaning': 'мэр'},
    '事情': {'pinyin': 'shìqing', 'meaning': 'дело, событие; случай'},
    '收': {'pinyin': 'shōu', 'meaning': 'получать; собирать; принимать'},
    '收到': {'pinyin': 'shōudào', 'meaning': 'получать'},
    '收入': {'pinyin': 'shōurù', 'meaning': 'доход; поступления'},
    '手表': {'pinyin': 'shǒubiǎo', 'meaning': 'наручные часы'},
    '受到': {'pinyin': 'shòudào', 'meaning': 'получить; подвергнуться'},
    '舒服': {'pinyin': 'shūfu', 'meaning': 'удобный; хорошо себя чувствовать'},
    '熟': {'pinyin': 'shú', 'meaning': 'готовый; спелый, зрелый; знакомый'},
    '数': {'pinyin': 'shǔ', 'meaning': 'число; несколько'},
    '数字': {'pinyin': 'shùzì', 'meaning': 'цифра; цифровой'},
    '水平': {'pinyin': 'shuǐpíng', 'meaning': 'уровень, стандарт'},
    '顺利': {'pinyin': 'shùnlì', 'meaning': 'успешно; благоприятно'},
    '说明': {'pinyin': 'shuōmíng', 'meaning': 'объяснить; свидетельствовать; пояснение'},
    '司机': {'pinyin': 'sījī', 'meaning': 'шофёр, водитель'},
    '送到': {'pinyin': 'sòngdào', 'meaning': 'отправлять, относить'},
    '送给': {'pinyin': 'sònggěi', 'meaning': 'дарить; отправлять'},
    '算': {'pinyin': 'suàn', 'meaning': 'считать, вычислять'},
    '虽然': {'pinyin': 'suīrán', 'meaning': 'хотя, несмотря на'},
    '随便': {'pinyin': 'suíbiàn', 'meaning': 'как угодно; необдуманно'},
    '随时': {'pinyin': 'suíshí', 'meaning': 'в любое время; всегда'},
    '所以': {'pinyin': 'suǒyǐ', 'meaning': 'поэтому, таким образом'},
    '所有': {'pinyin': 'suǒyǒu', 'meaning': 'всё, все; имущество'},
    '它': {'pinyin': 'tā', 'meaning': 'оно (про неодушевлённые объекты)'},
    '它们': {'pinyin': 'tāmen', 'meaning': 'они (о животных)'},
    '太太': {'pinyin': 'tàitai', 'meaning': 'госпожа; супруга, жена'},
    '太阳': {'pinyin': 'tàiyáng', 'meaning': 'солнце'},
    '态度': {'pinyin': 'tàidu', 'meaning': 'отношение; поведение'},
    '讨论': {'pinyin': 'tǎolùn', 'meaning': 'обсуждать; прения, обсуждение'},
    '套': {'pinyin': 'tào', 'meaning': 'футляр; чехол; обёртка'},
    '特别': {'pinyin': 'tèbié', 'meaning': 'особенно, особенный'},
    '特点': {'pinyin': 'tèdiǎn', 'meaning': 'особенность; своеобразие'},
    '疼': {'pinyin': 'téng', 'meaning': 'больно, болезненный'},
    '提': {'pinyin': 'tí', 'meaning': 'держать в руке; поднимать; выдвигать'},
    '提出': {'pinyin': 'tíchū', 'meaning': 'выдвигать; предлагать'},
    '提到': {'pinyin': 'tídào', 'meaning': 'упоминать; касаться'},
    '提高': {'pinyin': 'tígāo', 'meaning': 'повышать'},
    '题': {'pinyin': 'tí', 'meaning': 'тема, вопрос; упоминать'},
    '体育': {'pinyin': 'tǐyù', 'meaning': 'физкультура, спорт'},
    '体育场': {'pinyin': 'tǐyùchǎng', 'meaning': 'стадион'},
    '体育馆': {'pinyin': 'tǐyùguǎn', 'meaning': 'спортивный зал'},
    '天上': {'pinyin': 'tiānshàng', 'meaning': 'небо, небеса'},
    '条': {'pinyin': 'tiáo', 'meaning': 'линия; сч. слово для продолговатых объектов'},
    '条件': {'pinyin': 'tiáojiàn', 'meaning': 'условие; обстоятельства'},
    '听讲': {'pinyin': 'tīngjiǎng', 'meaning': 'слушать объяснение; посещать лекции'},
    '听说': {'pinyin': 'tīngshuō', 'meaning': 'слышно, что; как говорят'},
    '停': {'pinyin': 'tíng', 'meaning': 'останавливать(ся); прекращать(ся)'},
    '停车': {'pinyin': 'tíngchē', 'meaning': 'останавливать автомобиль; парковаться'},
    '停车场': {'pinyin': 'tíngchēchǎng', 'meaning': 'парковка, стоянка для машин'},
    '挺': {'pinyin': 'tǐng', 'meaning': 'очень; крайне; в высшей степени'},
    '挺好': {'pinyin': 'tǐng hǎo', 'meaning': 'очень хороший, отличный'},
    '通': {'pinyin': 'tōng', 'meaning': 'проходить; пропускать; сквозной'},
    '通过': {'pinyin': 'tōngguò', 'meaning': 'проходить через; посредством; принять'},
    '通知': {'pinyin': 'tōngzhī', 'meaning': 'сообщать; уведомление'},
    '同时': {'pinyin': 'tóngshí', 'meaning': 'одновременно; в то же время'},
    '同事': {'pinyin': 'tóngshì', 'meaning': 'коллега, товарищ по работе'},
    '同样': {'pinyin': 'tóngyàng', 'meaning': 'одинаковый, равный'},
    '头': {'pinyin': 'tou', 'meaning': 'словообразующий суффикс существительных'},
    '头发': {'pinyin': 'tóufa', 'meaning': 'волосы'},
    '图片': {'pinyin': 'túpiàn', 'meaning': 'рисунок, картинка, фотография'},
    '推': {'pinyin': 'tuī', 'meaning': 'толкать; перекладывать; отклонять'},
    '腿': {'pinyin': 'tuǐ', 'meaning': 'нога'},
    '外地': {'pinyin': 'wàidì', 'meaning': 'другие края; за пределами данного места'},
    '外卖': {'pinyin': 'wàimài', 'meaning': 'еда на вынос; доставка еды'},
    '完': {'pinyin': 'wán', 'meaning': 'заканчивать (результативная морфема)'},
    '完成': {'pinyin': 'wánchéng', 'meaning': 'закончить; выполнить'},
    '完全': {'pinyin': 'wánquán', 'meaning': 'полный; полностью; совсем'},
    '晚安': {'pinyin': 'wǎnān', 'meaning': 'Спокойной ночи'},
    '晚报': {'pinyin': 'wǎnbào', 'meaning': 'вечерняя газета'},
    '晚餐': {'pinyin': 'wǎncān', 'meaning': 'ужин'},
    '晚会': {'pinyin': 'wǎnhuì', 'meaning': 'вечеринка, праздничный вечер'},
    '碗': {'pinyin': 'wǎn', 'meaning': 'плошка, пиала; счётное слово'},
    '万': {'pinyin': 'wàn', 'meaning': '10 000, десять тысяч'},
    '网': {'pinyin': 'wǎng', 'meaning': 'сеть, сетка; поймать сетью'},
    '网球': {'pinyin': 'wǎngqiú', 'meaning': 'теннис; теннисный мяч'},
    '网站': {'pinyin': 'wǎngzhàn', 'meaning': 'сайт, веб-сайт'},
    '往': {'pinyin': 'wǎng', 'meaning': 'к; по направлению к; прошлое'},
    '为': {'pinyin': 'wèi', 'meaning': 'для; из-за; в качестве'},
    '为什么': {'pinyin': 'wèishénme', 'meaning': 'почему? зачем?'},
    '位': {'pinyin': 'wèi', 'meaning': 'уважительное счётное слово для личностей'},
    '味道': {'pinyin': 'wèidào', 'meaning': 'вкус; запах; привкус'},
    '喂': {'pinyin': 'wèi', 'meaning': 'эй!'},
    '温度': {'pinyin': 'wēndù', 'meaning': 'температура'},
    '闻': {'pinyin': 'wén', 'meaning': 'услышать; нюхать; обонять'},
    '问路': {'pinyin': 'wènlù', 'meaning': 'спрашивать дорогу'},
    '问题': {'pinyin': 'wèntí', 'meaning': 'вопрос, проблема'},
    '午餐': {'pinyin': 'wǔcān', 'meaning': 'обед'},
    '午睡': {'pinyin': 'wǔshuì', 'meaning': 'дрёмать днём; послеобеденный сон'},
    '西北': {'pinyin': 'xīběi', 'meaning': 'северо-запад'},
    '西餐': {'pinyin': 'xīcān', 'meaning': 'западная кухня'},
    '西方': {'pinyin': 'xīfāng', 'meaning': 'запад, западная сторона'},
    '西南': {'pinyin': 'xīnán', 'meaning': 'юго-запад'},
    '西医': {'pinyin': 'xīyī', 'meaning': 'западная медицина'},
    '习惯': {'pinyin': 'xíguàn', 'meaning': 'привыкать; привычка'},
    '洗衣机': {'pinyin': 'xǐyījī', 'meaning': 'стиральная машина'},
    '洗澡': {'pinyin': 'xǐzǎo', 'meaning': 'мыться, купаться'},
    '下': {'pinyin': 'xià', 'meaning': 'сч. слово (повторение действия)'},
    '下雪': {'pinyin': 'xiàxuě', 'meaning': 'выпадать (о снеге)'},
    '下周': {'pinyin': 'xiàzhōu', 'meaning': 'следующая неделя'},
    '夏天': {'pinyin': 'xiàtiān', 'meaning': 'лето'},
    '相同': {'pinyin': 'xiāngtóng', 'meaning': 'одинаковый; тождественный'},
    '相信': {'pinyin': 'xiāngxìn', 'meaning': 'верить, поверить'},
    '响': {'pinyin': 'xiǎng', 'meaning': 'звучный; звучать; греметь'},
    '想到': {'pinyin': 'xiǎngdào', 'meaning': 'думать о; предвидеть'},
    '想法': {'pinyin': 'xiǎngfǎ', 'meaning': 'идея, мысль'},
    '想起': {'pinyin': 'xiǎngqǐ', 'meaning': 'вспоминать; воскрешать в памяти'},
    '向': {'pinyin': 'xiàng', 'meaning': 'в направлении к (предлог)'},
    '相机': {'pinyin': 'xiàngjī', 'meaning': 'фотоаппарат, фотокамера'},
    '像': {'pinyin': 'xiàng', 'meaning': 'напоминать; выглядеть как; быть как'},
    '小': {'pinyin': 'xiǎo', 'meaning': 'ласкательный или уменьшительный префикс'},
    '小声': {'pinyin': 'xiǎoshēng', 'meaning': 'тихо, вполголоса, шёпотом'},
    '小时候': {'pinyin': 'xiǎoshíhou', 'meaning': 'детство'},
    '小说': {'pinyin': 'xiǎoshuō', 'meaning': 'роман'},
    '小心': {'pinyin': 'xiǎoxīn', 'meaning': 'осторожно; быть осторожным'},
    '小组': {'pinyin': 'xiǎozǔ', 'meaning': 'небольшая группа'},
    '校园': {'pinyin': 'xiàoyuán', 'meaning': 'кампус, территория университета'},
    '校长': {'pinyin': 'xiàozhǎng', 'meaning': 'директор школы'},
    '笑话': {'pinyin': 'xiàohuà', 'meaning': 'шутка, анекдот'},
    '笑话儿': {'pinyin': 'xiàohuàr', 'meaning': 'шутка, анекдот, чепуха'},
    '鞋': {'pinyin': 'xié', 'meaning': 'обувь'},
    '心里': {'pinyin': 'xīnli', 'meaning': 'в душе, в уме'},
    '心情': {'pinyin': 'xīnqíng', 'meaning': 'настроение'},
    '心中': {'pinyin': 'xīnzhōng', 'meaning': 'в сердце, в мыслях'},
    '新闻': {'pinyin': 'xīnwén', 'meaning': 'новости'},
    '信': {'pinyin': 'xìn', 'meaning': 'письмо; сообщение, новость'},
    '信号': {'pinyin': 'xìnhào', 'meaning': 'сигнал; сигнальный'},
    '信息': {'pinyin': 'xìnxī', 'meaning': 'информация; сведения'},
    '信心': {'pinyin': 'xìnxīn', 'meaning': 'вера; уверенность в своих силах'},
    '信用卡': {'pinyin': 'xìnyòngkǎ', 'meaning': 'кредитная карта'},
    '星星': {'pinyin': 'xīngxing', 'meaning': 'звезда'},
    '行动': {'pinyin': 'xíngdòng', 'meaning': 'двигаться; действие; акт'},
    '行人': {'pinyin': 'xíngrén', 'meaning': 'пешеход; прохожий'},
    '行为': {'pinyin': 'xíngwéi', 'meaning': 'действие; поведение'},
    '姓': {'pinyin': 'xìng', 'meaning': 'фамилия; иметь такую-то фамилию'},
    '姓名': {'pinyin': 'xìngmíng', 'meaning': 'полное имя; фамилия и имя'},
    '休假': {'pinyin': 'xiūjià', 'meaning': 'быть в отпуске'},
    '许多': {'pinyin': 'xǔduō', 'meaning': 'очень много'},
    '选': {'pinyin': 'xuǎn', 'meaning': 'выбирать, избирать'},
    '学期': {'pinyin': 'xuéqī', 'meaning': 'семестр'},
    '雪': {'pinyin': 'xuě', 'meaning': 'снег'},
    '颜色': {'pinyin': 'yánsè', 'meaning': 'цвет'},
    '眼': {'pinyin': 'yǎn', 'meaning': 'глаз; взгляд; зрение'},
    '眼睛': {'pinyin': 'yǎnjing', 'meaning': 'глаз(-а)'},
    '养': {'pinyin': 'yǎng', 'meaning': 'держать (питомцев); растить; поправлять здоровье'},
    '样子': {'pinyin': 'yàngzi', 'meaning': 'образец; вид; образ; видимость'},
    '要求': {'pinyin': 'yāoqiú', 'meaning': 'требовать; запрашивать'},
    '药': {'pinyin': 'yào', 'meaning': 'лекарство, препарат'},
    '药店': {'pinyin': 'yàodiàn', 'meaning': 'аптека'},
    '药片': {'pinyin': 'yàopiàn', 'meaning': 'таблетка, пилюля'},
    '药水': {'pinyin': 'yàoshuǐ', 'meaning': 'микстура, жидкое лекарство'},
    '也许': {'pinyin': 'yěxǔ', 'meaning': 'возможно'},
    '夜': {'pinyin': 'yè', 'meaning': 'ночь; ночной'},
    '夜里': {'pinyin': 'yèli', 'meaning': 'ночью, в ночное время'},
    '一部分': {'pinyin': 'yíbùfen', 'meaning': 'часть, доля'},
    '一定': {'pinyin': 'yídìng', 'meaning': 'обязательно, точно'},
    '一共': {'pinyin': 'yígòng', 'meaning': 'всего'},
    '一会儿': {'pinyin': 'yíhuìr', 'meaning': 'немного; вскоре'},
    '一路平安': {'pinyin': 'yílùpíngān', 'meaning': 'Счастливого пути!'},
    '一路顺风': {'pinyin': 'yílùshùnfēng', 'meaning': 'Попутного ветра!'},
    '已经': {'pinyin': 'yǐjīng', 'meaning': 'уже'},
    '以后': {'pinyin': 'yǐhòu', 'meaning': 'после, потом, позже'},
    '以前': {'pinyin': 'yǐqián', 'meaning': 'раньше, до'},
    '以上': {'pinyin': 'yǐshàng', 'meaning': 'больше чем; свыше'},
    '以外': {'pinyin': 'yǐwài', 'meaning': 'вне; кроме; за исключением'},
    '以为': {'pinyin': 'yǐwéi', 'meaning': 'полагать, считать'},
    '以下': {'pinyin': 'yǐxià', 'meaning': 'ниже; менее; до'},
    '椅子': {'pinyin': 'yǐzi', 'meaning': 'стул'},
    '一般': {'pinyin': 'yìbān', 'meaning': 'обычно; как правило'},
    '一点点': {'pinyin': 'yìdiǎndiǎn', 'meaning': 'немного'},
    '一生': {'pinyin': 'yìshēng', 'meaning': 'вся жизнь'},
    '一直': {'pinyin': 'yìzhí', 'meaning': 'прямо; постоянно; всё время'},
    '亿': {'pinyin': 'yì', 'meaning': 'сто миллионов'},
    '意见': {'pinyin': 'yìjiàn', 'meaning': 'мнение, взгляд; точка зрения'},
    '意思': {'pinyin': 'yìsi', 'meaning': 'смысл, значение; интерес'},
    '因为': {'pinyin': 'yīnwèi', 'meaning': 'потому что, из-за'},
    '阴': {'pinyin': 'yīn', 'meaning': 'тёмный; скрытый; инь'},
    '阴天': {'pinyin': 'yīntiān', 'meaning': 'пасмурное небо'},
    '音节': {'pinyin': 'yīnjié', 'meaning': 'слог'},
    '音乐': {'pinyin': 'yīnyuè', 'meaning': 'музыка'},
    '音乐会': {'pinyin': 'yīnyuèhuì', 'meaning': 'музыкальный концерт'},
    '银行': {'pinyin': 'yínháng', 'meaning': 'банк'},
    '银行卡': {'pinyin': 'yínhángkǎ', 'meaning': 'банковская карта'},
    '应该': {'pinyin': 'yīnggāi', 'meaning': 'должен; следует; необходимо'},
    '英文': {'pinyin': 'Yīngwén', 'meaning': 'английский язык; английский текст'},
    '英语': {'pinyin': 'Yīngyǔ', 'meaning': 'английский язык'},
    '影片': {'pinyin': 'yǐngpiàn', 'meaning': 'фильм, кино'},
    '影响': {'pinyin': 'yǐngxiǎng', 'meaning': 'влиять; влияние'},
    '永远': {'pinyin': 'yǒngyuǎn', 'meaning': 'вечно; всегда; навечно'},
    '油': {'pinyin': 'yóu', 'meaning': 'масло, жир; нефть; красить'},
    '游客': {'pinyin': 'yóukè', 'meaning': 'турист, экскурсант'},
    '友好': {'pinyin': 'yǒuhǎo', 'meaning': 'дружба; дружественный'},
    '有空儿': {'pinyin': 'yǒukòngr', 'meaning': 'иметь свободное время'},
    '有人': {'pinyin': 'yǒurén', 'meaning': 'кто-то; кто-то есть (занято)'},
    '有': {'pinyin': 'yǒudiǎnr', 'meaning': 'немного, чуть-чуть'},
    '有意思': {'pinyin': 'yǒuyìsi', 'meaning': 'интересный; питать интерес'},
    '又': {'pinyin': 'yòu', 'meaning': 'снова, опять; к тому же'},
    '鱼': {'pinyin': 'yú', 'meaning': 'рыба'},
    '语言': {'pinyin': 'yǔyán', 'meaning': 'речь; язык'},
    '原来': {'pinyin': 'yuánlái', 'meaning': 'первоначально; оказывается'},
    '原因': {'pinyin': 'yuányīn', 'meaning': 'причина, повод'},
    '院': {'pinyin': 'yuàn', 'meaning': 'двор; название государственных учреждений; институт'},
    '院长': {'pinyin': 'yuànzhǎng', 'meaning': 'директор; президент; глава'},
    '院子': {'pinyin': 'yuànzi', 'meaning': 'двор, усадьба'},
    '愿意': {'pinyin': 'yuànyì', 'meaning': 'желать, хотеть'},
    '月份': {'pinyin': 'yuèfèn', 'meaning': 'месяц'},
    '月亮': {'pinyin': 'yuèliang', 'meaning': 'луна'},
    '越': {'pinyin': 'yuè', 'meaning': 'перейти через; всё более'},
    '越来越': {'pinyin': 'yuèláiyuè', 'meaning': 'всё больше и больше'},
    '云': {'pinyin': 'yún', 'meaning': 'облако'},
    '运动': {'pinyin': 'yùndòng', 'meaning': 'спорт, движение; кампания'},
    '咱': {'pinyin': 'zán', 'meaning': 'мы (включая говорящего)'},
    '咱们': {'pinyin': 'zánmen', 'meaning': 'мы с вами (с тобой)'},
    '脏': {'pinyin': 'zāng', 'meaning': 'грязный'},
    '早餐': {'pinyin': 'zǎocān', 'meaning': 'завтрак'},
    '早晨': {'pinyin': 'zǎochén', 'meaning': 'утро'},
    '早就': {'pinyin': 'zǎojiù', 'meaning': 'уже давно; ещё раньше'},
    '怎么办': {'pinyin': 'zěnmebàn', 'meaning': 'что делать, как делать'},
    '怎么样': {'pinyin': 'zěnmeyàng', 'meaning': 'как дела?; каким образом?'},
    '怎样': {'pinyin': 'zěnyàng', 'meaning': 'как, каким образом'},
    '占': {'pinyin': 'zhàn', 'meaning': 'занимать (место, время); составлять'},
    '站': {'pinyin': 'zhàn', 'meaning': 'стоять; вставать; останавливаться'},
    '站住': {'pinyin': 'zhànzhù', 'meaning': 'остановиться; стой!'},
    '长大': {'pinyin': 'zhǎngdà', 'meaning': 'вырастать; становиться взрослым'},
    '找出': {'pinyin': 'zhǎochū', 'meaning': 'находить, обнаруживать'},
    '照顾': {'pinyin': 'zhàogù', 'meaning': 'присматривать; заботиться'},
    '照片': {'pinyin': 'zhàopiàn', 'meaning': 'фотография'},
    '照相': {'pinyin': 'zhàoxiàng', 'meaning': 'фотографировать'},
    '这么': {'pinyin': 'zhème', 'meaning': 'так; такой; настолько'},
    '这时候': {'pinyin': 'zhè shíhou', 'meaning': 'в это время, в этот момент'},
    '这样': {'pinyin': 'zhèyàng', 'meaning': 'такой; так; таким образом'},
    '真正': {'pinyin': 'zhēnzhèng', 'meaning': 'подлинный; настоящий'},
    '正常': {'pinyin': 'zhèngcháng', 'meaning': 'нормальный; средний'},
    '正好': {'pinyin': 'zhènghǎo', 'meaning': 'как раз; кстати'},
    '正确': {'pinyin': 'zhèngquè', 'meaning': 'правильный; точный'},
    '正是': {'pinyin': 'zhèngshì', 'meaning': 'быть точно, быть именно'},
    '直接': {'pinyin': 'zhíjiē', 'meaning': 'прямой; непосредственный'},
    '只': {'pinyin': 'zhǐ', 'meaning': 'только; лишь; всего лишь'},
    '只能': {'pinyin': 'zhǐnéng', 'meaning': 'мочь только'},
    '只要': {'pinyin': 'zhǐyào', 'meaning': 'нужно лишь; надо только'},
    '纸': {'pinyin': 'zhǐ', 'meaning': 'бумага'},
    '中餐': {'pinyin': 'zhōngcān', 'meaning': 'китайская кухня'},
    '中级': {'pinyin': 'zhōngjí', 'meaning': 'средний уровень'},
    '中年': {'pinyin': 'zhōngnián', 'meaning': 'средних лет; средний возраст'},
    '中小学': {'pinyin': 'zhōngxiǎoxué', 'meaning': 'начальная и средняя школа'},
    '中心': {'pinyin': 'zhōngxīn', 'meaning': 'центр; сердцевина; центральный'},
    '中医': {'pinyin': 'zhōngyī', 'meaning': 'традиционная китайская медицина'},
    '重点': {'pinyin': 'zhòngdiǎn', 'meaning': 'ключевой пункт; главное звено'},
    '重视': {'pinyin': 'zhòngshì', 'meaning': 'придавать значение; обращать внимание'},
    '周': {'pinyin': 'zhōu', 'meaning': 'неделя; цикл, круг'},
    '周末': {'pinyin': 'zhōumò', 'meaning': 'выходные; конец недели'},
    '周年': {'pinyin': 'zhōunián', 'meaning': 'годовщина; годичный'},
    '主人': {'pinyin': 'zhǔrén', 'meaning': 'хозяин; владелец'},
    '主要': {'pinyin': 'zhǔyào', 'meaning': 'главный, главным образом'},
    '住房': {'pinyin': 'zhùfáng', 'meaning': 'жильё'},
    '住院': {'pinyin': 'zhùyuàn', 'meaning': 'лечь в больницу'},
    '装': {'pinyin': 'zhuāng', 'meaning': 'наряд; одежда; притворяться; упаковывать'},
    '准确': {'pinyin': 'zhǔnquè', 'meaning': 'точный; правильный; меткий'},
    '自己': {'pinyin': 'zìjǐ', 'meaning': 'сам'},
    '自行车': {'pinyin': 'zìxíngchē', 'meaning': 'велосипед'},
    '自由': {'pinyin': 'zìyóu', 'meaning': 'свобода; свободный'},
    '字典': {'pinyin': 'zìdiǎn', 'meaning': 'словарь'},
    '走过': {'pinyin': 'zǒuguò', 'meaning': 'миновать; проходить мимо'},
    '走进': {'pinyin': 'zǒujìn', 'meaning': 'заходить, входить'},
    '走开': {'pinyin': 'zǒukāi', 'meaning': 'уходить; убираться'},
    '租': {'pinyin': 'zū', 'meaning': 'арендовать; снимать; сдавать в аренду'},
    '组': {'pinyin': 'zǔ', 'meaning': 'группа; кружок; организовать'},
    '组成': {'pinyin': 'zǔchéng', 'meaning': 'образовать; составить'},
    '组长': {'pinyin': 'zǔzhǎng', 'meaning': 'лидер группы'},
    '嘴': {'pinyin': 'zuǐ', 'meaning': 'рот'},
    '最近': {'pinyin': 'zuìjìn', 'meaning': 'ближайший; недавно'},
    '作家': {'pinyin': 'zuòjiā', 'meaning': 'писатель; творческий работник'},
    '作文': {'pinyin': 'zuòwén', 'meaning': 'писать сочинение; сочинение'},
    '作业': {'pinyin': 'zuòyè', 'meaning': 'домашнее задание; работа'},
    '作用': {'pinyin': 'zuòyòng', 'meaning': 'роль; значение; действие'},
    '座': {'pinyin': 'zuò', 'meaning': 'место; постамент; сч. слово для зданий'},
    '座位': {'pinyin': 'zuòwèi', 'meaning': 'место (для сидения)'},
    '做到': {'pinyin': 'zuòdào', 'meaning': 'выполнять, достигать'},
    '做法': {'pinyin': 'zuòfǎ', 'meaning': 'метод, способ действия; поступок'},
    '做饭': {'pinyin': 'zuòfàn', 'meaning': 'готовить еду'},
}
