HSK3_CHARACTERS = {
    '阿姨': {'pinyin': 'ayi', 'meaning': 'тетя; няня'},
    '安静': {'pinyin': 'anjing', 'meaning': 'тихий; спокойный'},
    '安排': {'pinyin': 'anpai', 'meaning': 'организовать; планировать'},
    '按时': {'pinyin': 'anshi', 'meaning': 'вовремя'},
    '按照': {'pinyin': 'anzhao', 'meaning': 'в соответствии с'},
    '棒': {'pinyin': 'bang', 'meaning': 'отличный; палка'},
    '包子': {'pinyin': 'baozi', 'meaning': 'паровая булочка'},
    '抱': {'pinyin': 'bao', 'meaning': 'обнимать; держать в руках'},
    '报名': {'pinyin': 'baoming', 'meaning': 'зарегистрироваться'},
    '保护': {'pinyin': 'baohu', 'meaning': 'защищать'},
    '抱歉': {'pinyin': 'baoqian', 'meaning': 'извиняться'},
    '保证': {'pinyin': 'baozheng', 'meaning': 'гарантировать'},
    '倍': {'pinyin': 'bei', 'meaning': 'кратный; раз'},
    '笨': {'pinyin': 'ben', 'meaning': 'глупый'},
    '比如': {'pinyin': 'biru', 'meaning': 'например'},
    '毕业': {'pinyin': 'biye', 'meaning': 'закончить учебу'},
    '饼干': {'pinyin': 'binggan', 'meaning': 'печенье'},
    '并且': {'pinyin': 'bingqie', 'meaning': 'и; к тому же'},
    '博士': {'pinyin': 'boshi', 'meaning': 'доктор (ученая степень)'},
    '不过': {'pinyin': 'buguo', 'meaning': 'однако; но'},
    '不得不': {'pinyin': 'budebu', 'meaning': 'приходится'},
    '部分': {'pinyin': 'bufen', 'meaning': 'часть; раздел'},
    '擦': {'pinyin': 'ca', 'meaning': 'тереть; вытирать'},
    '猜': {'pinyin': 'cai', 'meaning': 'угадывать'},
    '材料': {'pinyin': 'cailiao', 'meaning': 'материал'},
    '餐厅': {'pinyin': 'canting', 'meaning': 'столовая; ресторан'},
    '厕所': {'pinyin': 'cesuo', 'meaning': 'туалет'},
    '层': {'pinyin': 'ceng', 'meaning': 'слой; этаж'},
    '曾经': {'pinyin': 'cengjing', 'meaning': 'когда-то'},
    '尝': {'pinyin': 'chang', 'meaning': 'пробовать (на вкус)'},
    '场': {'pinyin': 'chang', 'meaning': 'площадка; место'},
    '长城': {'pinyin': 'Changcheng', 'meaning': 'Великая Китайская стена'},
    '长江': {'pinyin': 'Changjiang', 'meaning': 'река Янцзы'},
    '超市': {'pinyin': 'chaoshi', 'meaning': 'супермаркет'},
    '衬衫': {'pinyin': 'chenshan', 'meaning': 'рубашка'},
    '成绩': {'pinyin': 'chengji', 'meaning': 'результат; оценка'},
    '成为': {'pinyin': 'chengwei', 'meaning': 'становиться'},
    '诚实': {'pinyin': 'chengshi', 'meaning': 'честный'},
    '吃惊': {'pinyin': 'chijing', 'meaning': 'удивляться'},
    '重新': {'pinyin': 'chongxin', 'meaning': 'заново'},
    '抽烟': {'pinyin': 'chouyan', 'meaning': 'курить'},
    '出': {'pinyin': 'chu', 'meaning': 'выходить'},
    '出错': {'pinyin': 'chucuo', 'meaning': 'совершить ошибку'},
    '出现': {'pinyin': 'chuxian', 'meaning': 'появляться'},
    '出发': {'pinyin': 'chufa', 'meaning': 'отправляться'},
    '传真': {'pinyin': 'chuanzhen', 'meaning': 'факс'},
    '除了': {'pinyin': 'chule', 'meaning': 'кроме'},
    '船': {'pinyin': 'chuan', 'meaning': 'корабль'},
    '穿': {'pinyin': 'chuan', 'meaning': 'носить (одежду)'},
    '窗户': {'pinyin': 'chuanghu', 'meaning': 'окно'},
    '创造': {'pinyin': 'chuangzao', 'meaning': 'создавать'},
    '次': {'pinyin': 'ci', 'meaning': 'раз; мера для действий'},
    '从': {'pinyin': 'cong', 'meaning': 'из; с'},
    '从来': {'pinyin': 'conglai', 'meaning': 'никогда'},
    '粗心': {'pinyin': 'cuxin', 'meaning': 'невнимательный'},
    '错': {'pinyin': 'cuo', 'meaning': 'ошибка'},
    '答案': {'pinyin': 'daan', 'meaning': 'ответ'},
    '打扮': {'pinyin': 'daban', 'meaning': 'наряжаться'},
    '打扰': {'pinyin': 'darao', 'meaning': 'беспокоить'},
    '打印': {'pinyin': 'dayin', 'meaning': 'печатать'},
    '打折': {'pinyin': 'dazhe', 'meaning': 'предоставлять скидку'},
    '大概': {'pinyin': 'dagai', 'meaning': 'примерно'},
    '带': {'pinyin': 'dai', 'meaning': 'приносить; брать с собой'},
    '代表': {'pinyin': 'daibiao', 'meaning': 'представлять'},
    '戴': {'pinyin': 'dai', 'meaning': 'носить (на голове)'},
    '大学': {'pinyin': 'daxue', 'meaning': 'университет'},
    '当': {'pinyin': 'dang', 'meaning': 'когда; в качестве'},
    '刀': {'pinyin': 'dao', 'meaning': 'нож'},
    '导游': {'pinyin': 'daoyou', 'meaning': 'гид'},
    '到处': {'pinyin': 'daochu', 'meaning': 'везде'},
    '到底': {'pinyin': 'daodi', 'meaning': 'в конце концов'},
    '地球': {'pinyin': 'diqiu', 'meaning': 'Земля'},
    '地图': {'pinyin': 'ditu', 'meaning': 'карта'},
    '低': {'pinyin': 'di', 'meaning': 'низкий'},
    '弟弟': {'pinyin': 'didi', 'meaning': 'младший брат'},
    '地方': {'pinyin': 'difang', 'meaning': 'место'},
    '丢': {'pinyin': 'diu', 'meaning': 'терять'},
    '东': {'pinyin': 'dong', 'meaning': 'восток'},
    '动作': {'pinyin': 'dongzuo', 'meaning': 'действие; движение'},
    '堵车': {'pinyin': 'duche', 'meaning': 'пробка (дорожная)'},
    '肚子': {'pinyin': 'duzi', 'meaning': 'живот'},
    '短信': {'pinyin': 'duanxin', 'meaning': 'СМС'},
    '对话': {'pinyin': 'duihua', 'meaning': 'диалог'},
    '对': {'pinyin': 'dui', 'meaning': 'правильный; к'},
    '对象': {'pinyin': 'duixiang', 'meaning': 'объект; партнер'},
    '对于': {'pinyin': 'duiyu', 'meaning': 'относительно'},
    '儿童': {'pinyin': 'ertong', 'meaning': 'дети'},
    '而': {'pinyin': 'er', 'meaning': 'и; а'},
    '而且': {'pinyin': 'erqie', 'meaning': 'к тому же'},
    '法律': {'pinyin': 'falv', 'meaning': 'закон'},
    '翻译': {'pinyin': 'fanyi', 'meaning': 'переводить'},
    '烦恼': {'pinyin': 'fannao', 'meaning': 'беспокоиться'},
    '反对': {'pinyin': 'fandui', 'meaning': 'возражать'},
    '方法': {'pinyin': 'fangfa', 'meaning': 'метод'},
    '方面': {'pinyin': 'fangmian', 'meaning': 'аспект'},
    '方向': {'pinyin': 'fangxiang', 'meaning': 'направление'},
    '房东': {'pinyin': 'fangdong', 'meaning': 'арендодатель'},
    '房间': {'pinyin': 'fangjian', 'meaning': 'комната'},
    '放弃': {'pinyin': 'fangqi', 'meaning': 'отказываться'},
    '放假': {'pinyin': 'fangjia', 'meaning': 'брать отпуск'},
    '访问': {'pinyin': 'fangwen', 'meaning': 'посещать'},
    '方便': {'pinyin': 'fangbian', 'meaning': 'удобный'},
    '风': {'pinyin': 'feng', 'meaning': 'ветер'},
    '风景': {'pinyin': 'fengjing', 'meaning': 'пейзаж'},
    '风险': {'pinyin': 'fengxian', 'meaning': 'риск'},
    '疯狂': {'pinyin': 'fengkuang', 'meaning': 'сумасшедший'},
    '分': {'pinyin': 'fen', 'meaning': 'разделять'},
    '份': {'pinyin': 'fen', 'meaning': 'порция; экземпляр'},
    '丰富': {'pinyin': 'fengfu', 'meaning': 'богатый; разнообразный'},
    '否则': {'pinyin': 'fouze', 'meaning': 'иначе'},
    '付款': {'pinyin': 'fukuan', 'meaning': 'оплачивать'},
    '复印': {'pinyin': 'fuyin', 'meaning': 'ксерокопировать'},
    '复杂': {'pinyin': 'fuza', 'meaning': 'сложный'},
    '父母': {'pinyin': 'fumu', 'meaning': 'родители'},
    '改变': {'pinyin': 'gaibian', 'meaning': 'изменять'},
    '改进': {'pinyin': 'gaijin', 'meaning': 'улучшать'},
    '干杯': {'pinyin': 'ganbei', 'meaning': 'за ваше здоровье'},
    '感动': {'pinyin': 'gandong', 'meaning': 'быть тронутым'},
    '感谢': {'pinyin': 'ganxie', 'meaning': 'благодарить'},
    '敢': {'pinyin': 'gan', 'meaning': 'сметь'},
    '赶': {'pinyin': 'gan', 'meaning': 'спешить'},
    '刚': {'pinyin': 'gang', 'meaning': 'только что'},
    '刚才': {'pinyin': 'gangcai', 'meaning': 'только что'},
    '高速公路': {'pinyin': 'gaosu gonglu', 'meaning': 'автострада'},
    '胳膊': {'pinyin': 'gebo', 'meaning': 'рука'},
    '各种': {'pinyin': 'gezhong', 'meaning': 'различный'},
    '根据': {'pinyin': 'genju', 'meaning': 'на основании'},
    '跟': {'pinyin': 'gen', 'meaning': 'с; за'},
    '更加': {'pinyin': 'gengjia', 'meaning': 'еще более'},
    '工资': {'pinyin': 'gongzi', 'meaning': 'зарплата'},
    '工具': {'pinyin': 'gongju', 'meaning': 'инструмент'},
    '工厂': {'pinyin': 'gongchang', 'meaning': 'фабрика'},
    '公园': {'pinyin': 'gongyuan', 'meaning': 'парк'},
    '恭喜': {'pinyin': 'gongxi', 'meaning': 'поздравлять'},
    '购物': {'pinyin': 'gouwu', 'meaning': 'делать покупки'},
    '够': {'pinyin': 'gou', 'meaning': 'достаточно'},
    '估计': {'pinyin': 'guji', 'meaning': 'оценивать'},
    '鼓励': {'pinyin': 'guli', 'meaning': 'поощрять'},
    '故意': {'pinyin': 'guyi', 'meaning': 'намеренно'},
    '顾客': {'pinyin': 'guke', 'meaning': 'клиент'},
    '故事': {'pinyin': 'gushi', 'meaning': 'история'},
    '故意': {'pinyin': 'gushi', 'meaning': 'намеренно'},
    '过程': {'pinyin': 'guocheng', 'meaning': 'процесс'},
    '过去': {'pinyin': 'guoqu', 'meaning': 'прошлое'},
    '果汁': {'pinyin': 'guozhi', 'meaning': 'сок'},
    '害怕': {'pinyin': 'haipa', 'meaning': 'бояться'},
    '害羞': {'pinyin': 'haixiu', 'meaning': 'стесняться'},
    '海洋': {'pinyin': 'haiyang', 'meaning': 'океан'},
    '汗': {'pinyin': 'han', 'meaning': 'пот'},
    '好': {'pinyin': 'hao', 'meaning': 'хороший'},
    '好奇': {'pinyin': 'haoqi', 'meaning': 'любопытный'},
    '合适': {'pinyin': 'heshi', 'meaning': 'подходящий'},
    '盒子': {'pinyin': 'hezi', 'meaning': 'коробка'},
    '河': {'pinyin': 'he', 'meaning': 'река'},
    '合格': {'pinyin': 'hege', 'meaning': 'квалифицированный'},
    '合同': {'pinyin': 'hetong', 'meaning': 'контракт'},
    '和平': {'pinyin': 'heping', 'meaning': 'мир'},
    '核心': {'pinyin': 'hexin', 'meaning': 'ядро; суть'},
    '后悔': {'pinyin': 'houhui', 'meaning': 'сожалеть'},
    '忽然': {'pinyin': 'huran', 'meaning': 'вдруг'},
    '互相': {'pinyin': 'huxiang', 'meaning': 'взаимно'},
    '护士': {'pinyin': 'hushi', 'meaning': 'медсестра'},
    '护照': {'pinyin': 'huzhao', 'meaning': 'паспорт'},
    '花': {'pinyin': 'hua', 'meaning': 'цветок'},
    '坏': {'pinyin': 'huai', 'meaning': 'плохой'},
    '怀念': {'pinyin': 'huainian', 'meaning': 'скучать'},
    '还': {'pinyin': 'huan', 'meaning': 'возвращать'},
    '换': {'pinyin': 'huan', 'meaning': 'менять'},
    '幻想': {'pinyin': 'huanxiang', 'meaning': 'фантазировать'},
    '黄': {'pinyin': 'huang', 'meaning': 'желтый'},
    '谎话': {'pinyin': 'huanghua', 'meaning': 'ложь'},
    '活动': {'pinyin': 'huodong', 'meaning': 'мероприятие'},
    '活泼': {'pinyin': 'huopo', 'meaning': 'живой; энергичный'},
    '或者': {'pinyin': 'huozhe', 'meaning': 'или'},
    '火': {'pinyin': 'huo', 'meaning': 'огонь'},
    '获得': {'pinyin': 'huode', 'meaning': 'получать'},
    '货': {'pinyin': 'huo', 'meaning': 'товар'},
    '极': {'pinyin': 'ji', 'meaning': 'чрезвычайно'},
    '基本': {'pinyin': 'jiben', 'meaning': 'основной'},
    '基础': {'pinyin': 'jichu', 'meaning': 'основа'},
    '激动': {'pinyin': 'jidong', 'meaning': 'волноваться'},
    '记得': {'pinyin': 'jide', 'meaning': 'помнить'},
    '技术': {'pinyin': 'jishu', 'meaning': 'технология'},
    '继续': {'pinyin': 'jixu', 'meaning': 'продолжать'},
    '计划': {'pinyin': 'jihua', 'meaning': 'планировать'},
    '寄': {'pinyin': 'ji', 'meaning': 'отправлять (почту)'},
    '加班': {'pinyin': 'jiaban', 'meaning': 'работать сверхурочно'},
    '加油': {'pinyin': 'jiayou', 'meaning': 'заправляться; стараться'},
    '价格': {'pinyin': 'jiage', 'meaning': 'цена'},
    '架': {'pinyin': 'jia', 'meaning': 'стойка; мера для самолетов'},
    '假': {'pinyin': 'jia', 'meaning': 'фальшивый'},
    '假期': {'pinyin': 'jiaqi', 'meaning': 'каникулы'},
    '坚持': {'pinyin': 'jianchi', 'meaning': 'упорствовать'},
    '减肥': {'pinyin': 'jianfei', 'meaning': 'худеть'},
    '减少': {'pinyin': 'jianshao', 'meaning': 'уменьшать'},
    '建议': {'pinyin': 'jianyi', 'meaning': 'предлагать'},
    '将来': {'pinyin': 'jianglai', 'meaning': 'будущее'},
    '讲': {'pinyin': 'jiang', 'meaning': 'говорить; объяснять'},
    '酱油': {'pinyin': 'jiangyou', 'meaning': 'соевый соус'},
    '降落': {'pinyin': 'jiangluo', 'meaning': 'приземляться'},
    '交': {'pinyin': 'jiao', 'meaning': 'передавать'},
    '交流': {'pinyin': 'jiaoliu', 'meaning': 'общаться'},
    '交通': {'pinyin': 'jiaotong', 'meaning': 'транспорт'},
    '骄傲': {'pinyin': 'jiaoao', 'meaning': 'гордиться'},
    '饺子': {'pinyin': 'jiaozi', 'meaning': 'пельмени'},
    '教育': {'pinyin': 'jiaoyu', 'meaning': 'образование'},
    '接受': {'pinyin': 'jieshou', 'meaning': 'принимать'},
    '节约': {'pinyin': 'jieyue', 'meaning': 'экономить'},
    '结果': {'pinyin': 'jieguo', 'meaning': 'результат'},
    '解释': {'pinyin': 'jieshi', 'meaning': 'объяснять'},
    '借': {'pinyin': 'jie', 'meaning': 'брать в долг'},
    '结婚': {'pinyin': 'jiehun', 'meaning': 'жениться; выходить замуж'},
    '节': {'pinyin': 'jie', 'meaning': 'праздник'},
    '节日': {'pinyin': 'jieri', 'meaning': 'праздник'},
    '尽管': {'pinyin': 'jinguan', 'meaning': 'хотя; несмотря на'},
    '紧张': {'pinyin': 'jinzhang', 'meaning': 'нервничать'},
    '进行': {'pinyin': 'jinxing', 'meaning': 'проводить'},
    '禁止': {'pinyin': 'jinzhi', 'meaning': 'запрещать'},
    '竟然': {'pinyin': 'jingran', 'meaning': 'неожиданно'},
    '经济': {'pinyin': 'jingji', 'meaning': 'экономика'},
    '警察': {'pinyin': 'jingcha', 'meaning': 'полиция'},
    '竞争': {'pinyin': 'jingzheng', 'meaning': 'конкурировать'},
    '静': {'pinyin': 'jing', 'meaning': 'спокойный'},
    '镜子': {'pinyin': 'jingzi', 'meaning': 'зеркало'},
    '究竟': {'pinyin': 'jiujing', 'meaning': 'в конце концов'},
    '酒': {'pinyin': 'jiu', 'meaning': 'алкоголь'},
    '救': {'pinyin': 'jiu', 'meaning': 'спасать'},
    '旧': {'pinyin': 'jiu', 'meaning': 'старый'},
    '就': {'pinyin': 'jiu', 'meaning': 'именно; сразу'},
    '举手': {'pinyin': 'jushou', 'meaning': 'поднимать руку'},
    '举行': {'pinyin': 'juxing', 'meaning': 'проводить (мероприятие)'},
    '拒绝': {'pinyin': 'jujue', 'meaning': 'отказываться'},
    '距离': {'pinyin': 'juli', 'meaning': 'расстояние'},
    '开玩笑': {'pinyin': 'kaiwanxiao', 'meaning': 'шутить'},
    '看': {'pinyin': 'kan', 'meaning': 'смотреть'},
    '看法': {'pinyin': 'kanfa', 'meaning': 'мнение'},
    '棵': {'pinyin': 'ke', 'meaning': 'мера для деревьев'},
    '咳嗽': {'pinyin': 'kesou', 'meaning': 'кашлять'},
    '可爱': {'pinyin': 'keai', 'meaning': 'милый'},
    '渴': {'pinyin': 'ke', 'meaning': 'жаждать'},
    '刻': {'pinyin': 'ke', 'meaning': 'момент'},
    '客人': {'pinyin': 'keren', 'meaning': 'гость'},
    '空气': {'pinyin': 'kongqi', 'meaning': 'воздух'},
    '恐怕': {'pinyin': 'kongpa', 'meaning': 'боюсь, что'},
    '控制': {'pinyin': 'kongzhi', 'meaning': 'контролировать'},
    '哭': {'pinyin': 'ku', 'meaning': 'плакать'},
    '夸': {'pinyin': 'kua', 'meaning': 'хвалить'},
    '跨': {'pinyin': 'kua', 'meaning': 'перешагивать'},
    '块': {'pinyin': 'kuai', 'meaning': 'кусок; мера'},
    '筷子': {'pinyin': 'kuaizi', 'meaning': 'палочки для еды'},
    '宽': {'pinyin': 'kuan', 'meaning': 'широкий'},
    '困': {'pinyin': 'kun', 'meaning': 'сонный'},
    '困难': {'pinyin': 'kunnan', 'meaning': 'трудный'},
    '拉': {'pinyin': 'la', 'meaning': 'тянуть'},
    '垃圾': {'pinyin': 'laji', 'meaning': 'мусор'},
    '辣': {'pinyin': 'la', 'meaning': 'острый'},
    '来不及': {'pinyin': 'laibuji', 'meaning': 'не успеть'},
    '来得及': {'pinyin': 'laideji', 'meaning': 'успеть'},
    '懒': {'pinyin': 'lan', 'meaning': 'ленивый'},
    '浪费': {'pinyin': 'langfei', 'meaning': 'тратить впустую'},
    '浪漫': {'pinyin': 'langman', 'meaning': 'романтичный'},
    '狼': {'pinyin': 'lang', 'meaning': 'волк'},
    '老': {'pinyin': 'lao', 'meaning': 'старый'},
    '劳驾': {'pinyin': 'laojia', 'meaning': 'извините (вежливо)'},
    '老板': {'pinyin': 'laoban', 'meaning': 'босс'},
    '姥姥': {'pinyin': 'laolao', 'meaning': 'бабушка (по матери)'},
    '冷': {'pinyin': 'leng', 'meaning': 'холодный'},
    '梨': {'pinyin': 'li', 'meaning': 'груша'},
    '礼貌': {'pinyin': 'limao', 'meaning': 'вежливость'},
    '理发': {'pinyin': 'lifa', 'meaning': 'стричься'},
    '理解': {'pinyin': 'lijie', 'meaning': 'понимать'},
    '理想': {'pinyin': 'lixiang', 'meaning': 'идеал'},
    '离开': {'pinyin': 'likai', 'meaning': 'покидать'},
    '立刻': {'pinyin': 'like', 'meaning': 'немедленно'},
    '力气': {'pinyin': 'liqi', 'meaning': 'сила'},
    '例如': {'pinyin': 'liru', 'meaning': 'например'},
    '流': {'pinyin': 'liu', 'meaning': 'течь'},
    '流行': {'pinyin': 'liuxing', 'meaning': 'популярный'},
    '留': {'pinyin': 'liu', 'meaning': 'оставлять'},
    '留学': {'pinyin': 'liuxue', 'meaning': 'учиться за границей'},
    '楼': {'pinyin': 'lou', 'meaning': 'здание; этаж'},
    '露': {'pinyin': 'lu', 'meaning': 'роса; показывать'},
    '陆地': {'pinyin': 'ludi', 'meaning': 'суша'},
    '乱': {'pinyin': 'luan', 'meaning': 'беспорядок'},
    '律师': {'pinyin': 'lvshi', 'meaning': 'адвокат'},
    '旅游': {'pinyin': 'lvyu', 'meaning': 'путешествовать'},
    '绿': {'pinyin': 'lv', 'meaning': 'зеленый'},
    '妈妈': {'pinyin': 'mama', 'meaning': 'мама'},
    '麻烦': {'pinyin': 'mafan', 'meaning': 'проблема; хлопоты'},
    '马': {'pinyin': 'ma', 'meaning': 'лошадь'},
    '马上': {'pinyin': 'mashang', 'meaning': 'немедленно'},
    '满足': {'pinyin': 'manzu', 'meaning': 'удовлетворять'},
    '慢慢': {'pinyin': 'manman', 'meaning': 'медленно'},
    '毛': {'pinyin': 'mao', 'meaning': 'волос; шерсть'},
    '帽子': {'pinyin': 'maozi', 'meaning': 'шапка'},
    '没': {'pinyin': 'mei', 'meaning': 'не'},
    '美味': {'pinyin': 'meiwei', 'meaning': 'вкусный'},
    '每次': {'pinyin': 'meici', 'meaning': 'каждый раз'},
    '妹妹': {'pinyin': 'meimei', 'meaning': 'младшая сестра'},
    '魅力': {'pinyin': 'meili', 'meaning': 'очарование'},
    '迷路': {'pinyin': 'milu', 'meaning': 'заблудиться'},
    '秘密': {'pinyin': 'mimi', 'meaning': 'секрет'},
    '棉': {'pinyin': 'mian', 'meaning': 'хлопок'},
    '免费': {'pinyin': 'mianfei', 'meaning': 'бесплатный'},
    '面条': {'pinyin': 'miantiao', 'meaning': 'лапша'},
    '描写': {'pinyin': 'miaoxie', 'meaning': 'описывать'},
    '秒': {'pinyin': 'miao', 'meaning': 'секунда'},
    '目标': {'pinyin': 'mubiao', 'meaning': 'цель'},
    '木': {'pinyin': 'mu', 'meaning': 'дерево'},
    '目前': {'pinyin': 'muqian', 'meaning': 'в настоящее время'},
    '拿': {'pinyin': 'na', 'meaning': 'брать'},
    '奶奶': {'pinyin': 'nainai', 'meaning': 'бабушка (по отцу)'},
    '耐心': {'pinyin': 'naixin', 'meaning': 'терпение'},
    '南': {'pinyin': 'nan', 'meaning': 'юг'},
    '难过': {'pinyin': 'nanguo', 'meaning': 'грустить'},
    '难看': {'pinyin': 'nankan', 'meaning': 'некрасивый'},
    '脑袋': {'pinyin': 'naodai', 'meaning': 'голова'},
    '内': {'pinyin': 'nei', 'meaning': 'внутри'},
    '内容': {'pinyin': 'neirong', 'meaning': 'содержание'},
    '能力': {'pinyin': 'nengli', 'meaning': 'способность'},
    '年龄': {'pinyin': 'nianling', 'meaning': 'возраст'},
    '年轻': {'pinyin': 'nianqing', 'meaning': 'молодой'},
    '鸟': {'pinyin': 'niao', 'meaning': 'птица'},
    '努力': {'pinyin': 'nuli', 'meaning': 'стараться'},
    '农村': {'pinyin': 'nongcun', 'meaning': 'деревня'},
    '弄': {'pinyin': 'nong', 'meaning': 'возиться; делать'},
    '偶尔': {'pinyin': 'ouran', 'meaning': 'иногда'},
    '欧洲': {'pinyin': 'Ouzhou', 'meaning': 'Европа'},
    '爬': {'pinyin': 'pa', 'meaning': 'ползать'},
    '怕': {'pinyin': 'pa', 'meaning': 'бояться'},
    '拍': {'pinyin': 'pai', 'meaning': 'снимать; хлопать'},
    '排队': {'pinyin': 'paidui', 'meaning': 'стоять в очереди'},
    '派': {'pinyin': 'pai', 'meaning': 'отправлять'},
    '盘子': {'pinyin': 'panzi', 'meaning': 'тарелка'},
    '判断': {'pinyin': 'panduan', 'meaning': 'судить'},
    '陪': {'pinyin': 'pei', 'meaning': 'сопровождать'},
    '批评': {'pinyin': 'piping', 'meaning': 'критиковать'},
    '皮鞋': {'pinyin': 'pixie', 'meaning': 'кожаная обувь'},
    '脾气': {'pinyin': 'piqi', 'meaning': 'характер'},
    '啤酒': {'pinyin': 'pijiu', 'meaning': 'пиво'},
    '篇': {'pinyin': 'pian', 'meaning': 'мера для статей'},
    '骗': {'pinyin': 'pian', 'meaning': 'обманывать'},
    '漂': {'pinyin': 'piao', 'meaning': 'плыть'},
    '票': {'pinyin': 'piao', 'meaning': 'билет'},
    '瓶子': {'pinyin': 'pingzi', 'meaning': 'бутылка'},
    '平时': {'pinyin': 'pingshi', 'meaning': 'обычно'},
    '破': {'pinyin': 'po', 'meaning': 'ломать'},
    '普遍': {'pinyin': 'pubian', 'meaning': 'распространенный'},
    '普通': {'pinyin': 'putong', 'meaning': 'обычный'},
    '奇怪': {'pinyin': 'qiguai', 'meaning': 'странный'},
    '其实': {'pinyin': 'qishi', 'meaning': 'на самом деле'},
    '气候': {'pinyin': 'qihou', 'meaning': 'климат'},
    '汽水': {'pinyin': 'qishui', 'meaning': 'газированная вода'},
    '千克': {'pinyin': 'qianke', 'meaning': 'килограмм'},
    '签证': {'pinyin': 'qianzheng', 'meaning': 'виза'},
    '桥': {'pinyin': 'qiao', 'meaning': 'мост'},
    '悄悄': {'pinyin': 'qiaoqiao', 'meaning': 'тихо'},
    '敲': {'pinyin': 'qiao', 'meaning': 'стучать'},
    '巧克力': {'pinyin': 'qiaokeli', 'meaning': 'шоколад'},
    '亲爱': {'pinyin': 'qinai', 'meaning': 'дорогой'},
    '亲戚': {'pinyin': 'qinqi', 'meaning': 'родственник'},
    '轻': {'pinyin': 'qing', 'meaning': 'легкий'},
    '情况': {'pinyin': 'qingkuang', 'meaning': 'ситуация'},
    '晴': {'pinyin': 'qing', 'meaning': 'ясный (о погоде)'},
    '请假': {'pinyin': 'qingjia', 'meaning': 'брать отпуск'},
    '请求': {'pinyin': 'qingqiu', 'meaning': 'просить'},
    '青春': {'pinyin': 'qingchun', 'meaning': 'юность'},
    '清楚': {'pinyin': 'qingchu', 'meaning': 'ясный'},
    '庆祝': {'pinyin': 'qingzhu', 'meaning': 'праздновать'},
    '取': {'pinyin': 'qu', 'meaning': 'брать'},
    '取消': {'pinyin': 'quxiao', 'meaning': 'отменять'},
    '去': {'pinyin': 'qu', 'meaning': 'идти'},
    '全部': {'pinyin': 'quanbu', 'meaning': 'весь'},
    '圈': {'pinyin': 'quan', 'meaning': 'круг'},
    '缺点': {'pinyin': 'quedian', 'meaning': 'недостаток'},
    '缺少': {'pinyin': 'queshao', 'meaning': 'не хватать'},
    '却': {'pinyin': 'que', 'meaning': 'однако'},
    '确实': {'pinyin': 'queshi', 'meaning': 'действительно'},
    '热': {'pinyin': 're', 'meaning': 'горячий'},
    '热情': {'pinyin': 'reqing', 'meaning': 'энтузиазм'},
    '人': {'pinyin': 'ren', 'meaning': 'человек'},
    '任何': {'pinyin': 'renhe', 'meaning': 'любой'},
    '认识': {'pinyin': 'renshi', 'meaning': 'знать; узнавать'},
    '认真': {'pinyin': 'renzhen', 'meaning': 'серьезный'},
    '扔': {'pinyin': 'reng', 'meaning': 'бросать'},
    '仍然': {'pinyin': 'rengran', 'meaning': 'по-прежнему'},
    '日': {'pinyin': 'ri', 'meaning': 'день'},
    '日记': {'pinyin': 'riji', 'meaning': 'дневник'},
    '入口': {'pinyin': 'rukou', 'meaning': 'вход'},
    '软': {'pinyin': 'ruan', 'meaning': 'мягкий'},
    '弱': {'pinyin': 'ruo', 'meaning': 'слабый'},
    '洒': {'pinyin': 'sa', 'meaning': 'разбрызгивать'},
    '三': {'pinyin': 'san', 'meaning': 'три'},
    '伞': {'pinyin': 'san', 'meaning': 'зонт'},
    '散步': {'pinyin': 'sanbu', 'meaning': 'гулять'},
    '森林': {'pinyin': 'senlin', 'meaning': 'лес'},
    '沙': {'pinyin': 'sha', 'meaning': 'песок'},
    '沙漠': {'pinyin': 'shamo', 'meaning': 'пустыня'},
    '傻': {'pinyin': 'sha', 'meaning': 'глупый'},
    '晒': {'pinyin': 'shai', 'meaning': 'загорать'},
    '删除': {'pinyin': 'shanchu', 'meaning': 'удалять'},
    '善良': {'pinyin': 'shanliang', 'meaning': 'добрый'},
    '商店': {'pinyin': 'shangdian', 'meaning': 'магазин'},
    '伤心': {'pinyin': 'shangxin', 'meaning': 'грустить'},
    '稍微': {'pinyin': 'shaowei', 'meaning': 'немного'},
    '少': {'pinyin': 'shao', 'meaning': 'мало'},
    '社会': {'pinyin': 'shehui', 'meaning': 'общество'},
    '设计': {'pinyin': 'sheji', 'meaning': 'проектировать'},
    '设备': {'pinyin': 'shebei', 'meaning': 'оборудование'},
    '生活': {'pinyin': 'shenghuo', 'meaning': 'жизнь'},
    '申请': {'pinyin': 'shenqing', 'meaning': 'подавать заявку'},
    '甚至': {'pinyin': 'shenzhi', 'meaning': 'даже'},
    '深': {'pinyin': 'shen', 'meaning': 'глубокий'},
    '神': {'pinyin': 'shen', 'meaning': 'бог'},
    '声': {'pinyin': 'sheng', 'meaning': 'звук'},
    '剩': {'pinyin': 'sheng', 'meaning': 'оставаться'},
    '胜利': {'pinyin': 'shengli', 'meaning': 'победа'},
    '省': {'pinyin': 'sheng', 'meaning': 'провинция'},
    '升': {'pinyin': 'sheng', 'meaning': 'подниматься'},
    '绳子': {'pinyin': 'shengzi', 'meaning': 'веревка'},
    '时代': {'pinyin': 'shidai', 'meaning': 'эпоха'},
    '适合': {'pinyin': 'shihe', 'meaning': 'подходить'},
    '适应': {'pinyin': 'shiying', 'meaning': 'приспосабливаться'},
    '世纪': {'pinyin': 'shiji', 'meaning': 'век'},
    '时间': {'pinyin': 'shijian', 'meaning': 'время'},
    '实际': {'pinyin': 'shiji', 'meaning': 'реальный'},
    '实习': {'pinyin': 'shixi', 'meaning': 'стажировка'},
    '实现': {'pinyin': 'shixian', 'meaning': 'реализовывать'},
    '实验': {'pinyin': 'shiyan', 'meaning': 'эксперимент'},
    '食物': {'pinyin': 'shiwu', 'meaning': 'еда'},
    '使用': {'pinyin': 'shiyong', 'meaning': 'использовать'},
    '试': {'pinyin': 'shi', 'meaning': 'пробовать'},
    '市场': {'pinyin': 'shichang', 'meaning': 'рынок'},
    '失望': {'pinyin': 'shiwang', 'meaning': 'разочаровываться'},
    '师傅': {'pinyin': 'shifu', 'meaning': 'мастер'},
    '湿': {'pinyin': 'shi', 'meaning': 'влажный'},
    '狮子': {'pinyin': 'shizi', 'meaning': 'лев'},
    '是': {'pinyin': 'shi', 'meaning': 'быть'},
    '是否': {'pinyin': 'shifou', 'meaning': 'ли; будь то'},
    '世界': {'pinyin': 'shijie', 'meaning': 'мир'},
    '事故': {'pinyin': 'shigu', 'meaning': 'происшествие'},
    '时尚': {'pinyin': 'shishang', 'meaning': 'мода'},
    '收': {'pinyin': 'shou', 'meaning': 'получать'},
    '收拾': {'pinyin': 'shoushi', 'meaning': 'прибирать'},
    '瘦': {'pinyin': 'shou', 'meaning': 'худой'},
    '受不了': {'pinyin': 'shoubuliao', 'meaning': 'не выносить'},
    '舒服': {'pinyin': 'shufu', 'meaning': 'удобный'},
    '书': {'pinyin': 'shu', 'meaning': 'книга'},
    '熟': {'pinyin': 'shu', 'meaning': 'зрелый; знакомый'},
    '属于': {'pinyin': 'shuyu', 'meaning': 'принадлежать'},
    '数学': {'pinyin': 'shuxue', 'meaning': 'математика'},
    '数字': {'pinyin': 'shuzi', 'meaning': 'цифра'},
    '刷牙': {'pinyin': 'shuaya', 'meaning': 'чистить зубы'},
    '帅': {'pinyin': 'shuai', 'meaning': 'красивый (о мужчинах)'},
    '顺便': {'pinyin': 'shunbian', 'meaning': 'заодно'},
    '顺利': {'pinyin': 'shunli', 'meaning': 'успешно'},
    '说明': {'pinyin': 'shuoming', 'meaning': 'объяснять'},
    '硕士': {'pinyin': 'shuoshi', 'meaning': 'магистр'},
    '水平': {'pinyin': 'shuiping', 'meaning': 'уровень'},
    '睡着': {'pinyin': 'shuizhao', 'meaning': 'засыпать'},
    '司机': {'pinyin': 'siji', 'meaning': 'водитель'},
    '死': {'pinyin': 'si', 'meaning': 'умирать'},
    '速度': {'pinyin': 'sudu', 'meaning': 'скорость'},
    '塑料': {'pinyin': 'suliao', 'meaning': 'пластик'},
    '酸': {'pinyin': 'suan', 'meaning': 'кислый'},
    '算': {'pinyin': 'suan', 'meaning': 'считать'},
    '随便': {'pinyin': 'suibian', 'meaning': 'небрежный; как угодно'},
    '虽然': {'pinyin': 'suiran', 'meaning': 'хотя'},
    '随时': {'pinyin': 'suishi', 'meaning': 'в любое время'},
    '孙子': {'pinyin': 'sunzi', 'meaning': 'внук'},
    '所有': {'pinyin': 'suoyou', 'meaning': 'все'},
    '锁': {'pinyin': 'suo', 'meaning': 'замок'},
    '塔': {'pinyin': 'ta', 'meaning': 'башня'},
    '太': {'pinyin': 'tai', 'meaning': 'слишком'},
    '态度': {'pinyin': 'taidu', 'meaning': 'отношение'},
    '台': {'pinyin': 'tai', 'meaning': 'платформа; мера'},
    '抬': {'pinyin': 'tai', 'meaning': 'поднимать'},
    '谈': {'pinyin': 'tan', 'meaning': 'разговаривать'},
    '弹钢琴': {'pinyin': 'tangangqin', 'meaning': 'играть на пианино'},
    '汤': {'pinyin': 'tang', 'meaning': 'суп'},
    '糖': {'pinyin': 'tang', 'meaning': 'сахар'},
    '躺': {'pinyin': 'tang', 'meaning': 'лежать'},
    '讨论': {'pinyin': 'taolun', 'meaning': 'обсуждать'},
    '讨厌': {'pinyin': 'taoyan', 'meaning': 'ненавидеть'},
    '特点': {'pinyin': 'tedian', 'meaning': 'особенность'},
    '提': {'pinyin': 'ti', 'meaning': 'поднимать'},
    '提供': {'pinyin': 'tigong', 'meaning': 'предоставлять'},
    '提前': {'pinyin': 'tiqian', 'meaning': 'заранее'},
    '提醒': {'pinyin': 'tixing', 'meaning': 'напоминать'},
    '题': {'pinyin': 'ti', 'meaning': 'вопрос; тема'},
    '体育': {'pinyin': 'tiyu', 'meaning': 'физкультура'},
    '替': {'pinyin': 'ti', 'meaning': 'заменять'},
    '天': {'pinyin': 'tian', 'meaning': 'небо; день'},
    '甜': {'pinyin': 'tian', 'meaning': 'сладкий'},
    '条': {'pinyin': 'tiao', 'meaning': 'полоса; мера'},
    '条件': {'pinyin': 'tiaojian', 'meaning': 'условие'},
    '跳': {'pinyin': 'tiao', 'meaning': 'прыгать'},
    '调皮': {'pinyin': 'tiaopi', 'meaning': 'озорной'},
    '停': {'pinyin': 'ting', 'meaning': 'останавливаться'},
    '挺': {'pinyin': 'ting', 'meaning': 'весьма'},
    '通过': {'pinyin': 'tongguo', 'meaning': 'через; проходить'},
    '同情': {'pinyin': 'tongqing', 'meaning': 'сочувствовать'},
    '同事': {'pinyin': 'tongshi', 'meaning': 'коллега'},
    '同意': {'pinyin': 'tongyi', 'meaning': 'соглашаться'},
    '通知': {'pinyin': 'tongzhi', 'meaning': 'уведомлять'},
    '痛': {'pinyin': 'tong', 'meaning': 'боль'},
    '痛苦': {'pinyin': 'tongku', 'meaning': 'страдание'},
    '偷': {'pinyin': 'tou', 'meaning': 'украсть'},
    '投资': {'pinyin': 'touzi', 'meaning': 'инвестировать'},
    '透明': {'pinyin': 'touming', 'meaning': 'прозрачный'},
    '突然': {'pinyin': 'turan', 'meaning': 'вдруг'},
    '图书馆': {'pinyin': 'tushuguan', 'meaning': 'библиотека'},
    '推': {'pinyin': 'tui', 'meaning': 'толкать'},
    '推迟': {'pinyin': 'tuichi', 'meaning': 'откладывать'},
    '腿': {'pinyin': 'tui', 'meaning': 'нога'},
    '退': {'pinyin': 'tui', 'meaning': 'отступать'},
    '脱': {'pinyin': 'tuo', 'meaning': 'снимать (одежду)'},
    '袜子': {'pinyin': 'wazi', 'meaning': 'носки'},
    '外': {'pinyin': 'wai', 'meaning': 'внешний'},
    '玩': {'pinyin': 'wan', 'meaning': 'играть'},
    '完成': {'pinyin': 'wancheng', 'meaning': 'завершать'},
    '完美': {'pinyin': 'wanmei', 'meaning': 'совершенный'},
    '完全': {'pinyin': 'wanquan', 'meaning': 'полностью'},
    '玩具': {'pinyin': 'wanju', 'meaning': 'игрушка'},
    '万': {'pinyin': 'wan', 'meaning': 'десять тысяч'},
    '忘记': {'pinyin': 'wangji', 'meaning': 'забывать'},
    '危险': {'pinyin': 'weixian', 'meaning': 'опасный'},
    '为': {'pinyin': 'wei', 'meaning': 'для'},
    '为什么': {'pinyin': 'weishenme', 'meaning': 'почему'},
    '喂': {'pinyin': 'wei', 'meaning': 'кормить; алло'},
    '伟大': {'pinyin': 'weida', 'meaning': 'великий'},
    '味道': {'pinyin': 'weidao', 'meaning': 'вкус'},
    '温度': {'pinyin': 'wendu', 'meaning': 'температура'},
    '文件': {'pinyin': 'wenjian', 'meaning': 'файл'},
    '文具': {'pinyin': 'wenju', 'meaning': 'канцелярские товары'},
    '文章': {'pinyin': 'wenzhang', 'meaning': 'статья'},
    '污染': {'pinyin': 'wuran', 'meaning': 'загрязнение'},
    '无': {'pinyin': 'wu', 'meaning': 'без'},
    '误会': {'pinyin': 'wuhui', 'meaning': 'недоразумение'},
    '物理': {'pinyin': 'wuli', 'meaning': 'физика'},
    '西': {'pinyin': 'xi', 'meaning': 'запад'},
    '吸引': {'pinyin': 'xiyin', 'meaning': 'привлекать'},
    '西瓜': {'pinyin': 'xigua', 'meaning': 'арбуз'},
    '习惯': {'pinyin': 'xiguan', 'meaning': 'привычка'},
    '洗手间': {'pinyin': 'xishoujian', 'meaning': 'туалет'},
    '洗澡': {'pinyin': 'xizao', 'meaning': 'принимать душ'},
    '下': {'pinyin': 'xia', 'meaning': 'вниз'},
    '吓': {'pinyin': 'xia', 'meaning': 'пугать'},
    '下载': {'pinyin': 'xiazai', 'meaning': 'скачивать'},
    '夏天': {'pinyin': 'xiatian', 'meaning': 'лето'},
    '现代': {'pinyin': 'xiandai', 'meaning': 'современный'},
    '羡慕': {'pinyin': 'xianmu', 'meaning': 'завидовать'},
    '现金': {'pinyin': 'xianjin', 'meaning': 'наличные'},
    '显得': {'pinyin': 'xiande', 'meaning': 'казаться'},
    '现象': {'pinyin': 'xianxiang', 'meaning': 'явление'},
    '现在': {'pinyin': 'xianzai', 'meaning': 'сейчас'},
    '现实': {'pinyin': 'xianshi', 'meaning': 'реальность'},
    '线': {'pinyin': 'xian', 'meaning': 'линия'},
    '限制': {'pinyin': 'xianzhi', 'meaning': 'ограничивать'},
    '香': {'pinyin': 'xiang', 'meaning': 'ароматный'},
    '香蕉': {'pinyin': 'xiangjiao', 'meaning': 'банан'},
    '箱子': {'pinyin': 'xiangzi', 'meaning': 'ящик'},
    '想': {'pinyin': 'xiang', 'meaning': 'думать'},
    '向': {'pinyin': 'xiang', 'meaning': 'к; в сторону'},
    '相信': {'pinyin': 'xiangxin', 'meaning': 'верить'},
    '详细': {'pinyin': 'xiangxi', 'meaning': 'подробный'},
    '响': {'pinyin': 'xiang', 'meaning': 'звучать'},
    '享受': {'pinyin': 'xiangshou', 'meaning': 'наслаждаться'},
    '想象': {'pinyin': 'xiangxiang', 'meaning': 'воображать'},
    '消息': {'pinyin': 'xiaoxi', 'meaning': 'новости'},
    '小心': {'pinyin': 'xiaoxin', 'meaning': 'осторожный'},
    '消失': {'pinyin': 'xiaoshi', 'meaning': 'исчезать'},
    '笑话': {'pinyin': 'xiaohua', 'meaning': 'анекдот'},
    '效果': {'pinyin': 'xiaoguo', 'meaning': 'эффект'},
    '效率': {'pinyin': 'xiaolv', 'meaning': 'эффективность'},
    '校长': {'pinyin': 'xiaozhang', 'meaning': 'директор школы'},
    '孝顺': {'pinyin': 'xiaoshun', 'meaning': 'почтительный'},
    '鞋': {'pinyin': 'xie', 'meaning': 'обувь'},
    '斜': {'pinyin': 'xie', 'meaning': 'наклонный'},
    '谢谢': {'pinyin': 'xiexie', 'meaning': 'спасибо'},
    '写作': {'pinyin': 'xiezuo', 'meaning': 'писать (текст)'},
    '心理': {'pinyin': 'xinli', 'meaning': 'психология'},
    '心情': {'pinyin': 'xinqing', 'meaning': 'настроение'},
    '辛苦': {'pinyin': 'xinku', 'meaning': 'тяжелый труд'},
    '信': {'pinyin': 'xin', 'meaning': 'письмо'},
    '信息': {'pinyin': 'xinxin', 'meaning': 'информация'},
    '信心': {'pinyin': 'xinxin', 'meaning': 'уверенность'},
    '新鲜': {'pinyin': 'xinxian', 'meaning': 'свежий'},
    '行李箱': {'pinyin': 'xinglixiang', 'meaning': 'чемодан'},
    '行': {'pinyin': 'xing', 'meaning': 'идти; годиться'},
    '醒': {'pinyin': 'xing', 'meaning': 'просыпаться'},
    '幸福': {'pinyin': 'xingfu', 'meaning': 'счастье'},
    '性别': {'pinyin': 'xingbie', 'meaning': 'пол'},
    '性格': {'pinyin': 'xingge', 'meaning': 'характер'},
    '幸运': {'pinyin': 'xingyun', 'meaning': 'удачливый'},
    '兄弟': {'pinyin': 'xiongdi', 'meaning': 'братья'},
    '熊': {'pinyin': 'xiong', 'meaning': 'медведь'},
    '雄伟': {'pinyin': 'xiongwei', 'meaning': 'величественный'},
    '修': {'pinyin': 'xiu', 'meaning': 'ремонтировать'},
    '休息': {'pinyin': 'xiuxi', 'meaning': 'отдыхать'},
    '需要': {'pinyin': 'xuyao', 'meaning': 'нуждаться'},
    '选择': {'pinyin': 'xuanze', 'meaning': 'выбирать'},
    '选举': {'pinyin': 'xuanju', 'meaning': 'выборы'},
    '学期': {'pinyin': 'xueqi', 'meaning': 'семестр'},
    '学生': {'pinyin': 'xuesheng', 'meaning': 'студент'},
    '学习': {'pinyin': 'xuexi', 'meaning': 'учиться'},
    '学校': {'pinyin': 'xuexiao', 'meaning': 'школа'},
    '雪': {'pinyin': 'xue', 'meaning': 'снег'},
    '压': {'pinyin': 'ya', 'meaning': 'давить'},
    '压力': {'pinyin': 'yali', 'meaning': 'давление'},
    '牙': {'pinyin': 'ya', 'meaning': 'зуб'},
    '牙膏': {'pinyin': 'yagao', 'meaning': 'зубная паста'},
    '亚洲': {'pinyin': 'Yazhou', 'meaning': 'Азия'},
    '呀': {'pinyin': 'ya', 'meaning': 'частица удивления'},
    '研究': {'pinyin': 'yanjiu', 'meaning': 'исследовать'},
    '眼镜': {'pinyin': 'yanjing', 'meaning': 'очки'},
    '盐': {'pinyin': 'yan', 'meaning': 'соль'},
    '严重': {'pinyin': 'yanzhong', 'meaning': 'серьезный'},
    '演出': {'pinyin': 'yanchu', 'meaning': 'выступление'},
    '演员': {'pinyin': 'yanyuan', 'meaning': 'актер'},
    '眼睛': {'pinyin': 'yanjing', 'meaning': 'глаза'},
    '颜色': {'pinyin': 'yanse', 'meaning': 'цвет'},
    '羊': {'pinyin': 'yang', 'meaning': 'овца'},
    '样子': {'pinyin': 'yangzi', 'meaning': 'вид; внешность'},
    '邀请': {'pinyin': 'yaoqing', 'meaning': 'приглашать'},
    '要求': {'pinyin': 'yaoqiu', 'meaning': 'требовать'},
    '药': {'pinyin': 'yao', 'meaning': 'лекарство'},
    '钥匙': {'pinyin': 'yaoshi', 'meaning': 'ключ'},
    '要': {'pinyin': 'yao', 'meaning': 'хотеть; нужно'},
    '爷': {'pinyin': 'ye', 'meaning': 'дедушка'},
    '也许': {'pinyin': 'yexu', 'meaning': 'возможно'},
    '页': {'pinyin': 'ye', 'meaning': 'страница'},
    '夜': {'pinyin': 'ye', 'meaning': 'ночь'},
    '叶子': {'pinyin': 'yezi', 'meaning': 'лист'},
    '一': {'pinyin': 'yi', 'meaning': 'один'},
    '衣服': {'pinyin': 'yifu', 'meaning': 'одежда'},
    '移动': {'pinyin': 'yidong', 'meaning': 'двигать'},
    '一定': {'pinyin': 'yiding', 'meaning': 'обязательно'},
    '一共': {'pinyin': 'yigong', 'meaning': 'всего'},
    '一会儿': {'pinyin': 'yihuir', 'meaning': 'через минуту'},
    '一样': {'pinyin': 'yiyang', 'meaning': 'одинаковый'},
    '以前': {'pinyin': 'yiqian', 'meaning': 'раньше'},
    '一直': {'pinyin': 'yizhi', 'meaning': 'все время'},
    '意见': {'pinyin': 'yijian', 'meaning': 'мнение'},
    '艺术': {'pinyin': 'yishu', 'meaning': 'искусство'},
    '因此': {'pinyin': 'yinci', 'meaning': 'поэтому'},
    '饮料': {'pinyin': 'yinliao', 'meaning': 'напиток'},
    '因为': {'pinyin': 'yinwei', 'meaning': 'потому что'},
    '印象': {'pinyin': 'yinxiang', 'meaning': 'впечатление'},
    '引起': {'pinyin': 'yinqi', 'meaning': 'вызывать'},
    '音乐': {'pinyin': 'yinyue', 'meaning': 'музыка'},
    '银行': {'pinyin': 'yinhang', 'meaning': 'банк'},
    '应该': {'pinyin': 'yinggai', 'meaning': 'должен'},
    '赢': {'pinyin': 'ying', 'meaning': 'выигрывать'},
    '硬': {'pinyin': 'ying', 'meaning': 'твердый'},
    '影响': {'pinyin': 'yingxiang', 'meaning': 'влиять'},
    '英雄': {'pinyin': 'yingxiong', 'meaning': 'герой'},
    '永远': {'pinyin': 'yongyuan', 'meaning': 'навсегда'},
    '勇敢': {'pinyin': 'yonggan', 'meaning': 'храбрый'},
    '用': {'pinyin': 'yong', 'meaning': 'использовать'},
    '优点': {'pinyin': 'youdian', 'meaning': 'преимущество'},
    '优秀': {'pinyin': 'youxiu', 'meaning': 'выдающийся'},
    '友好': {'pinyin': 'youhao', 'meaning': 'дружелюбный'},
    '友谊': {'pinyin': 'youyi', 'meaning': 'дружба'},
    '有趣': {'pinyin': 'youqu', 'meaning': 'интересный'},
    '邮局': {'pinyin': 'youju', 'meaning': 'почта'},
    '游戏': {'pinyin': 'youxi', 'meaning': 'игра'},
    '游泳': {'pinyin': 'youyong', 'meaning': 'плавать'},
    '尤其': {'pinyin': 'youqi', 'meaning': 'особенно'},
    '有': {'pinyin': 'you', 'meaning': 'иметь'},
    '有名': {'pinyin': 'youming', 'meaning': 'известный'},
    '右边': {'pinyin': 'youbian', 'meaning': 'справа'},
    '鱼': {'pinyin': 'yu', 'meaning': 'рыба'},
    '娱乐': {'pinyin': 'yule', 'meaning': 'развлечение'},
    '愉快': {'pinyin': 'yukuai', 'meaning': 'приятный'},
    '与': {'pinyin': 'yu', 'meaning': 'с'},
    '预习': {'pinyin': 'yuxi', 'meaning': 'готовиться к уроку'},
    '语言': {'pinyin': 'yuyan', 'meaning': 'язык'},
    '约会': {'pinyin': 'yuehui', 'meaning': 'свидание'},
    '阅读': {'pinyin': 'yuedu', 'meaning': 'читать'},
    '云': {'pinyin': 'yun', 'meaning': 'облако'},
    '允许': {'pinyin': 'yunxu', 'meaning': 'разрешать'},
    '运动': {'pinyin': 'yundong', 'meaning': 'спорт'},
    '运输': {'pinyin': 'yunshu', 'meaning': 'транспортировать'},
    '再': {'pinyin': 'zai', 'meaning': 'снова'},
    '在': {'pinyin': 'zai', 'meaning': 'в'},
    '赞成': {'pinyin': 'zancheng', 'meaning': 'соглашаться'},
    '脏': {'pinyin': 'zang', 'meaning': 'грязный'},
    '早餐': {'pinyin': 'zaocan', 'meaning': 'завтрак'},
    '早': {'pinyin': 'zao', 'meaning': 'рано'},
    '造成': {'pinyin': 'zaocheng', 'meaning': 'вызывать'},
    '责任': {'pinyin': 'zeren', 'meaning': 'ответственность'},
    '增加': {'pinyin': 'zengjia', 'meaning': 'увеличивать'},
    '窄': {'pinyin': 'zhai', 'meaning': 'узкий'},
    '招聘': {'pinyin': 'zhaopin', 'meaning': 'нанимать'},
    '照': {'pinyin': 'zhao', 'meaning': 'фотографировать'},
    '照顾': {'pinyin': 'zhaogu', 'meaning': 'заботиться'},
    '照片': {'pinyin': 'zhaopian', 'meaning': 'фотография'},
    '照相机': {'pinyin': 'zhaoxiangji', 'meaning': 'фотоаппарат'},
    '这': {'pinyin': 'zhe', 'meaning': 'этот'},
    '者': {'pinyin': 'zhe', 'meaning': 'суффикс для деятеля'},
    '折': {'pinyin': 'zhe', 'meaning': 'ломать'},
    '哲学': {'pinyin': 'zhexue', 'meaning': 'философия'},
    '真': {'pinyin': 'zhen', 'meaning': 'настоящий'},
    '真实': {'pinyin': 'zhenshi', 'meaning': 'реальный'},
    '整齐': {'pinyin': 'zhengqi', 'meaning': 'опрятный'},
    '正常': {'pinyin': 'zhengchang', 'meaning': 'нормальный'},
    '正好': {'pinyin': 'zhenghao', 'meaning': 'как раз'},
    '证明': {'pinyin': 'zhengming', 'meaning': 'доказывать'},
    '政府': {'pinyin': 'zhengfu', 'meaning': 'правительство'},
    '政治': {'pinyin': 'zhengzhi', 'meaning': 'политика'},
    '正在': {'pinyin': 'zhengzai', 'meaning': 'в процессе'},
    '挣': {'pinyin': 'zheng', 'meaning': 'зарабатывать'},
    '整': {'pinyin': 'zheng', 'meaning': 'целый'},
    '正确': {'pinyin': 'zhengque', 'meaning': 'правильный'},
    '之': {'pinyin': 'zhi', 'meaning': 'литературная частица'},
    '支持': {'pinyin': 'zhichi', 'meaning': 'поддерживать'},
    '知识': {'pinyin': 'zhishi', 'meaning': 'знание'},
    '值得': {'pinyin': 'zhidi', 'meaning': 'стоить'},
    '直接': {'pinyin': 'zhijie', 'meaning': 'прямой'},
    '职业': {'pinyin': 'zhiye', 'meaning': 'профессия'},
    '植物': {'pinyin': 'zhiwu', 'meaning': 'растение'},
    '只': {'pinyin': 'zhi', 'meaning': 'только'},
    '指': {'pinyin': 'zhi', 'meaning': 'указывать'},
    '制造': {'pinyin': 'zhizao', 'meaning': 'производить'},
    '至少': {'pinyin': 'zhishao', 'meaning': 'по крайней мере'},
    '质量': {'pinyin': 'zhiliang', 'meaning': 'качество'},
    '治疗': {'pinyin': 'zhiliao', 'meaning': 'лечить'},
    '中国': {'pinyin': 'Zhongguo', 'meaning': 'Китай'},
    '中间': {'pinyin': 'zhongjian', 'meaning': 'середина'},
    '终于': {'pinyin': 'zhongyu', 'meaning': 'наконец'},
    '种': {'pinyin': 'zhong', 'meaning': 'вид; тип'},
    '重点': {'pinyin': 'zhongdian', 'meaning': 'основной пункт'},
    '重要': {'pinyin': 'zhongyao', 'meaning': 'важный'},
    '周': {'pinyin': 'zhou', 'meaning': 'неделя'},
    '周末': {'pinyin': 'zhoumo', 'meaning': 'выходные'},
    '州': {'pinyin': 'zhou', 'meaning': 'штат'},
    '猪': {'pinyin': 'zhu', 'meaning': 'свинья'},
    '主': {'pinyin': 'zhu', 'meaning': 'главный'},
    '主动': {'pinyin': 'zhudong', 'meaning': 'инициативный'},
    '主意': {'pinyin': 'zhuyi', 'meaning': 'идея'},
    '注意': {'pinyin': 'zhuyi', 'meaning': 'обращать внимание'},
    '著名': {'pinyin': 'zhuming', 'meaning': 'знаменитый'},
    '祝贺': {'pinyin': 'zhuhe', 'meaning': 'поздравлять'},
    '专门': {'pinyin': 'zhuanmen', 'meaning': 'специально'},
    '专业': {'pinyin': 'zhuanye', 'meaning': 'специальность'},
    '砖': {'pinyin': 'zhuan', 'meaning': 'кирпич'},
    '赚': {'pinyin': 'zhuan', 'meaning': 'зарабатывать'},
    '转': {'pinyin': 'zhuan', 'meaning': 'поворачивать'},
    '撞': {'pinyin': 'zhuang', 'meaning': 'сталкиваться'},
    '准备': {'pinyin': 'zhunbei', 'meaning': 'готовиться'},
    '准确': {'pinyin': 'zhunque', 'meaning': 'точный'},
    '追': {'pinyin': 'zhui', 'meaning': 'преследовать'},
    '嘴': {'pinyin': 'zui', 'meaning': 'рот'},
    '最': {'pinyin': 'zui', 'meaning': 'самый'},
    '最近': {'pinyin': 'zuijin', 'meaning': 'недавно'},
    '尊敬': {'pinyin': 'zunjing', 'meaning': 'уважать'},
    '昨天': {'pinyin': 'zuotian', 'meaning': 'вчера'},
    '左边': {'pinyin': 'zuobian', 'meaning': 'слева'},
    '坐': {'pinyin': 'zuo', 'meaning': 'сидеть'},
    '做': {'pinyin': 'zuo', 'meaning': 'делать'},
    '作业': {'pinyin': 'zuoye', 'meaning': 'домашняя работа'},
}