HSK3_CHARACTERS = {
    '阿姨': {'pinyin': 'āyí', 'meaning': 'тетя; няня'},
    '安静': {'pinyin': 'ānjìng', 'meaning': 'тихий; спокойный'},
    '安排': {'pinyin': 'ānpái', 'meaning': 'организовать; планировать'},
    '按时': {'pinyin': 'ànshí', 'meaning': 'вовремя'},
    '按照': {'pinyin': 'ànzhào', 'meaning': 'в соответствии с'},
    '棒': {'pinyin': 'bàng', 'meaning': 'отличный; палка'},
    '包子': {'pinyin': 'bāozi', 'meaning': 'паровая булочка'},
    '抱': {'pinyin': 'bào', 'meaning': 'обнимать; держать в руках'},
    '报名': {'pinyin': 'bàomíng', 'meaning': 'зарегистрироваться'},
    '保护': {'pinyin': 'bǎohù', 'meaning': 'защищать'},
    '抱歉': {'pinyin': 'bàoqiàn', 'meaning': 'извиняться'},
    '保证': {'pinyin': 'bǎozhèng', 'meaning': 'гарантировать'},
    '倍': {'pinyin': 'bèi', 'meaning': 'кратный; раз'},
    '笨': {'pinyin': 'bèn', 'meaning': 'глупый'},
    '比如': {'pinyin': 'bǐrú', 'meaning': 'например'},
    '毕业': {'pinyin': 'bìyè', 'meaning': 'закончить учебу'},
    '饼干': {'pinyin': 'bǐnggān', 'meaning': 'печенье'},
    '并且': {'pinyin': 'bìngqiě', 'meaning': 'и; к тому же'},
    '博士': {'pinyin': 'bóshì', 'meaning': 'доктор (ученая степень)'},
    '不过': {'pinyin': 'bùguò', 'meaning': 'однако; но'},
    '不得不': {'pinyin': 'bùdébù', 'meaning': 'приходится'},
    '部分': {'pinyin': 'bùfèn', 'meaning': 'часть; раздел'},
    '擦': {'pinyin': 'cā', 'meaning': 'тереть; вытирать'},
    '猜': {'pinyin': 'cāi', 'meaning': 'угадывать'},
    '材料': {'pinyin': 'cáiliào', 'meaning': 'материал'},
    '餐厅': {'pinyin': 'cāntīng', 'meaning': 'столовая; ресторан'},
    '厕所': {'pinyin': 'cèsuǒ', 'meaning': 'туалет'},
    '层': {'pinyin': 'céng', 'meaning': 'слой; этаж'},
    '曾经': {'pinyin': 'céngjīng', 'meaning': 'когда-то'},
    '尝': {'pinyin': 'cháng', 'meaning': 'пробовать (на вкус)'},
    '场': {'pinyin': 'chǎng', 'meaning': 'площадка; место'},
    '长城': {'pinyin': 'Chángchéng', 'meaning': 'Великая Китайская стена'},
    '长江': {'pinyin': 'Chángjiāng', 'meaning': 'река Янцзы'},
    '超市': {'pinyin': 'chāoshì', 'meaning': 'супермаркет'},
    '衬衫': {'pinyin': 'chènshān', 'meaning': 'рубашка'},
    '成绩': {'pinyin': 'chéngjì', 'meaning': 'результат; оценка'},
    '成为': {'pinyin': 'chéngwéi', 'meaning': 'становиться'},
    '诚实': {'pinyin': 'chéngshí', 'meaning': 'честный'},
    '吃惊': {'pinyin': 'chījīng', 'meaning': 'удивляться'},
    '重新': {'pinyin': 'chóngxīn', 'meaning': 'заново'},
    '抽烟': {'pinyin': 'chōuyān', 'meaning': 'курить'},
    '出': {'pinyin': 'chū', 'meaning': 'выходить'},
    '出错': {'pinyin': 'chūcuò', 'meaning': 'совершить ошибку'},
    '出现': {'pinyin': 'chūxiàn', 'meaning': 'появляться'},
    '出发': {'pinyin': 'chūfā', 'meaning': 'отправляться'},
    '传真': {'pinyin': 'chuánzhēn', 'meaning': 'факс'},
    '除了': {'pinyin': 'chúle', 'meaning': 'кроме'},
    '船': {'pinyin': 'chuán', 'meaning': 'корабль'},
    '穿': {'pinyin': 'chuān', 'meaning': 'носить (одежду)'},
    '窗户': {'pinyin': 'chuānghù', 'meaning': 'окно'},
    '创造': {'pinyin': 'chuàngzào', 'meaning': 'создавать'},
    '次': {'pinyin': 'cì', 'meaning': 'раз; мера для действий'},
    '从': {'pinyin': 'cóng', 'meaning': 'из; с'},
    '从来': {'pinyin': 'cónglái', 'meaning': 'никогда'},
    '粗心': {'pinyin': 'cūxīn', 'meaning': 'невнимательный'},
    '错': {'pinyin': 'cuò', 'meaning': 'ошибка'},
    '答案': {'pinyin': 'dáàn', 'meaning': 'ответ'},
    '打扮': {'pinyin': 'dǎbàn', 'meaning': 'наряжаться'},
    '打扰': {'pinyin': 'dǎrǎo', 'meaning': 'беспокоить'},
    '打印': {'pinyin': 'dǎyìn', 'meaning': 'печатать'},
    '打折': {'pinyin': 'dǎzhé', 'meaning': 'предоставлять скидку'},
    '大概': {'pinyin': 'dàgài', 'meaning': 'примерно'},
    '带': {'pinyin': 'dài', 'meaning': 'приносить; брать с собой'},
    '代表': {'pinyin': 'dàibiǎo', 'meaning': 'представлять'},
    '戴': {'pinyin': 'dài', 'meaning': 'носить (на голове)'},
    '大学': {'pinyin': 'dàxué', 'meaning': 'университет'},
    '当': {'pinyin': 'dāng', 'meaning': 'когда; в качестве'},
    '刀': {'pinyin': 'dāo', 'meaning': 'нож'},
    '导游': {'pinyin': 'dǎoyóu', 'meaning': 'гид'},
    '到处': {'pinyin': 'dàochù', 'meaning': 'везде'},
    '到底': {'pinyin': 'dàodǐ', 'meaning': 'в конце концов'},
    '地球': {'pinyin': 'dìqiú', 'meaning': 'Земля'},
    '地图': {'pinyin': 'dìtú', 'meaning': 'карта'},
    '低': {'pinyin': 'dī', 'meaning': 'низкий'},
    '弟弟': {'pinyin': 'dìdi', 'meaning': 'младший брат'},
    '地方': {'pinyin': 'dìfāng', 'meaning': 'место'},
    '丢': {'pinyin': 'diū', 'meaning': 'терять'},
    '东': {'pinyin': 'dōng', 'meaning': 'восток'},
    '动作': {'pinyin': 'dòngzuò', 'meaning': 'действие; движение'},
    '堵车': {'pinyin': 'dǔchē', 'meaning': 'пробка (дорожная)'},
    '肚子': {'pinyin': 'dùzi', 'meaning': 'живот'},
    '短信': {'pinyin': 'duǎnxìn', 'meaning': 'СМС'},
    '对话': {'pinyin': 'duìhuà', 'meaning': 'диалог'},
    '对': {'pinyin': 'duì', 'meaning': 'правильный; к'},
    '对象': {'pinyin': 'duìxiàng', 'meaning': 'объект; партнер'},
    '对于': {'pinyin': 'duìyú', 'meaning': 'относительно'},
    '儿童': {'pinyin': 'értóng', 'meaning': 'дети'},
    '而': {'pinyin': 'ér', 'meaning': 'и; а'},
    '而且': {'pinyin': 'érqiě', 'meaning': 'к тому же'},
    '法律': {'pinyin': 'fǎlǜ', 'meaning': 'закон'},
    '翻译': {'pinyin': 'fānyì', 'meaning': 'переводить'},
    '烦恼': {'pinyin': 'fánnǎo', 'meaning': 'беспокоиться'},
    '反对': {'pinyin': 'fǎnduì', 'meaning': 'возражать'},
    '方法': {'pinyin': 'fāngfǎ', 'meaning': 'метод'},
    '方面': {'pinyin': 'fāngmiàn', 'meaning': 'аспект'},
    '方向': {'pinyin': 'fāngxiàng', 'meaning': 'направление'},
    '房东': {'pinyin': 'fángdōng', 'meaning': 'арендодатель'},
    '房间': {'pinyin': 'fángjiān', 'meaning': 'комната'},
    '放弃': {'pinyin': 'fàngqì', 'meaning': 'отказываться'},
    '放假': {'pinyin': 'fàngjià', 'meaning': 'брать отпуск'},
    '访问': {'pinyin': 'fǎngwèn', 'meaning': 'посещать'},
    '方便': {'pinyin': 'fāngbiàn', 'meaning': 'удобный'},
    '风': {'pinyin': 'fēng', 'meaning': 'ветер'},
    '风景': {'pinyin': 'fēngjǐng', 'meaning': 'пейзаж'},
    '风险': {'pinyin': 'fēngxiǎn', 'meaning': 'риск'},
    '疯狂': {'pinyin': 'fēngkuáng', 'meaning': 'сумасшедший'},
    '分': {'pinyin': 'fēn', 'meaning': 'разделять'},
    '份': {'pinyin': 'fèn', 'meaning': 'порция; экземпляр'},
    '丰富': {'pinyin': 'fēngfù', 'meaning': 'богатый; разнообразный'},
    '否则': {'pinyin': 'fǒuzé', 'meaning': 'иначе'},
    '付款': {'pinyin': 'fùkuǎn', 'meaning': 'оплачивать'},
    '复印': {'pinyin': 'fùyìn', 'meaning': 'ксерокопировать'},
    '复杂': {'pinyin': 'fùzá', 'meaning': 'сложный'},
    '父母': {'pinyin': 'fùmǔ', 'meaning': 'родители'},
    '改变': {'pinyin': 'gǎibiàn', 'meaning': 'изменять'},
    '改进': {'pinyin': 'gǎijìn', 'meaning': 'улучшать'},
    '干杯': {'pinyin': 'gānbēi', 'meaning': 'за ваше здоровье'},
    '感动': {'pinyin': 'gǎndòng', 'meaning': 'быть тронутым'},
    '感谢': {'pinyin': 'gǎnxiè', 'meaning': 'благодарить'},
    '敢': {'pinyin': 'gǎn', 'meaning': 'сметь'},
    '赶': {'pinyin': 'gǎn', 'meaning': 'спешить'},
    '刚': {'pinyin': 'gāng', 'meaning': 'только что'},
    '刚才': {'pinyin': 'gāngcái', 'meaning': 'только что'},
    '高速公路': {'pinyin': 'gāosù gōnglù', 'meaning': 'автострада'},
    '胳膊': {'pinyin': 'gēbo', 'meaning': 'рука'},
    '各种': {'pinyin': 'gèzhǒng', 'meaning': 'различный'},
    '根据': {'pinyin': 'gēnjù', 'meaning': 'на основании'},
    '跟': {'pinyin': 'gēn', 'meaning': 'с; за'},
    '更加': {'pinyin': 'gèngjiā', 'meaning': 'еще более'},
    '工资': {'pinyin': 'gōngzī', 'meaning': 'зарплата'},
    '工具': {'pinyin': 'gōngjù', 'meaning': 'инструмент'},
    '工厂': {'pinyin': 'gōngchǎng', 'meaning': 'фабрика'},
    '公园': {'pinyin': 'gōngyuán', 'meaning': 'парк'},
    '恭喜': {'pinyin': 'gōngxǐ', 'meaning': 'поздравлять'},
    '购物': {'pinyin': 'gòuwù', 'meaning': 'делать покупки'},
    '够': {'pinyin': 'gòu', 'meaning': 'достаточно'},
    '估计': {'pinyin': 'gūjì', 'meaning': 'оценивать'},
    '鼓励': {'pinyin': 'gǔlì', 'meaning': 'поощрять'},
    '故意': {'pinyin': 'gùyì', 'meaning': 'намеренно'},
    '顾客': {'pinyin': 'gùkè', 'meaning': 'клиент'},
    '故事': {'pinyin': 'gùshì', 'meaning': 'история'},
    '过程': {'pinyin': 'guòchéng', 'meaning': 'процесс'},
    '过去': {'pinyin': 'guòqù', 'meaning': 'прошлое'},
    '果汁': {'pinyin': 'guǒzhī', 'meaning': 'сок'},
    '害怕': {'pinyin': 'hàipà', 'meaning': 'бояться'},
    '害羞': {'pinyin': 'hàixiū', 'meaning': 'стесняться'},
    '海洋': {'pinyin': 'hǎiyáng', 'meaning': 'океан'},
    '汗': {'pinyin': 'hàn', 'meaning': 'пот'},
    '好': {'pinyin': 'hǎo', 'meaning': 'хороший'},
    '好奇': {'pinyin': 'hàoqí', 'meaning': 'любопытный'},
    '合适': {'pinyin': 'héshì', 'meaning': 'подходящий'},
    '盒子': {'pinyin': 'hézi', 'meaning': 'коробка'},
    '河': {'pinyin': 'hé', 'meaning': 'река'},
    '合格': {'pinyin': 'hégé', 'meaning': 'квалифицированный'},
    '合同': {'pinyin': 'hétong', 'meaning': 'контракт'},
    '和平': {'pinyin': 'hépíng', 'meaning': 'мир'},
    '核心': {'pinyin': 'héxīn', 'meaning': 'ядро; суть'},
    '后悔': {'pinyin': 'hòuhuǐ', 'meaning': 'сожалеть'},
    '忽然': {'pinyin': 'hūrán', 'meaning': 'вдруг'},
    '互相': {'pinyin': 'hùxiāng', 'meaning': 'взаимно'},
    '护士': {'pinyin': 'hùshì', 'meaning': 'медсестра'},
    '护照': {'pinyin': 'hùzhào', 'meaning': 'паспорт'},
    '花': {'pinyin': 'huā', 'meaning': 'цветок'},
    '坏': {'pinyin': 'huài', 'meaning': 'плохой'},
    '怀念': {'pinyin': 'huáiniàn', 'meaning': 'скучать'},
    '还': {'pinyin': 'huán', 'meaning': 'возвращать'},
    '换': {'pinyin': 'huàn', 'meaning': 'менять'},
    '幻想': {'pinyin': 'huànxiǎng', 'meaning': 'фантазировать'},
    '黄': {'pinyin': 'huáng', 'meaning': 'желтый'},
    '谎话': {'pinyin': 'huǎnghuà', 'meaning': 'ложь'},
    '活动': {'pinyin': 'huódòng', 'meaning': 'мероприятие'},
    '活泼': {'pinyin': 'huópō', 'meaning': 'живой; энергичный'},
    '或者': {'pinyin': 'huòzhě', 'meaning': 'или'},
    '火': {'pinyin': 'huǒ', 'meaning': 'огонь'},
    '获得': {'pinyin': 'huòdé', 'meaning': 'получать'},
    '货': {'pinyin': 'huò', 'meaning': 'товар'},
    '极': {'pinyin': 'jí', 'meaning': 'чрезвычайно'},
    '基本': {'pinyin': 'jīběn', 'meaning': 'основной'},
    '基础': {'pinyin': 'jīchǔ', 'meaning': 'основа'},
    '激动': {'pinyin': 'jīdòng', 'meaning': 'волноваться'},
    '记得': {'pinyin': 'jìde', 'meaning': 'помнить'},
    '技术': {'pinyin': 'jìshù', 'meaning': 'технология'},
    '继续': {'pinyin': 'jìxù', 'meaning': 'продолжать'},
    '计划': {'pinyin': 'jìhuà', 'meaning': 'планировать'},
    '寄': {'pinyin': 'jì', 'meaning': 'отправлять (почту)'},
    '加班': {'pinyin': 'jiābān', 'meaning': 'работать сверхурочно'},
    '加油': {'pinyin': 'jiāyóu', 'meaning': 'заправляться; стараться'},
    '价格': {'pinyin': 'jiàgé', 'meaning': 'цена'},
    '架': {'pinyin': 'jià', 'meaning': 'стойка; мера для самолетов'},
    '假': {'pinyin': 'jiǎ', 'meaning': 'фальшивый'},
    '假期': {'pinyin': 'jiàqī', 'meaning': 'каникулы'},
    '坚持': {'pinyin': 'jiānchí', 'meaning': 'упорствовать'},
    '减肥': {'pinyin': 'jiǎnféi', 'meaning': 'худеть'},
    '减少': {'pinyin': 'jiǎnshǎo', 'meaning': 'уменьшать'},
    '建议': {'pinyin': 'jiànyì', 'meaning': 'предлагать'},
    '将来': {'pinyin': 'jiānglái', 'meaning': 'будущее'},
    '讲': {'pinyin': 'jiǎng', 'meaning': 'говорить; объяснять'},
    '酱油': {'pinyin': 'jiàngyóu', 'meaning': 'соевый соус'},
    '降落': {'pinyin': 'jiàngluò', 'meaning': 'приземляться'},
    '交': {'pinyin': 'jiāo', 'meaning': 'передавать'},
    '交流': {'pinyin': 'jiāoliú', 'meaning': 'общаться'},
    '交通': {'pinyin': 'jiāotōng', 'meaning': 'транспорт'},
    '骄傲': {'pinyin': 'jiāoào', 'meaning': 'гордиться'},
    '饺子': {'pinyin': 'jiǎozi', 'meaning': 'пельмени'},
    '教育': {'pinyin': 'jiàoyù', 'meaning': 'образование'},
    '接受': {'pinyin': 'jiēshòu', 'meaning': 'принимать'},
    '节约': {'pinyin': 'jiéyuē', 'meaning': 'экономить'},
    '结果': {'pinyin': 'jiéguǒ', 'meaning': 'результат'},
    '解释': {'pinyin': 'jiěshì', 'meaning': 'объяснять'},
    '借': {'pinyin': 'jiè', 'meaning': 'брать в долг'},
    '结婚': {'pinyin': 'jiéhūn', 'meaning': 'жениться; выходить замуж'},
    '节': {'pinyin': 'jié', 'meaning': 'праздник'},
    '节日': {'pinyin': 'jiérì', 'meaning': 'праздник'},
    '尽管': {'pinyin': 'jǐnguǎn', 'meaning': 'хотя; несмотря на'},
    '紧张': {'pinyin': 'jǐnzhāng', 'meaning': 'нервничать'},
    '进行': {'pinyin': 'jìnxíng', 'meaning': 'проводить'},
    '禁止': {'pinyin': 'jìnzhǐ', 'meaning': 'запрещать'},
    '竟然': {'pinyin': 'jìngrán', 'meaning': 'неожиданно'},
    '经济': {'pinyin': 'jīngjì', 'meaning': 'экономика'},
    '警察': {'pinyin': 'jǐngchá', 'meaning': 'полиция'},
    '竞争': {'pinyin': 'jìngzhēng', 'meaning': 'конкурировать'},
    '静': {'pinyin': 'jìng', 'meaning': 'спокойный'},
    '镜子': {'pinyin': 'jìngzi', 'meaning': 'зеркало'},
    '究竟': {'pinyin': 'jiūjìng', 'meaning': 'в конце концов'},
    '酒': {'pinyin': 'jiǔ', 'meaning': 'алкоголь'},
    '救': {'pinyin': 'jiù', 'meaning': 'спасать'},
    '旧': {'pinyin': 'jiù', 'meaning': 'старый'},
    '就': {'pinyin': 'jiù', 'meaning': 'именно; сразу'},
    '举手': {'pinyin': 'jǔshǒu', 'meaning': 'поднимать руку'},
    '举行': {'pinyin': 'jǔxíng', 'meaning': 'проводить (мероприятие)'},
    '拒绝': {'pinyin': 'jùjué', 'meaning': 'отказываться'},
    '距离': {'pinyin': 'jùlí', 'meaning': 'расстояние'},
    '开玩笑': {'pinyin': 'kāiwánxiào', 'meaning': 'шутить'},
    '看': {'pinyin': 'kàn', 'meaning': 'смотреть'},
    '看法': {'pinyin': 'kànfǎ', 'meaning': 'мнение'},
    '棵': {'pinyin': 'kē', 'meaning': 'мера для деревьев'},
    '咳嗽': {'pinyin': 'késòu', 'meaning': 'кашлять'},
    '可爱': {'pinyin': 'kěài', 'meaning': 'милый'},
    '渴': {'pinyin': 'kě', 'meaning': 'жаждать'},
    '刻': {'pinyin': 'kè', 'meaning': 'момент'},
    '客人': {'pinyin': 'kèrén', 'meaning': 'гость'},
    '空气': {'pinyin': 'kōngqì', 'meaning': 'воздух'},
    '恐怕': {'pinyin': 'kǒngpà', 'meaning': 'боюсь, что'},
    '控制': {'pinyin': 'kòngzhì', 'meaning': 'контролировать'},
    '哭': {'pinyin': 'kū', 'meaning': 'плакать'},
    '夸': {'pinyin': 'kuā', 'meaning': 'хвалить'},
    '跨': {'pinyin': 'kuà', 'meaning': 'перешагивать'},
    '块': {'pinyin': 'kuài', 'meaning': 'кусок; мера'},
    '筷子': {'pinyin': 'kuàizi', 'meaning': 'палочки для еды'},
    '宽': {'pinyin': 'kuān', 'meaning': 'широкий'},
    '困': {'pinyin': 'kùn', 'meaning': 'сонный'},
    '困难': {'pinyin': 'kùnnán', 'meaning': 'трудный'},
    '拉': {'pinyin': 'lā', 'meaning': 'тянуть'},
    '垃圾': {'pinyin': 'lājī', 'meaning': 'мусор'},
    '辣': {'pinyin': 'là', 'meaning': 'острый'},
    '来不及': {'pinyin': 'láibùjí', 'meaning': 'не успеть'},
    '来得及': {'pinyin': 'láidejí', 'meaning': 'успеть'},
    '懒': {'pinyin': 'lǎn', 'meaning': 'ленивый'},
    '浪费': {'pinyin': 'làngfèi', 'meaning': 'тратить впустую'},
    '浪漫': {'pinyin': 'làngmàn', 'meaning': 'романтичный'},
    '狼': {'pinyin': 'láng', 'meaning': 'волк'},
    '老': {'pinyin': 'lǎo', 'meaning': 'старый'},
    '劳驾': {'pinyin': 'láojià', 'meaning': 'извините (вежливо)'},
    '老板': {'pinyin': 'lǎobǎn', 'meaning': 'босс'},
    '姥姥': {'pinyin': 'lǎolao', 'meaning': 'бабушка (по матери)'},
    '冷': {'pinyin': 'lěng', 'meaning': 'холодный'},
    '梨': {'pinyin': 'lí', 'meaning': 'груша'},
    '礼貌': {'pinyin': 'lǐmào', 'meaning': 'вежливость'},
    '理发': {'pinyin': 'lǐfà', 'meaning': 'стричься'},
    '理解': {'pinyin': 'lǐjiě', 'meaning': 'понимать'},
    '理想': {'pinyin': 'lǐxiǎng', 'meaning': 'идеал'},
    '离开': {'pinyin': 'líkāi', 'meaning': 'покидать'},
    '立刻': {'pinyin': 'lìkè', 'meaning': 'немедленно'},
    '力气': {'pinyin': 'lìqì', 'meaning': 'сила'},
    '例如': {'pinyin': 'lìrú', 'meaning': 'например'},
    '流': {'pinyin': 'liú', 'meaning': 'течь'},
    '流行': {'pinyin': 'liúxíng', 'meaning': 'популярный'},
    '留': {'pinyin': 'liú', 'meaning': 'оставлять'},
    '留学': {'pinyin': 'liúxué', 'meaning': 'учиться за границей'},
    '楼': {'pinyin': 'lóu', 'meaning': 'здание; этаж'},
    '露': {'pinyin': 'lù', 'meaning': 'роса; показывать'},
    '陆地': {'pinyin': 'lùdì', 'meaning': 'суша'},
    '乱': {'pinyin': 'luàn', 'meaning': 'беспорядок'},
    '律师': {'pinyin': 'lǜshī', 'meaning': 'адвокат'},
    '旅游': {'pinyin': 'lǚyóu', 'meaning': 'путешествовать'},
    '绿': {'pinyin': 'lǜ', 'meaning': 'зеленый'},
    '妈妈': {'pinyin': 'māma', 'meaning': 'мама'},
    '麻烦': {'pinyin': 'máfán', 'meaning': 'проблема; хлопоты'},
    '马': {'pinyin': 'mǎ', 'meaning': 'лошадь'},
    '马上': {'pinyin': 'mǎshàng', 'meaning': 'немедленно'},
    '满足': {'pinyin': 'mǎnzú', 'meaning': 'удовлетворять'},
    '慢慢': {'pinyin': 'mànmàn', 'meaning': 'медленно'},
    '毛': {'pinyin': 'máo', 'meaning': 'волос; шерсть'},
    '帽子': {'pinyin': 'màozi', 'meaning': 'шапка'},
    '没': {'pinyin': 'méi', 'meaning': 'не'},
    '美味': {'pinyin': 'měiwèi', 'meaning': 'вкусный'},
    '每次': {'pinyin': 'měicì', 'meaning': 'каждый раз'},
    '妹妹': {'pinyin': 'mèimei', 'meaning': 'младшая сестра'},
    '魅力': {'pinyin': 'mèilì', 'meaning': 'очарование'},
    '迷路': {'pinyin': 'mílù', 'meaning': 'заблудиться'},
    '秘密': {'pinyin': 'mìmì', 'meaning': 'секрет'},
    '棉': {'pinyin': 'mián', 'meaning': 'хлопок'},
    '免费': {'pinyin': 'miǎnfèi', 'meaning': 'бесплатный'},
    '面条': {'pinyin': 'miàntiáo', 'meaning': 'лапша'},
    '描写': {'pinyin': 'miáoxiě', 'meaning': 'описывать'},
    '秒': {'pinyin': 'miǎo', 'meaning': 'секунда'},
    '目标': {'pinyin': 'mùbiāo', 'meaning': 'цель'},
    '木': {'pinyin': 'mù', 'meaning': 'дерево'},
    '目前': {'pinyin': 'mùqián', 'meaning': 'в настоящее время'},
    '拿': {'pinyin': 'ná', 'meaning': 'брать'},
    '奶奶': {'pinyin': 'nǎinai', 'meaning': 'бабушка (по отцу)'},
    '耐心': {'pinyin': 'nàixīn', 'meaning': 'терпение'},
    '南': {'pinyin': 'nán', 'meaning': 'юг'},
    '难过': {'pinyin': 'nánguò', 'meaning': 'грустить'},
    '难看': {'pinyin': 'nánkàn', 'meaning': 'некрасивый'},
    '脑袋': {'pinyin': 'nǎodai', 'meaning': 'голова'},
    '内': {'pinyin': 'nèi', 'meaning': 'внутри'},
    '内容': {'pinyin': 'nèiróng', 'meaning': 'содержание'},
    '能力': {'pinyin': 'nénglì', 'meaning': 'способность'},
    '年龄': {'pinyin': 'niánlíng', 'meaning': 'возраст'},
    '年轻': {'pinyin': 'niánqīng', 'meaning': 'молодой'},
    '鸟': {'pinyin': 'niǎo', 'meaning': 'птица'},
    '努力': {'pinyin': 'nǔlì', 'meaning': 'стараться'},
    '农村': {'pinyin': 'nóngcūn', 'meaning': 'деревня'},
    '弄': {'pinyin': 'nòng', 'meaning': 'возиться; делать'},
    '偶尔': {'pinyin': 'ǒurán', 'meaning': 'иногда'},
    '欧洲': {'pinyin': 'Ōuzhōu', 'meaning': 'Европа'},
    '爬': {'pinyin': 'pá', 'meaning': 'ползать'},
    '怕': {'pinyin': 'pà', 'meaning': 'бояться'},
    '拍': {'pinyin': 'pāi', 'meaning': 'снимать; хлопать'},
    '排队': {'pinyin': 'páiduì', 'meaning': 'стоять в очереди'},
    '派': {'pinyin': 'pài', 'meaning': 'отправлять'},
    '盘子': {'pinyin': 'pánzi', 'meaning': 'тарелка'},
    '判断': {'pinyin': 'pànduàn', 'meaning': 'судить'},
    '陪': {'pinyin': 'péi', 'meaning': 'сопровождать'},
    '批评': {'pinyin': 'pīpíng', 'meaning': 'критиковать'},
    '皮鞋': {'pinyin': 'píxié', 'meaning': 'кожаная обувь'},
    '脾气': {'pinyin': 'píqì', 'meaning': 'характер'},
    '啤酒': {'pinyin': 'píjiǔ', 'meaning': 'пиво'},
    '篇': {'pinyin': 'piān', 'meaning': 'мера для статей'},
    '骗': {'pinyin': 'piàn', 'meaning': 'обманывать'},
    '漂': {'pinyin': 'piāo', 'meaning': 'плыть'},
    '票': {'pinyin': 'piào', 'meaning': 'билет'},
    '瓶子': {'pinyin': 'píngzi', 'meaning': 'бутылка'},
    '平时': {'pinyin': 'píngshí', 'meaning': 'обычно'},
    '破': {'pinyin': 'pò', 'meaning': 'ломать'},
    '普遍': {'pinyin': 'pǔbiàn', 'meaning': 'распространенный'},
    '普通': {'pinyin': 'pǔtōng', 'meaning': 'обычный'},
    '奇怪': {'pinyin': 'qíguài', 'meaning': 'странный'},
    '其实': {'pinyin': 'qíshí', 'meaning': 'на самом деле'},
    '气候': {'pinyin': 'qìhòu', 'meaning': 'климат'},
    '汽水': {'pinyin': 'qìshuǐ', 'meaning': 'газированная вода'},
    '千克': {'pinyin': 'qiānkè', 'meaning': 'килограмм'},
    '签证': {'pinyin': 'qiānzhèng', 'meaning': 'виза'},
    '桥': {'pinyin': 'qiáo', 'meaning': 'мост'},
    '悄悄': {'pinyin': 'qiāoqiāo', 'meaning': 'тихо'},
    '敲': {'pinyin': 'qiāo', 'meaning': 'стучать'},
    '巧克力': {'pinyin': 'qiǎokèlì', 'meaning': 'шоколад'},
    '亲爱': {'pinyin': 'qīnài', 'meaning': 'дорогой'},
    '亲戚': {'pinyin': 'qīnqī', 'meaning': 'родственник'},
    '轻': {'pinyin': 'qīng', 'meaning': 'легкий'},
    '情况': {'pinyin': 'qíngkuàng', 'meaning': 'ситуация'},
    '晴': {'pinyin': 'qíng', 'meaning': 'ясный (о погоде)'},
    '请假': {'pinyin': 'qǐngjià', 'meaning': 'брать отпуск'},
    '请求': {'pinyin': 'qǐngqiú', 'meaning': 'просить'},
    '青春': {'pinyin': 'qīngchūn', 'meaning': 'юность'},
    '清楚': {'pinyin': 'qīngchǔ', 'meaning': 'ясный'},
    '庆祝': {'pinyin': 'qìngzhù', 'meaning': 'праздновать'},
    '取': {'pinyin': 'qǔ', 'meaning': 'брать'},
    '取消': {'pinyin': 'qǔxiāo', 'meaning': 'отменять'},
    '去': {'pinyin': 'qù', 'meaning': 'идти'},
    '全部': {'pinyin': 'quánbù', 'meaning': 'весь'},
    '圈': {'pinyin': 'quān', 'meaning': 'круг'},
    '缺点': {'pinyin': 'quēdiǎn', 'meaning': 'недостаток'},
    '缺少': {'pinyin': 'quēshǎo', 'meaning': 'не хватать'},
    '却': {'pinyin': 'què', 'meaning': 'однако'},
    '确实': {'pinyin': 'quèshí', 'meaning': 'действительно'},
    '热': {'pinyin': 'rè', 'meaning': 'горячий'},
    '热情': {'pinyin': 'rèqíng', 'meaning': 'энтузиазм'},
    '人': {'pinyin': 'rén', 'meaning': 'человек'},
    '任何': {'pinyin': 'rènhé', 'meaning': 'любой'},
    '认识': {'pinyin': 'rènshí', 'meaning': 'знать; узнавать'},
    '认真': {'pinyin': 'rènzhēn', 'meaning': 'серьезный'},
    '扔': {'pinyin': 'rēng', 'meaning': 'бросать'},
    '仍然': {'pinyin': 'réngrán', 'meaning': 'по-прежнему'},
    '日': {'pinyin': 'rì', 'meaning': 'день'},
    '日记': {'pinyin': 'rìjì', 'meaning': 'дневник'},
    '入口': {'pinyin': 'rùkǒu', 'meaning': 'вход'},
    '软': {'pinyin': 'ruǎn', 'meaning': 'мягкий'},
    '弱': {'pinyin': 'ruò', 'meaning': 'слабый'},
    '洒': {'pinyin': 'sǎ', 'meaning': 'разбрызгивать'},
    '三': {'pinyin': 'sān', 'meaning': 'три'},
    '伞': {'pinyin': 'sǎn', 'meaning': 'зонт'},
    '散步': {'pinyin': 'sànbù', 'meaning': 'гулять'},
    '森林': {'pinyin': 'sēnlín', 'meaning': 'лес'},
    '沙': {'pinyin': 'shā', 'meaning': 'песок'},
    '沙漠': {'pinyin': 'shāmò', 'meaning': 'пустыня'},
    '傻': {'pinyin': 'shǎ', 'meaning': 'глупый'},
    '晒': {'pinyin': 'shài', 'meaning': 'загорать'},
    '删除': {'pinyin': 'shānchū', 'meaning': 'удалять'},
    '善良': {'pinyin': 'shànliáng', 'meaning': 'добрый'},
    '商店': {'pinyin': 'shāngdiàn', 'meaning': 'магазин'},
    '伤心': {'pinyin': 'shāngxīn', 'meaning': 'грустить'},
    '稍微': {'pinyin': 'shāowēi', 'meaning': 'немного'},
    '少': {'pinyin': 'shǎo', 'meaning': 'мало'},
    '社会': {'pinyin': 'shèhuì', 'meaning': 'общество'},
    '设计': {'pinyin': 'shèjì', 'meaning': 'проектировать'},
    '设备': {'pinyin': 'shèbèi', 'meaning': 'оборудование'},
    '生活': {'pinyin': 'shēnghuó', 'meaning': 'жизнь'},
    '申请': {'pinyin': 'shēnqǐng', 'meaning': 'подавать заявку'},
    '甚至': {'pinyin': 'shènzhì', 'meaning': 'даже'},
    '深': {'pinyin': 'shēn', 'meaning': 'глубокий'},
    '神': {'pinyin': 'shén', 'meaning': 'бог'},
    '声': {'pinyin': 'shēng', 'meaning': 'звук'},
    '剩': {'pinyin': 'shèng', 'meaning': 'оставаться'},
    '胜利': {'pinyin': 'shènglì', 'meaning': 'победа'},
    '省': {'pinyin': 'shěng', 'meaning': 'провинция'},
    '升': {'pinyin': 'shēng', 'meaning': 'подниматься'},
    '绳子': {'pinyin': 'shéngzi', 'meaning': 'веревка'},
    '时代': {'pinyin': 'shídài', 'meaning': 'эпоха'},
    '适合': {'pinyin': 'shìhé', 'meaning': 'подходить'},
    '适应': {'pinyin': 'shìyìng', 'meaning': 'приспосабливаться'},
    '世纪': {'pinyin': 'shìjì', 'meaning': 'век'},
    '时间': {'pinyin': 'shíjiān', 'meaning': 'время'},
    '实际': {'pinyin': 'shíjì', 'meaning': 'реальный'},
    '实习': {'pinyin': 'shíxí', 'meaning': 'стажировка'},
    '实现': {'pinyin': 'shíxiàn', 'meaning': 'реализовывать'},
    '实验': {'pinyin': 'shíyàn', 'meaning': 'эксперимент'},
    '食物': {'pinyin': 'shíwù', 'meaning': 'еда'},
    '使用': {'pinyin': 'shǐyòng', 'meaning': 'использовать'},
    '试': {'pinyin': 'shì', 'meaning': 'пробовать'},
    '市场': {'pinyin': 'shìchǎng', 'meaning': 'рынок'},
    '失望': {'pinyin': 'shīwàng', 'meaning': 'разочаровываться'},
    '师傅': {'pinyin': 'shīfu', 'meaning': 'мастер'},
    '湿': {'pinyin': 'shī', 'meaning': 'влажный'},
    '狮子': {'pinyin': 'shīzi', 'meaning': 'лев'},
    '是': {'pinyin': 'shì', 'meaning': 'быть'},
    '是否': {'pinyin': 'shìfǒu', 'meaning': 'ли; будь то'},
    '世界': {'pinyin': 'shìjiè', 'meaning': 'мир'},
    '事故': {'pinyin': 'shìgù', 'meaning': 'происшествие'},
    '时尚': {'pinyin': 'shíshàng', 'meaning': 'мода'},
    '收': {'pinyin': 'shōu', 'meaning': 'получать'},
    '收拾': {'pinyin': 'shōushí', 'meaning': 'прибирать'},
    '瘦': {'pinyin': 'shòu', 'meaning': 'худой'},
    '受不了': {'pinyin': 'shòubùliǎo', 'meaning': 'не выносить'},
    '舒服': {'pinyin': 'shūfu', 'meaning': 'удобный'},
    '书': {'pinyin': 'shū', 'meaning': 'книга'},
    '熟': {'pinyin': 'shú', 'meaning': 'зрелый; знакомый'},
    '属于': {'pinyin': 'shǔyú', 'meaning': 'принадлежать'},
    '数学': {'pinyin': 'shùxué', 'meaning': 'математика'},
    '数字': {'pinyin': 'shùzì', 'meaning': 'цифра'},
    '刷牙': {'pinyin': 'shuāyá', 'meaning': 'чистить зубы'},
    '帅': {'pinyin': 'shuài', 'meaning': 'красивый (о мужчинах)'},
    '顺便': {'pinyin': 'shùnbiàn', 'meaning': 'заодно'},
    '顺利': {'pinyin': 'shùnlì', 'meaning': 'успешно'},
    '说明': {'pinyin': 'shuōmíng', 'meaning': 'объяснять'},
    '硕士': {'pinyin': 'shuòshì', 'meaning': 'магистр'},
    '水平': {'pinyin': 'shuǐpíng', 'meaning': 'уровень'},
    '睡着': {'pinyin': 'shuìzháo', 'meaning': 'засыпать'},
    '司机': {'pinyin': 'sījī', 'meaning': 'водитель'},
    '死': {'pinyin': 'sǐ', 'meaning': 'умирать'},
    '速度': {'pinyin': 'sùdù', 'meaning': 'скорость'},
    '塑料': {'pinyin': 'sùliào', 'meaning': 'пластик'},
    '酸': {'pinyin': 'suān', 'meaning': 'кислый'},
    '算': {'pinyin': 'suàn', 'meaning': 'считать'},
    '随便': {'pinyin': 'suíbiàn', 'meaning': 'небрежный; как угодно'},
    '虽然': {'pinyin': 'suīrán', 'meaning': 'хотя'},
    '随时': {'pinyin': 'suíshí', 'meaning': 'в любое время'},
    '孙子': {'pinyin': 'sūnzi', 'meaning': 'внук'},
    '所有': {'pinyin': 'suǒyǒu', 'meaning': 'все'},
    '锁': {'pinyin': 'suǒ', 'meaning': 'замок'},
    '塔': {'pinyin': 'tǎ', 'meaning': 'башня'},
    '太': {'pinyin': 'tài', 'meaning': 'слишком'},
    '态度': {'pinyin': 'tàidù', 'meaning': 'отношение'},
    '台': {'pinyin': 'tái', 'meaning': 'платформа; мера'},
    '抬': {'pinyin': 'tái', 'meaning': 'поднимать'},
    '谈': {'pinyin': 'tán', 'meaning': 'разговаривать'},
    '弹钢琴': {'pinyin': 'tángāngqín', 'meaning': 'играть на пианино'},
    '汤': {'pinyin': 'tāng', 'meaning': 'суп'},
    '糖': {'pinyin': 'táng', 'meaning': 'сахар'},
    '躺': {'pinyin': 'tǎng', 'meaning': 'лежать'},
    '讨论': {'pinyin': 'tǎolùn', 'meaning': 'обсуждать'},
    '讨厌': {'pinyin': 'tǎoyàn', 'meaning': 'ненавидеть'},
    '特点': {'pinyin': 'tèdiǎn', 'meaning': 'особенность'},
    '提': {'pinyin': 'tí', 'meaning': 'поднимать'},
    '提供': {'pinyin': 'tígōng', 'meaning': 'предоставлять'},
    '提前': {'pinyin': 'tíqián', 'meaning': 'заранее'},
    '提醒': {'pinyin': 'tíxǐng', 'meaning': 'напоминать'},
    '题': {'pinyin': 'tí', 'meaning': 'вопрос; тема'},
    '体育': {'pinyin': 'tǐyù', 'meaning': 'физкультура'},
    '替': {'pinyin': 'tì', 'meaning': 'заменять'},
    '天': {'pinyin': 'tiān', 'meaning': 'небо; день'},
    '甜': {'pinyin': 'tián', 'meaning': 'сладкий'},
    '条': {'pinyin': 'tiáo', 'meaning': 'полоса; мера'},
    '条件': {'pinyin': 'tiáojiàn', 'meaning': 'условие'},
    '跳': {'pinyin': 'tiào', 'meaning': 'прыгать'},
    '调皮': {'pinyin': 'tiáopí', 'meaning': 'озорной'},
    '停': {'pinyin': 'tíng', 'meaning': 'останавливаться'},
    '挺': {'pinyin': 'tǐng', 'meaning': 'весьма'},
    '通过': {'pinyin': 'tōngguò', 'meaning': 'через; проходить'},
    '同情': {'pinyin': 'tóngqíng', 'meaning': 'сочувствовать'},
    '同事': {'pinyin': 'tóngshì', 'meaning': 'коллега'},
    '同意': {'pinyin': 'tóngyì', 'meaning': 'соглашаться'},
    '通知': {'pinyin': 'tōngzhī', 'meaning': 'уведомлять'},
    '痛': {'pinyin': 'tòng', 'meaning': 'боль'},
    '痛苦': {'pinyin': 'tòngkǔ', 'meaning': 'страдание'},
    '偷': {'pinyin': 'tōu', 'meaning': 'украсть'},
    '投资': {'pinyin': 'tóuzī', 'meaning': 'инвестировать'},
    '透明': {'pinyin': 'tòumíng', 'meaning': 'прозрачный'},
    '突然': {'pinyin': 'tūrán', 'meaning': 'вдруг'},
    '图书馆': {'pinyin': 'túshūguǎn', 'meaning': 'библиотека'},
    '推': {'pinyin': 'tuī', 'meaning': 'толкать'},
    '推迟': {'pinyin': 'tuīchí', 'meaning': 'откладывать'},
    '腿': {'pinyin': 'tuǐ', 'meaning': 'нога'},
    '退': {'pinyin': 'tuì', 'meaning': 'отступать'},
    '脱': {'pinyin': 'tuō', 'meaning': 'снимать (одежду)'},
    '袜子': {'pinyin': 'wàzi', 'meaning': 'носки'},
    '外': {'pinyin': 'wài', 'meaning': 'внешний'},
    '玩': {'pinyin': 'wán', 'meaning': 'играть'},
    '完成': {'pinyin': 'wánchéng', 'meaning': 'завершать'},
    '完美': {'pinyin': 'wánměi', 'meaning': 'совершенный'},
    '完全': {'pinyin': 'wánquán', 'meaning': 'полностью'},
    '玩具': {'pinyin': 'wánjù', 'meaning': 'игрушка'},
    '万': {'pinyin': 'wàn', 'meaning': 'десять тысяч'},
    '忘记': {'pinyin': 'wàngjì', 'meaning': 'забывать'},
    '危险': {'pinyin': 'wēixiǎn', 'meaning': 'опасный'},
    '为': {'pinyin': 'wèi', 'meaning': 'для'},
    '为什么': {'pinyin': 'wèishénme', 'meaning': 'почему'},
    '喂': {'pinyin': 'wèi', 'meaning': 'кормить; алло'},
    '伟大': {'pinyin': 'wěidà', 'meaning': 'великий'},
    '味道': {'pinyin': 'wèidào', 'meaning': 'вкус'},
    '温度': {'pinyin': 'wēndù', 'meaning': 'температура'},
    '文件': {'pinyin': 'wénjiàn', 'meaning': 'файл'},
    '文具': {'pinyin': 'wénjù', 'meaning': 'канцелярские товары'},
    '文章': {'pinyin': 'wénzhāng', 'meaning': 'статья'},
    '污染': {'pinyin': 'wūrǎn', 'meaning': 'загрязнение'},
    '无': {'pinyin': 'wú', 'meaning': 'без'},
    '误会': {'pinyin': 'wùhuì', 'meaning': 'недоразумение'},
    '物理': {'pinyin': 'wùlǐ', 'meaning': 'физика'},
    '西': {'pinyin': 'xī', 'meaning': 'запад'},
    '吸引': {'pinyin': 'xīyǐn', 'meaning': 'привлекать'},
    '西瓜': {'pinyin': 'xīguā', 'meaning': 'арбуз'},
    '习惯': {'pinyin': 'xíguàn', 'meaning': 'привычка'},
    '洗手间': {'pinyin': 'xǐshǒujiān', 'meaning': 'туалет'},
    '洗澡': {'pinyin': 'xǐzǎo', 'meaning': 'принимать душ'},
    '下': {'pinyin': 'xià', 'meaning': 'вниз'},
    '吓': {'pinyin': 'xià', 'meaning': 'пугать'},
    '下载': {'pinyin': 'xiàzài', 'meaning': 'скачивать'},
    '夏天': {'pinyin': 'xiàtiān', 'meaning': 'лето'},
    '现代': {'pinyin': 'xiàndài', 'meaning': 'современный'},
    '羡慕': {'pinyin': 'xiànmù', 'meaning': 'завидовать'},
    '现金': {'pinyin': 'xiànjīn', 'meaning': 'наличные'},
    '显得': {'pinyin': 'xiǎnde', 'meaning': 'казаться'},
    '现象': {'pinyin': 'xiànxiàng', 'meaning': 'явление'},
    '现在': {'pinyin': 'xiànzài', 'meaning': 'сейчас'},
    '现实': {'pinyin': 'xiànshí', 'meaning': 'реальность'},
    '线': {'pinyin': 'xiàn', 'meaning': 'линия'},
    '限制': {'pinyin': 'xiànzhì', 'meaning': 'ограничивать'},
    '香': {'pinyin': 'xiāng', 'meaning': 'ароматный'},
    '香蕉': {'pinyin': 'xiāngjiāo', 'meaning': 'банан'},
    '箱子': {'pinyin': 'xiāngzi', 'meaning': 'ящик'},
    '想': {'pinyin': 'xiǎng', 'meaning': 'думать'},
    '向': {'pinyin': 'xiàng', 'meaning': 'к; в сторону'},
    '相信': {'pinyin': 'xiāngxìn', 'meaning': 'верить'},
    '详细': {'pinyin': 'xiángxì', 'meaning': 'подробный'},
    '响': {'pinyin': 'xiǎng', 'meaning': 'звучать'},
    '享受': {'pinyin': 'xiǎngshòu', 'meaning': 'наслаждаться'},
    '想象': {'pinyin': 'xiǎngxiàng', 'meaning': 'воображать'},
    '消息': {'pinyin': 'xiāoxī', 'meaning': 'новости'},
    '小心': {'pinyin': 'xiǎoxīn', 'meaning': 'осторожный'},
    '消失': {'pinyin': 'xiāoshī', 'meaning': 'исчезать'},
    '笑话': {'pinyin': 'xiàohuà', 'meaning': 'анекдот'},
    '效果': {'pinyin': 'xiàoguǒ', 'meaning': 'эффект'},
    '效率': {'pinyin': 'xiàolǜ', 'meaning': 'эффективность'},
    '校长': {'pinyin': 'xiàozhǎng', 'meaning': 'директор школы'},
    '孝顺': {'pinyin': 'xiàoshùn', 'meaning': 'почтительный'},
    '鞋': {'pinyin': 'xié', 'meaning': 'обувь'},
    '斜': {'pinyin': 'xié', 'meaning': 'наклонный'},
    '谢谢': {'pinyin': 'xièxiè', 'meaning': 'спасибо'},
    '写作': {'pinyin': 'xiězuò', 'meaning': 'писать (текст)'},
    '心理': {'pinyin': 'xīnlǐ', 'meaning': 'психология'},
    '心情': {'pinyin': 'xīnqíng', 'meaning': 'настроение'},
    '辛苦': {'pinyin': 'xīnkǔ', 'meaning': 'тяжелый труд'},
    '信': {'pinyin': 'xìn', 'meaning': 'письмо'},
    '信息': {'pinyin': 'xìnxī', 'meaning': 'информация'},
    '信心': {'pinyin': 'xìnxīn', 'meaning': 'уверенность'},
    '新鲜': {'pinyin': 'xīnxiān', 'meaning': 'свежий'},
    '行李箱': {'pinyin': 'xínglǐxiāng', 'meaning': 'чемодан'},
    '行': {'pinyin': 'xíng', 'meaning': 'идти; годиться'},
    '醒': {'pinyin': 'xǐng', 'meaning': 'просыпаться'},
    '幸福': {'pinyin': 'xìngfú', 'meaning': 'счастье'},
    '性别': {'pinyin': 'xìngbié', 'meaning': 'пол'},
    '性格': {'pinyin': 'xìnggé', 'meaning': 'характер'},
    '幸运': {'pinyin': 'xìngyùn', 'meaning': 'удачливый'},
    '兄弟': {'pinyin': 'xiōngdì', 'meaning': 'братья'},
    '熊': {'pinyin': 'xióng', 'meaning': 'медведь'},
    '雄伟': {'pinyin': 'xióngwěi', 'meaning': 'величественный'},
    '修': {'pinyin': 'xiū', 'meaning': 'ремонтировать'},
    '休息': {'pinyin': 'xiūxí', 'meaning': 'отдыхать'},
    '需要': {'pinyin': 'xūyào', 'meaning': 'нуждаться'},
    '选择': {'pinyin': 'xuǎnzé', 'meaning': 'выбирать'},
    '选举': {'pinyin': 'xuǎnjǔ', 'meaning': 'выборы'},
    '学期': {'pinyin': 'xuéqī', 'meaning': 'семестр'},
    '学生': {'pinyin': 'xuéshēng', 'meaning': 'студент'},
    '学习': {'pinyin': 'xuéxí', 'meaning': 'учиться'},
    '学校': {'pinyin': 'xuéxiào', 'meaning': 'школа'},
    '雪': {'pinyin': 'xuě', 'meaning': 'снег'},
    '压': {'pinyin': 'yā', 'meaning': 'давить'},
    '压力': {'pinyin': 'yālì', 'meaning': 'давление'},
    '牙': {'pinyin': 'yá', 'meaning': 'зуб'},
    '牙膏': {'pinyin': 'yágāo', 'meaning': 'зубная паста'},
    '亚洲': {'pinyin': 'Yàzhōu', 'meaning': 'Азия'},
    '呀': {'pinyin': 'ya', 'meaning': 'частица удивления'},
    '研究': {'pinyin': 'yánjiū', 'meaning': 'исследовать'},
    '眼镜': {'pinyin': 'yǎnjìng', 'meaning': 'очки'},
    '盐': {'pinyin': 'yán', 'meaning': 'соль'},
    '严重': {'pinyin': 'yánzhòng', 'meaning': 'серьезный'},
    '演出': {'pinyin': 'yǎnchū', 'meaning': 'выступление'},
    '演员': {'pinyin': 'yǎnyuán', 'meaning': 'актер'},
    '眼睛': {'pinyin': 'yǎnjīng', 'meaning': 'глаза'},
    '颜色': {'pinyin': 'yánsè', 'meaning': 'цвет'},
    '羊': {'pinyin': 'yáng', 'meaning': 'овца'},
    '样子': {'pinyin': 'yàngzi', 'meaning': 'вид; внешность'},
    '邀请': {'pinyin': 'yāoqǐng', 'meaning': 'приглашать'},
    '要求': {'pinyin': 'yāoqiú', 'meaning': 'требовать'},
    '药': {'pinyin': 'yào', 'meaning': 'лекарство'},
    '钥匙': {'pinyin': 'yàoshi', 'meaning': 'ключ'},
    '要': {'pinyin': 'yào', 'meaning': 'хотеть; нужно'},
    '爷': {'pinyin': 'yé', 'meaning': 'дедушка'},
    '也许': {'pinyin': 'yěxǔ', 'meaning': 'возможно'},
    '页': {'pinyin': 'yè', 'meaning': 'страница'},
    '夜': {'pinyin': 'yè', 'meaning': 'ночь'},
    '叶子': {'pinyin': 'yèzi', 'meaning': 'лист'},
    '一': {'pinyin': 'yī', 'meaning': 'один'},
    '衣服': {'pinyin': 'yīfu', 'meaning': 'одежда'},
    '移动': {'pinyin': 'yídòng', 'meaning': 'двигать'},
    '一定': {'pinyin': 'yídìng', 'meaning': 'обязательно'},
    '一共': {'pinyin': 'yígòng', 'meaning': 'всего'},
    '一会儿': {'pinyin': 'yíhuìr', 'meaning': 'через минуту'},
    '一样': {'pinyin': 'yíyàng', 'meaning': 'одинаковый'},
    '以前': {'pinyin': 'yǐqián', 'meaning': 'раньше'},
    '一直': {'pinyin': 'yìzhí', 'meaning': 'все время'},
    '意见': {'pinyin': 'yìjiàn', 'meaning': 'мнение'},
    '艺术': {'pinyin': 'yìshù', 'meaning': 'искусство'},
    '因此': {'pinyin': 'yīncǐ', 'meaning': 'поэтому'},
    '饮料': {'pinyin': 'yǐnliào', 'meaning': 'напиток'},
    '因为': {'pinyin': 'yīnwèi', 'meaning': 'потому что'},
    '印象': {'pinyin': 'yìnxiàng', 'meaning': 'впечатление'},
    '引起': {'pinyin': 'yǐnqǐ', 'meaning': 'вызывать'},
    '音乐': {'pinyin': 'yīnyuè', 'meaning': 'музыка'},
    '银行': {'pinyin': 'yínháng', 'meaning': 'банк'},
    '应该': {'pinyin': 'yīnggāi', 'meaning': 'должен'},
    '赢': {'pinyin': 'yíng', 'meaning': 'выигрывать'},
    '硬': {'pinyin': 'yìng', 'meaning': 'твердый'},
    '影响': {'pinyin': 'yǐngxiǎng', 'meaning': 'влиять'},
    '英雄': {'pinyin': 'yīngxióng', 'meaning': 'герой'},
    '永远': {'pinyin': 'yǒngyuǎn', 'meaning': 'навсегда'},
    '勇敢': {'pinyin': 'yǒnggǎn', 'meaning': 'храбрый'},
    '用': {'pinyin': 'yòng', 'meaning': 'использовать'},
    '优点': {'pinyin': 'yōudiǎn', 'meaning': 'преимущество'},
    '优秀': {'pinyin': 'yōuxiù', 'meaning': 'выдающийся'},
    '友好': {'pinyin': 'yǒuhǎo', 'meaning': 'дружелюбный'},
    '友谊': {'pinyin': 'yǒuyì', 'meaning': 'дружба'},
    '有趣': {'pinyin': 'yǒuqù', 'meaning': 'интересный'},
    '邮局': {'pinyin': 'yóujú', 'meaning': 'почта'},
    '游戏': {'pinyin': 'yóuxì', 'meaning': 'игра'},
    '游泳': {'pinyin': 'yóuyǒng', 'meaning': 'плавать'},
    '尤其': {'pinyin': 'yóuqí', 'meaning': 'особенно'},
    '有': {'pinyin': 'yǒu', 'meaning': 'иметь'},
    '有名': {'pinyin': 'yǒumíng', 'meaning': 'известный'},
    '右边': {'pinyin': 'yòubiān', 'meaning': 'справа'},
    '鱼': {'pinyin': 'yú', 'meaning': 'рыба'},
    '娱乐': {'pinyin': 'yúlè', 'meaning': 'развлечение'},
    '愉快': {'pinyin': 'yúkuài', 'meaning': 'приятный'},
    '与': {'pinyin': 'yǔ', 'meaning': 'с'},
    '预习': {'pinyin': 'yùxí', 'meaning': 'готовиться к уроку'},
    '语言': {'pinyin': 'yǔyán', 'meaning': 'язык'},
    '约会': {'pinyin': 'yuēhuì', 'meaning': 'свидание'},
    '阅读': {'pinyin': 'yuèdú', 'meaning': 'читать'},
    '云': {'pinyin': 'yún', 'meaning': 'облако'},
    '允许': {'pinyin': 'yǔnxǔ', 'meaning': 'разрешать'},
    '运动': {'pinyin': 'yùndòng', 'meaning': 'спорт'},
    '运输': {'pinyin': 'yùnshū', 'meaning': 'транспортировать'},
    '再': {'pinyin': 'zài', 'meaning': 'снова'},
    '在': {'pinyin': 'zài', 'meaning': 'в'},
    '赞成': {'pinyin': 'zànchéng', 'meaning': 'соглашаться'},
    '脏': {'pinyin': 'zāng', 'meaning': 'грязный'},
    '早餐': {'pinyin': 'zǎocān', 'meaning': 'завтрак'},
    '早': {'pinyin': 'zǎo', 'meaning': 'рано'},
    '造成': {'pinyin': 'zàochéng', 'meaning': 'вызывать'},
    '责任': {'pinyin': 'zérèn', 'meaning': 'ответственность'},
    '增加': {'pinyin': 'zēngjiā', 'meaning': 'увеличивать'},
    '窄': {'pinyin': 'zhǎi', 'meaning': 'узкий'},
    '招聘': {'pinyin': 'zhāopìn', 'meaning': 'нанимать'},
    '照': {'pinyin': 'zhào', 'meaning': 'фотографировать'},
    '照顾': {'pinyin': 'zhàogù', 'meaning': 'заботиться'},
    '照片': {'pinyin': 'zhàopiàn', 'meaning': 'фотография'},
    '照相机': {'pinyin': 'zhàoxiàngjī', 'meaning': 'фотоаппарат'},
    '这': {'pinyin': 'zhè', 'meaning': 'этот'},
    '者': {'pinyin': 'zhě', 'meaning': 'суффикс для деятеля'},
    '折': {'pinyin': 'zhé', 'meaning': 'ломать'},
    '哲学': {'pinyin': 'zhéxué', 'meaning': 'философия'},
    '真': {'pinyin': 'zhēn', 'meaning': 'настоящий'},
    '真实': {'pinyin': 'zhēnshí', 'meaning': 'реальный'},
    '整齐': {'pinyin': 'zhěngqí', 'meaning': 'опрятный'},
    '正常': {'pinyin': 'zhèngcháng', 'meaning': 'нормальный'},
    '正好': {'pinyin': 'zhènghǎo', 'meaning': 'как раз'},
    '证明': {'pinyin': 'zhèngmíng', 'meaning': 'доказывать'},
    '政府': {'pinyin': 'zhèngfǔ', 'meaning': 'правительство'},
    '政治': {'pinyin': 'zhèngzhì', 'meaning': 'политика'},
    '正在': {'pinyin': 'zhèngzài', 'meaning': 'в процессе'},
    '挣': {'pinyin': 'zhèng', 'meaning': 'зарабатывать'},
    '整': {'pinyin': 'zhěng', 'meaning': 'целый'},
    '正确': {'pinyin': 'zhèngquè', 'meaning': 'правильный'},
    '之': {'pinyin': 'zhī', 'meaning': 'литературная частица'},
    '支持': {'pinyin': 'zhīchí', 'meaning': 'поддерживать'},
    '知识': {'pinyin': 'zhīshí', 'meaning': 'знание'},
    '值得': {'pinyin': 'zhídé', 'meaning': 'стоить'},
    '直接': {'pinyin': 'zhíjiē', 'meaning': 'прямой'},
    '职业': {'pinyin': 'zhíyè', 'meaning': 'профессия'},
    '植物': {'pinyin': 'zhíwù', 'meaning': 'растение'},
    '只': {'pinyin': 'zhǐ', 'meaning': 'только'},
    '指': {'pinyin': 'zhǐ', 'meaning': 'указывать'},
    '制造': {'pinyin': 'zhìzào', 'meaning': 'производить'},
    '至少': {'pinyin': 'zhìshǎo', 'meaning': 'по крайней мере'},
    '质量': {'pinyin': 'zhìliàng', 'meaning': 'качество'},
    '治疗': {'pinyin': 'zhìliáo', 'meaning': 'лечить'},
    '中国': {'pinyin': 'Zhōngguó', 'meaning': 'Китай'},
    '中间': {'pinyin': 'zhōngjiān', 'meaning': 'середина'},
    '终于': {'pinyin': 'zhōngyú', 'meaning': 'наконец'},
    '种': {'pinyin': 'zhǒng', 'meaning': 'вид; тип'},
    '重点': {'pinyin': 'zhòngdiǎn', 'meaning': 'основной пункт'},
    '重要': {'pinyin': 'zhòngyào', 'meaning': 'важный'},
    '周': {'pinyin': 'zhōu', 'meaning': 'неделя'},
    '周末': {'pinyin': 'zhōumò', 'meaning': 'выходные'},
    '州': {'pinyin': 'zhōu', 'meaning': 'штат'},
    '猪': {'pinyin': 'zhū', 'meaning': 'свинья'},
    '主': {'pinyin': 'zhǔ', 'meaning': 'главный'},
    '主动': {'pinyin': 'zhǔdòng', 'meaning': 'инициативный'},
    '主意': {'pinyin': 'zhǔyi', 'meaning': 'идея'},
    '注意': {'pinyin': 'zhùyì', 'meaning': 'обращать внимание'},
    '著名': {'pinyin': 'zhùmíng', 'meaning': 'знаменитый'},
    '祝贺': {'pinyin': 'zhùhè', 'meaning': 'поздравлять'},
    '专门': {'pinyin': 'zhuānmén', 'meaning': 'специально'},
    '专业': {'pinyin': 'zhuānyè', 'meaning': 'специальность'},
    '砖': {'pinyin': 'zhuān', 'meaning': 'кирпич'},
    '赚': {'pinyin': 'zhuàn', 'meaning': 'зарабатывать'},
    '转': {'pinyin': 'zhuǎn', 'meaning': 'поворачивать'},
    '撞': {'pinyin': 'zhuàng', 'meaning': 'сталкиваться'},
    '准备': {'pinyin': 'zhǔnbèi', 'meaning': 'готовиться'},
    '准确': {'pinyin': 'zhǔnquè', 'meaning': 'точный'},
    '追': {'pinyin': 'zhuī', 'meaning': 'преследовать'},
    '嘴': {'pinyin': 'zuǐ', 'meaning': 'рот'},
    '最': {'pinyin': 'zuì', 'meaning': 'самый'},
    '最近': {'pinyin': 'zuìjìn', 'meaning': 'недавно'},
    '尊敬': {'pinyin': 'zūnjìng', 'meaning': 'уважать'},
    '昨天': {'pinyin': 'zuótiān', 'meaning': 'вчера'},
    '左边': {'pinyin': 'zuǒbiān', 'meaning': 'слева'},
    '坐': {'pinyin': 'zuò', 'meaning': 'сидеть'},
    '做': {'pinyin': 'zuò', 'meaning': 'делать'},
    '作业': {'pinyin': 'zuòyè', 'meaning': 'домашняя работа'},
}
