HSK1_CHARACTERS = {
    '爱': {'pinyin': 'ài', 'meaning': 'любовь; любить'},
    '八': {'pinyin': 'bā', 'meaning': 'восемь'},
    '爸爸': {'pinyin': 'bàba', 'meaning': 'папа'},
    '杯子': {'pinyin': 'bēizi', 'meaning': 'стакан; чашка'},
    '北京': {'pinyin': 'Běijīng', 'meaning': 'Пекин'},
    '本': {'pinyin': 'běn', 'meaning': 'книга; тетрадь'},
    '不': {'pinyin': 'bù', 'meaning': 'не; нет'},
    '不客气': {'pinyin': 'bù kèqi', 'meaning': 'не за что; пожалуйста'},
    '菜': {'pinyin': 'cài', 'meaning': 'блюдо; овощи'},
    '茶': {'pinyin': 'chá', 'meaning': 'чай'},
    '吃': {'pinyin': 'chī', 'meaning': 'есть'},
    '车': {'pinyin': 'chē', 'meaning': 'машина'},
    '出租车': {'pinyin': 'chūzūchē', 'meaning': 'такси'},
    '打电话': {'pinyin': 'dǎ diànhuà', 'meaning': 'звонить по телефону'},
    '大': {'pinyin': 'dà', 'meaning': 'большой'},
    '的': {'pinyin': 'de', 'meaning': '(притяжательная частица)'},
    '点': {'pinyin': 'diǎn', 'meaning': 'точка; час'},
    '电脑': {'pinyin': 'diànnǎo', 'meaning': 'компьютер'},
    '电视': {'pinyin': 'diànshì', 'meaning': 'телевизор'},
    '电影': {'pinyin': 'diànyǐng', 'meaning': 'фильм'},
    '东西': {'pinyin': 'dōngxī', 'meaning': 'вещь'},
    '都': {'pinyin': 'dōu', 'meaning': 'все; оба'},
    '读': {'pinyin': 'dú', 'meaning': 'читать'},
    '对不起': {'pinyin': 'duìbuqǐ', 'meaning': 'извините'},
    '多': {'pinyin': 'duō', 'meaning': 'много'},
    '多少': {'pinyin': 'duōshǎo', 'meaning': 'сколько'},
    '二': {'pinyin': 'èr', 'meaning': 'два'},
    '饭': {'pinyin': 'fàn', 'meaning': 'еда; рис'},
    '饭店': {'pinyin': 'fàndiàn', 'meaning': 'ресторан'},
    '飞机': {'pinyin': 'fēijī', 'meaning': 'самолёт'},
    '分钟': {'pinyin': 'fēnzhōng', 'meaning': 'минута'},
    '高兴': {'pinyin': 'gāoxìng', 'meaning': 'рад; счастливый'},
    '个': {'pinyin': 'gè', 'meaning': '(счётное слово)'},
    '工作': {'pinyin': 'gōngzuò', 'meaning': 'работа; работать'},
    '狗': {'pinyin': 'gǒu', 'meaning': 'собака'},
    '汉语': {'pinyin': 'Hànyǔ', 'meaning': 'китайский язык'},
    '好': {'pinyin': 'hǎo', 'meaning': 'хороший'},
    '号': {'pinyin': 'hào', 'meaning': 'номер; число'},
    '喝': {'pinyin': 'hē', 'meaning': 'пить'},
    '和': {'pinyin': 'hé', 'meaning': 'и; с'},
    '很': {'pinyin': 'hěn', 'meaning': 'очень'},
    '后面': {'pinyin': 'hòumiàn', 'meaning': 'сзади'},
    '回': {'pinyin': 'huí', 'meaning': 'возвращаться'},
    '会': {'pinyin': 'huì', 'meaning': 'уметь; мочь'},
    '火车站': {'pinyin': 'huǒchēzhàn', 'meaning': 'железнодорожный вокзал'},
    '几': {'pinyin': 'jǐ', 'meaning': 'сколько; несколько'},
    '家': {'pinyin': 'jiā', 'meaning': 'дом; семья'},
    '叫': {'pinyin': 'jiào', 'meaning': 'звать; называться'},
    '今天': {'pinyin': 'jīntiān', 'meaning': 'сегодня'},
    '九': {'pinyin': 'jiǔ', 'meaning': 'девять'},
    '开': {'pinyin': 'kāi', 'meaning': 'открывать; начинать'},
    '看': {'pinyin': 'kàn', 'meaning': 'смотреть'},
    '看见': {'pinyin': 'kànjiàn', 'meaning': 'увидеть'},
    '块': {'pinyin': 'kuài', 'meaning': '(счётное слово); кусок'},
    '来': {'pinyin': 'lái', 'meaning': 'приходить'},
    '老师': {'pinyin': 'lǎoshī', 'meaning': 'учитель'},
    '了': {'pinyin': 'le', 'meaning': '(частица завершения)'},
    '冷': {'pinyin': 'lěng', 'meaning': 'холодный'},
    '里': {'pinyin': 'lǐ', 'meaning': 'внутри; ли (мера длины)'},
    '零': {'pinyin': 'líng', 'meaning': 'ноль'},
    '六': {'pinyin': 'liù', 'meaning': 'шесть'},
    '妈妈': {'pinyin': 'māma', 'meaning': 'мама'},
    '吗': {'pinyin': 'ma', 'meaning': '(вопросительная частица)'},
    '买': {'pinyin': 'mǎi', 'meaning': 'покупать'},
    '猫': {'pinyin': 'māo', 'meaning': 'кошка'},
    '没': {'pinyin': 'méi', 'meaning': 'не (отрицание)'},
    '没有': {'pinyin': 'méiyǒu', 'meaning': 'нет; не иметь'},
    '米饭': {'pinyin': 'mǐfàn', 'meaning': 'рис (приготовленный)'},
    '名字': {'pinyin': 'míngzi', 'meaning': 'имя'},
    '明天': {'pinyin': 'míngtiān', 'meaning': 'завтра'},
    '哪': {'pinyin': 'nǎ', 'meaning': 'какой; где'},
    '哪儿': {'pinyin': 'nǎr', 'meaning': 'где'},
    '那': {'pinyin': 'nà', 'meaning': 'тот'},
    '那儿': {'pinyin': 'nàr', 'meaning': 'там'},
    '男': {'pinyin': 'nán', 'meaning': 'мужской; мужчина'},
    '你': {'pinyin': 'nǐ', 'meaning': 'ты'},
    '您': {'pinyin': 'nín', 'meaning': 'вы (вежливо)'},
    '年': {'pinyin': 'nián', 'meaning': 'год'},
    '女': {'pinyin': 'nǚ', 'meaning': 'женский; женщина'},
    '朋友': {'pinyin': 'péngyou', 'meaning': 'друг'},
    '苹果': {'pinyin': 'píngguǒ', 'meaning': 'яблоко'},
    '七': {'pinyin': 'qī', 'meaning': 'семь'},
    '钱': {'pinyin': 'qián', 'meaning': 'деньги'},
    '前面': {'pinyin': 'qiánmiàn', 'meaning': 'спереди'},
    '请': {'pinyin': 'qǐng', 'meaning': 'пожалуйста; приглашать'},
    '去': {'pinyin': 'qù', 'meaning': 'идти'},
    '热': {'pinyin': 'rè', 'meaning': 'горячий'},
    '人': {'pinyin': 'rén', 'meaning': 'человек'},
    '认识': {'pinyin': 'rènshi', 'meaning': 'знать; познакомиться'},
    '日': {'pinyin': 'rì', 'meaning': 'день; солнце'},
    '三': {'pinyin': 'sān', 'meaning': 'три'},
    '商店': {'pinyin': 'shāngdiàn', 'meaning': 'магазин'},
    '上': {'pinyin': 'shàng', 'meaning': 'наверху; подниматься'},
    '上午': {'pinyin': 'shàngwǔ', 'meaning': 'утро'},
    '少': {'pinyin': 'shǎo', 'meaning': 'мало'},
    '谁': {'pinyin': 'shéi', 'meaning': 'кто'},
    '什么': {'pinyin': 'shénme', 'meaning': 'что'},
    '十': {'pinyin': 'shí', 'meaning': 'десять'},
    '时候': {'pinyin': 'shíhou', 'meaning': 'время'},
    '是': {'pinyin': 'shì', 'meaning': 'быть'},
    '书': {'pinyin': 'shū', 'meaning': 'книга'},
    '水': {'pinyin': 'shuǐ', 'meaning': 'вода'},
    '水果': {'pinyin': 'shuǐguǒ', 'meaning': 'фрукты'},
    '睡觉': {'pinyin': 'shuì jiào', 'meaning': 'спать'},
    '说': {'pinyin': 'shuō', 'meaning': 'говорить'},
    '四': {'pinyin': 'sì', 'meaning': 'четыре'},
    '岁': {'pinyin': 'suì', 'meaning': 'год (возраст)'},
    '他': {'pinyin': 'tā', 'meaning': 'он'},
    '她': {'pinyin': 'tā', 'meaning': 'она'},
    '太': {'pinyin': 'tài', 'meaning': 'слишком'},
    '天气': {'pinyin': 'tiānqì', 'meaning': 'погода'},
    '听': {'pinyin': 'tīng', 'meaning': 'слушать'},
    '同学': {'pinyin': 'tóngxué', 'meaning': 'одноклассник'},
    '喂': {'pinyin': 'wèi', 'meaning': 'алло (по телефону)'},
    '我': {'pinyin': 'wǒ', 'meaning': 'я'},
    '我们': {'pinyin': 'wǒmen', 'meaning': 'мы'},
    '五': {'pinyin': 'wǔ', 'meaning': 'пять'},
    '下': {'pinyin': 'xià', 'meaning': 'внизу; спускаться'},
    '下午': {'pinyin': 'xiàwǔ', 'meaning': 'полдень'},
    '下雨': {'pinyin': 'xià yǔ', 'meaning': 'идёт дождь'},
    '先生': {'pinyin': 'xiānsheng', 'meaning': 'господин'},
    '现在': {'pinyin': 'xiànzài', 'meaning': 'сейчас'},
    '想': {'pinyin': 'xiǎng', 'meaning': 'думать; хотеть'},
    '小': {'pinyin': 'xiǎo', 'meaning': 'маленький'},
    '小姐': {'pinyin': 'xiǎojiě', 'meaning': 'мисс; девушка'},
    '些': {'pinyin': 'xiē', 'meaning': 'некоторые'},
    '写': {'pinyin': 'xiě', 'meaning': 'писать'},
    '谢谢': {'pinyin': 'xièxie', 'meaning': 'спасибо'},
    '星期': {'pinyin': 'xīngqī', 'meaning': 'неделя'},
    '学生': {'pinyin': 'xuésheng', 'meaning': 'студент'},
    '学习': {'pinyin': 'xuéxí', 'meaning': 'учиться'},
    '学校': {'pinyin': 'xuéxiào', 'meaning': 'школа'},
    '一': {'pinyin': 'yī', 'meaning': 'один'},
    '衣服': {'pinyin': 'yīfu', 'meaning': 'одежда'},
    '医生': {'pinyin': 'yīshēng', 'meaning': 'врач'},
    '医院': {'pinyin': 'yīyuàn', 'meaning': 'больница'},
    '椅子': {'pinyin': 'yǐzi', 'meaning': 'стул'},
    '有': {'pinyin': 'yǒu', 'meaning': 'иметь'},
    '月': {'pinyin': 'yuè', 'meaning': 'месяц; луна'},
    '再见': {'pinyin': 'zàijiàn', 'meaning': 'до свидания'},
    '在': {'pinyin': 'zài', 'meaning': 'в; на'},
    '早上': {'pinyin': 'zǎoshang', 'meaning': 'утро (ранее)'},
    '这': {'pinyin': 'zhè', 'meaning': 'этот'},
    '这儿': {'pinyin': 'zhèr', 'meaning': 'здесь'},
    '中国': {'pinyin': 'Zhōngguó', 'meaning': 'Китай'},
    '中午': {'pinyin': 'zhōngwǔ', 'meaning': 'полдень'},
    '住': {'pinyin': 'zhù', 'meaning': 'жить'},
    '桌子': {'pinyin': 'zhuōzi', 'meaning': 'стол'},
    '字': {'pinyin': 'zì', 'meaning': 'иероглиф; слово'},
    '昨天': {'pinyin': 'zuótiān', 'meaning': 'вчера'},
    '坐': {'pinyin': 'zuò', 'meaning': 'сидеть'},
}