HSK1_CHARACTERS = {
    '爱': {'pinyin': 'ài', 'meaning': 'любить; любовь'},
    '爱好': {'pinyin': 'àihào', 'meaning': 'хобби'},
    '八': {'pinyin': 'bā', 'meaning': '8, восемь'},
    '爸爸': {'pinyin': 'bàba', 'meaning': 'папа, отец'},
    '吧': {'pinyin': 'ba', 'meaning': 'частица, выражает предложение или предположение'},
    '白': {'pinyin': 'bái', 'meaning': 'белый'},
    '白天': {'pinyin': 'báitiān', 'meaning': 'дневное время'},
    '百': {'pinyin': 'bǎi', 'meaning': '100, сто'},
    '班': {'pinyin': 'bān', 'meaning': 'класс, команда'},
    '半': {'pinyin': 'bàn', 'meaning': 'половина'},
    '半年': {'pinyin': 'bànnián', 'meaning': 'полгода'},
    '半天': {'pinyin': 'bàntiān', 'meaning': 'полдня'},
    '帮': {'pinyin': 'bāng', 'meaning': 'помогать'},
    '帮忙': {'pinyin': 'bāngmáng', 'meaning': 'помогать'},
    '包': {'pinyin': 'bāo', 'meaning': 'заворачивать; сумка'},
    '包子': {'pinyin': 'bāozi', 'meaning': 'паровые пирожки'},
    '杯': {'pinyin': 'bēi', 'meaning': 'стакан; рюмка (сч. слово)'},
    '杯子': {'pinyin': 'bēizi', 'meaning': 'стакан, чашка'},
    '北': {'pinyin': 'běi', 'meaning': 'север'},
    '北边': {'pinyin': 'běibian', 'meaning': 'северная сторона'},
    '北京': {'pinyin': 'Běijīng', 'meaning': 'Пекин'},
    '本': {'pinyin': 'běn', 'meaning': 'сч. слово для книг и тетрадей'},
    '本子': {'pinyin': 'běnzi', 'meaning': 'тетрадь, блокнот'},
    '比': {'pinyin': 'bǐ', 'meaning': 'сравнивать; по сравнению с'},
    '别': {'pinyin': 'bié', 'meaning': 'не надо; другой'},
    '别的': {'pinyin': 'biéde', 'meaning': 'другой, иной'},
    '别人': {'pinyin': 'biérén', 'meaning': 'другой человек; другие'},
    '病': {'pinyin': 'bìng', 'meaning': 'болеть; болезнь'},
    '病人': {'pinyin': 'bìngrén', 'meaning': 'пациент, больной'},
    '不大': {'pinyin': 'bú dà', 'meaning': 'небольшой; не очень; редко'},
    '不对': {'pinyin': 'búduì', 'meaning': 'неверно, неправильный'},
    '不客气': {'pinyin': 'bú kèqi', 'meaning': 'не стоит благодарности; пожалуйста'},
    '不用': {'pinyin': 'búyòng', 'meaning': 'не нужно'},
    '不': {'pinyin': 'bù', 'meaning': 'нет, не'},
    '菜': {'pinyin': 'cài', 'meaning': 'блюдо, овощи'},
    '茶': {'pinyin': 'chá', 'meaning': 'чай'},
    '差': {'pinyin': 'chà', 'meaning': 'без (напр., без десяти); отличаться'},
    '常': {'pinyin': 'cháng', 'meaning': 'часто'},
    '常常': {'pinyin': 'chángcháng', 'meaning': 'часто, обычно'},
    '唱': {'pinyin': 'chàng', 'meaning': 'петь'},
    '唱歌': {'pinyin': 'chànggē', 'meaning': 'петь (песню)'},
    '车': {'pinyin': 'chē', 'meaning': 'транспортное средство; машина'},
    '车票': {'pinyin': 'chēpiào', 'meaning': 'проездной билет'},
    '车上': {'pinyin': 'chē shang', 'meaning': 'в автобусе, в машине'},
    '车站': {'pinyin': 'chēzhàn', 'meaning': 'автобусная остановка; вокзал'},
    '吃': {'pinyin': 'chī', 'meaning': 'есть, кушать'},
    '吃饭': {'pinyin': 'chīfàn', 'meaning': 'есть, кушать'},
    '出': {'pinyin': 'chū', 'meaning': 'выходить наружу'},
    '出来': {'pinyin': 'chūlái', 'meaning': 'выходить; появляться'},
    '出去': {'pinyin': 'chūqù', 'meaning': 'выходить'},
    '穿': {'pinyin': 'chuān', 'meaning': 'носить, надевать (одежду)'},
    '床': {'pinyin': 'chuáng', 'meaning': 'кровать'},
    '次': {'pinyin': 'cì', 'meaning': 'раз (счётное слово)'},
    '从': {'pinyin': 'cóng', 'meaning': 'из, с..., через'},
    '错': {'pinyin': 'cuò', 'meaning': 'ошибка, ошибаться'},
    '打': {'pinyin': 'dǎ', 'meaning': 'бить, ударять; играть; звонить'},
    '打车': {'pinyin': 'dǎchē', 'meaning': 'брать такси'},
    '打电话': {'pinyin': 'dǎ diànhuà', 'meaning': 'звонить по телефону'},
    '打开': {'pinyin': 'dǎkāi', 'meaning': 'открывать'},
    '打球': {'pinyin': 'dǎqiú', 'meaning': 'играть в мяч'},
    '大': {'pinyin': 'dà', 'meaning': 'большой, старший'},
    '大学': {'pinyin': 'dàxué', 'meaning': 'университет'},
    '大学生': {'pinyin': 'dàxuéshēng', 'meaning': 'студент'},
    '到': {'pinyin': 'dào', 'meaning': 'достигать, добираться'},
    '得到': {'pinyin': 'dédào', 'meaning': 'получать, добиваться'},
    '地': {'pinyin': 'dì', 'meaning': 'страна; местность; земля'},
    '的': {'pinyin': 'de', 'meaning': 'притяжательная частица'},
    '等': {'pinyin': 'děng', 'meaning': 'ждать'},
    '地点': {'pinyin': 'dìdiǎn', 'meaning': 'место, пункт'},
    '地方': {'pinyin': 'dìfang', 'meaning': 'место, местоположение'},
    '地上': {'pinyin': 'dìshang', 'meaning': 'на земле; на полу'},
    '地图': {'pinyin': 'dìtú', 'meaning': 'карта'},
    '弟弟': {'pinyin': 'dìdi', 'meaning': 'младший брат'},
    '第': {'pinyin': 'dì', 'meaning': 'показатель порядкового числительного'},
    '点': {'pinyin': 'diǎn', 'meaning': 'час; точка; немного'},
    '电': {'pinyin': 'diàn', 'meaning': 'электричество'},
    '电话': {'pinyin': 'diànhuà', 'meaning': 'телефон; звонок'},
    '电脑': {'pinyin': 'diànnǎo', 'meaning': 'компьютер'},
    '电视': {'pinyin': 'diànshì', 'meaning': 'телевизор'},
    '电视机': {'pinyin': 'diànshìjī', 'meaning': 'телевизор (аппарат)'},
    '电影': {'pinyin': 'diànyǐng', 'meaning': 'фильм, кино'},
    '电影院': {'pinyin': 'diànyǐngyuàn', 'meaning': 'кинотеатр'},
    '东': {'pinyin': 'dōng', 'meaning': 'восток, восточный'},
    '东边': {'pinyin': 'dōngbian', 'meaning': 'восточная сторона'},
    '东西': {'pinyin': 'dōngxi', 'meaning': 'вещь, предмет'},
    '动': {'pinyin': 'dòng', 'meaning': 'двигаться, действовать'},
    '动作': {'pinyin': 'dòngzuò', 'meaning': 'движение, действие'},
    '都': {'pinyin': 'dōu', 'meaning': 'все (наречие)'},
    '读': {'pinyin': 'dú', 'meaning': 'читать, учиться'},
    '读书': {'pinyin': 'dúshū', 'meaning': 'читать книгу; ходить в школу'},
    '对': {'pinyin': 'duì', 'meaning': 'правильный, верный'},
    '对不起': {'pinyin': 'duìbuqǐ', 'meaning': 'извините, подводить'},
    '多': {'pinyin': 'duō', 'meaning': 'многий, многочисленный'},
    '多少': {'pinyin': 'duōshǎo', 'meaning': 'сколько?'},
    '饿': {'pinyin': 'è', 'meaning': 'голодный'},
    '儿子': {'pinyin': 'érzi', 'meaning': 'сын'},
    '二': {'pinyin': 'èr', 'meaning': '2, два'},
    '饭': {'pinyin': 'fàn', 'meaning': 'еда; вареный рис'},
    '饭店': {'pinyin': 'fàndiàn', 'meaning': 'кафе, ресторан'},
    '房间': {'pinyin': 'fángjiān', 'meaning': 'комната'},
    '房子': {'pinyin': 'fángzi', 'meaning': 'дом, здание'},
    '放': {'pinyin': 'fàng', 'meaning': 'класть, положить'},
    '放假': {'pinyin': 'fàngjià', 'meaning': 'отпуск; распускать на каникулы'},
    '放学': {'pinyin': 'fàngxué', 'meaning': 'заканчивать занятия'},
    '飞': {'pinyin': 'fēi', 'meaning': 'летать'},
    '飞机': {'pinyin': 'fēijī', 'meaning': 'самолет'},
    '非常': {'pinyin': 'fēicháng', 'meaning': 'очень, крайне'},
    '分': {'pinyin': 'fēn', 'meaning': 'минута; процент; делить'},
    '风': {'pinyin': 'fēng', 'meaning': 'ветер'},
    '干': {'pinyin': 'gàn', 'meaning': 'работать, трудиться'},
    '干净': {'pinyin': 'gānjìng', 'meaning': 'чистый'},
    '干什么': {'pinyin': 'gàn shénme', 'meaning': 'зачем, для чего'},
    '高': {'pinyin': 'gāo', 'meaning': 'высокий'},
    '高兴': {'pinyin': 'gāoxìng', 'meaning': 'радостный'},
    '告诉': {'pinyin': 'gàosu', 'meaning': 'сказать, проинформировать'},
    '哥哥': {'pinyin': 'gēge', 'meaning': 'старший брат'},
    '歌': {'pinyin': 'gē', 'meaning': 'песня; петь'},
    '个': {'pinyin': 'gè', 'meaning': 'универсальное счетное слово'},
    '给': {'pinyin': 'gěi', 'meaning': 'давать; для (предлог)'},
    '跟': {'pinyin': 'gēn', 'meaning': 'с; следовать за'},
    '工人': {'pinyin': 'gōngrén', 'meaning': 'рабочий'},
    '工作': {'pinyin': 'gōngzuò', 'meaning': 'работать; работа'},
    '关': {'pinyin': 'guān', 'meaning': 'закрывать; выключать'},
    '关上': {'pinyin': 'guānshàng', 'meaning': 'закрыть'},
    '贵': {'pinyin': 'guì', 'meaning': 'дорогой; уважаемый'},
    '国': {'pinyin': 'guó', 'meaning': 'государство, страна'},
    '国家': {'pinyin': 'guójiā', 'meaning': 'страна'},
    '国外': {'pinyin': 'guówài', 'meaning': 'заграница, за рубежом'},
    '过': {'pinyin': 'guò', 'meaning': 'проходить; переходить; отмечать'},
    '还': {'pinyin': 'huán', 'meaning': 'возвращаться домой'},
    '还是': {'pinyin': 'háishi', 'meaning': 'все еще; или'},
    '还有': {'pinyin': 'hái yǒu', 'meaning': 'еще есть; а также'},
    '孩子': {'pinyin': 'háizi', 'meaning': 'ребенок'},
    '汉语': {'pinyin': 'hànyǔ', 'meaning': 'китайский язык'},
    '汉字': {'pinyin': 'hànzì', 'meaning': 'китайский иероглиф'},
    '好': {'pinyin': 'hǎo', 'meaning': 'хороший; добрый; здоровый'},
    '好吃': {'pinyin': 'hǎochī', 'meaning': 'вкусный'},
    '好看': {'pinyin': 'hǎokàn', 'meaning': 'красивый; хорошо выглядеть'},
    '好听': {'pinyin': 'hǎotīng', 'meaning': 'приятный для слуха'},
    '好玩儿': {'pinyin': 'hǎowánr', 'meaning': 'забавный, интересный'},
    '号': {'pinyin': 'hào', 'meaning': 'число, день (в датах)'},
    '喝': {'pinyin': 'hē', 'meaning': 'пить'},
    '和': {'pinyin': 'hé', 'meaning': 'и (союз); с'},
    '很': {'pinyin': 'hěn', 'meaning': 'очень'},
    '后': {'pinyin': 'hòu', 'meaning': 'после; сзади'},
    '后边': {'pinyin': 'hòubian', 'meaning': 'за, позади'},
    '后天': {'pinyin': 'hòutiān', 'meaning': 'послезавтра'},
    '花': {'pinyin': 'huā', 'meaning': 'цветок'},
    '话': {'pinyin': 'huà', 'meaning': 'слова, речь, фраза'},
    '坏': {'pinyin': 'huài', 'meaning': 'плохой; ломаться'},
    '回': {'pinyin': 'huí', 'meaning': 'возвращаться домой'},
    '回答': {'pinyin': 'huídá', 'meaning': 'отвечать, ответ'},
    '回到': {'pinyin': 'huídào', 'meaning': 'вернуться (к чему-либо)'},
    '回家': {'pinyin': 'huíjiā', 'meaning': 'возвращаться домой'},
    '回来': {'pinyin': 'huílái', 'meaning': 'возвращаться, приходить обратно'},
    '回去': {'pinyin': 'huíqù', 'meaning': 'возвращаться (от говорящего)'},
    '会': {'pinyin': 'huì', 'meaning': 'мочь, уметь; собрание'},
    '火车': {'pinyin': 'huǒchē', 'meaning': 'поезд'},
    '机场': {'pinyin': 'jīchǎng', 'meaning': 'аэропорт'},
    '机票': {'pinyin': 'jīpiào', 'meaning': 'авиабилет'},
    '鸡蛋': {'pinyin': 'jīdàn', 'meaning': 'куриное яйцо'},
    '几': {'pinyin': 'jǐ', 'meaning': 'несколько; сколько?'},
    '记': {'pinyin': 'jì', 'meaning': 'помнить; записывать'},
    '记得': {'pinyin': 'jìde', 'meaning': 'помнить'},
    '记住': {'pinyin': 'jìzhu', 'meaning': 'запоминать'},
    '家': {'pinyin': 'jiā', 'meaning': 'семья; сч. слово для магазинов'},
    '家里': {'pinyin': 'jiālǐ', 'meaning': 'дома, внутри'},
    '家人': {'pinyin': 'jiārén', 'meaning': 'член семьи'},
    '间': {'pinyin': 'jiān', 'meaning': 'между; комната (послелог и сч. слово)'},
    '见': {'pinyin': 'jiàn', 'meaning': 'видеть; встречаться'},
    '见面': {'pinyin': 'jiànmiàn', 'meaning': 'увидеться, встретиться'},
    '教': {'pinyin': 'jiāo', 'meaning': 'обучать, учить'},
    '叫': {'pinyin': 'jiào', 'meaning': 'кричать; называться; звать'},
    '教学楼': {'pinyin': 'jiàoxuélóu', 'meaning': 'учебный корпус'},
    '姐姐': {'pinyin': 'jiějie', 'meaning': 'старшая сестра'},
    '介绍': {'pinyin': 'jièshào', 'meaning': 'знакомить; представлять'},
    '今年': {'pinyin': 'jīnnián', 'meaning': 'этот год'},
    '今天': {'pinyin': 'jīntiān', 'meaning': 'сегодня'},
    '进': {'pinyin': 'jìn', 'meaning': 'входить'},
    '进来': {'pinyin': 'jìnlái', 'meaning': 'входить, заходить'},
    '进去': {'pinyin': 'jìnqù', 'meaning': 'входить'},
    '九': {'pinyin': 'jiǔ', 'meaning': '9, девять'},
    '就': {'pinyin': 'jiù', 'meaning': 'именно; как раз; сразу же (наречие)'},
    '觉得': {'pinyin': 'juéde', 'meaning': 'думать; считать; чувствовать'},
    '开': {'pinyin': 'kāi', 'meaning': 'открывать; начинать; водить'},
    '开车': {'pinyin': 'kāichē', 'meaning': 'водить машину'},
    '开会': {'pinyin': 'kāihuì', 'meaning': 'проводить собрание'},
    '开玩笑': {'pinyin': 'kāiwánxiào', 'meaning': 'шутить'},
    '看': {'pinyin': 'kàn', 'meaning': 'смотреть; читать'},
    '看病': {'pinyin': 'kànbìng', 'meaning': 'обращаться к врачу'},
    '看到': {'pinyin': 'kàndào', 'meaning': 'увидеть'},
    '看见': {'pinyin': 'kànjiàn', 'meaning': 'видеть, увидеть'},
    '考': {'pinyin': 'kǎo', 'meaning': 'экзаменовать; сдавать экзамен'},
    '考试': {'pinyin': 'kǎoshì', 'meaning': 'экзамен'},
    '渴': {'pinyin': 'kě', 'meaning': 'испытывать жажду'},
    '课': {'pinyin': 'kè', 'meaning': 'урок, дисциплина'},
    '课本': {'pinyin': 'kèběn', 'meaning': 'учебник'},
    '课文': {'pinyin': 'kèwén', 'meaning': '(учебный) текст'},
    '口': {'pinyin': 'kǒu', 'meaning': 'рот; сч. слово для людей'},
    '块': {'pinyin': 'kuài', 'meaning': 'кусок; сч. слово; денежная единица'},
    '快': {'pinyin': 'kuài', 'meaning': 'быстрый'},
    '来': {'pinyin': 'lái', 'meaning': 'приходить, прибывать'},
    '来到': {'pinyin': 'láidào', 'meaning': 'приходить, прибывать'},
    '老': {'pinyin': 'lǎo', 'meaning': 'старый; прежний; опытный'},
    '老人': {'pinyin': 'lǎorén', 'meaning': 'пожилой человек'},
    '老师': {'pinyin': 'lǎoshī', 'meaning': 'учитель'},
    '了': {'pinyin': 'le', 'meaning': 'частица завершения или смены ситуации'},
    '累': {'pinyin': 'lèi', 'meaning': 'уставший, уставать'},
    '冷': {'pinyin': 'lěng', 'meaning': 'холодный'},
    '里': {'pinyin': 'lǐ', 'meaning': 'внутри, в'},
    '里边': {'pinyin': 'lǐbian', 'meaning': 'внутри; внутренняя сторона'},
    '两': {'pinyin': 'liǎng', 'meaning': 'два, оба'},
    '零': {'pinyin': 'líng', 'meaning': 'ноль'},
    '六': {'pinyin': 'liù', 'meaning': '6, шесть'},
    '楼': {'pinyin': 'lóu', 'meaning': 'многоэтажный дом; этаж'},
    '楼上': {'pinyin': 'lóushàng', 'meaning': 'верхний этаж'},
    '楼下': {'pinyin': 'lóu xià', 'meaning': 'нижний этаж'},
    '路': {'pinyin': 'lù', 'meaning': 'дорога, путь'},
    '路口': {'pinyin': 'lùkǒu', 'meaning': 'перекрёсток'},
    '路上': {'pinyin': 'lùshang', 'meaning': 'в пути, в дороге'},
    '妈妈': {'pinyin': 'māma', 'meaning': 'мама, мать'},
    '马路': {'pinyin': 'mǎlù', 'meaning': 'дорога, улица'},
    '马上': {'pinyin': 'mǎshàng', 'meaning': 'сразу, сейчас же'},
    '吗': {'pinyin': 'ma', 'meaning': 'конечная вопросительная частица'},
    '买': {'pinyin': 'mǎi', 'meaning': 'купить, покупать'},
    '慢': {'pinyin': 'màn', 'meaning': 'медленный'},
    '忙': {'pinyin': 'máng', 'meaning': 'занятой'},
    '毛': {'pinyin': 'máo', 'meaning': 'мао (денежная единица)'},
    '没': {'pinyin': 'méi', 'meaning': 'не; не иметь'},
    '没关系': {'pinyin': 'méi guānxi', 'meaning': 'ничего страшного'},
    '没什么': {'pinyin': 'méishénme', 'meaning': 'не имеет значения; пустяки'},
    '没事儿': {'pinyin': 'méishìr', 'meaning': 'ничего страшного; всё нормально'},
    '没有': {'pinyin': 'méiyǒu', 'meaning': 'нет; отсутствует'},
    '妹妹': {'pinyin': 'mèimei', 'meaning': 'младшая сестра'},
    '门': {'pinyin': 'mén', 'meaning': 'дверь, ворота'},
    '门口': {'pinyin': 'ménkǒu', 'meaning': 'дверь, ворота (вход)'},
    '门票': {'pinyin': 'ménpiào', 'meaning': 'входной билет'},
    '们': {'pinyin': 'men', 'meaning': 'суффикс множественного числа'},
    '米饭': {'pinyin': 'mǐfàn', 'meaning': 'рис (вареный)'},
    '面包': {'pinyin': 'miànbāo', 'meaning': 'хлеб'},
    '面条儿': {'pinyin': 'miàntiáor', 'meaning': 'лапша'},
    '名字': {'pinyin': 'míngzi', 'meaning': 'имя'},
    '明白': {'pinyin': 'míngbai', 'meaning': 'ясно, понимать'},
    '明年': {'pinyin': 'míngnián', 'meaning': 'будущий год'},
    '明天': {'pinyin': 'míngtiān', 'meaning': 'завтра'},
    '拿': {'pinyin': 'ná', 'meaning': 'держать, брать, хватать'},
    '哪': {'pinyin': 'nǎ', 'meaning': 'какой?, который?'},
    '哪里': {'pinyin': 'nǎlǐ', 'meaning': 'ну что Вы (скромный ответ)'},
    '哪儿': {'pinyin': 'nǎr', 'meaning': 'где? куда?'},
    '哪些': {'pinyin': 'nǎxiē', 'meaning': 'какой, который'},
    '那': {'pinyin': 'nà', 'meaning': 'тот, этот'},
    '那边': {'pinyin': 'nàbiān', 'meaning': 'там, туда'},
    '那里': {'pinyin': 'nàlǐ', 'meaning': 'там, туда'},
    '那儿': {'pinyin': 'nàr', 'meaning': 'там; тогда'},
    '那些': {'pinyin': 'nàxiē', 'meaning': 'те'},
    '奶': {'pinyin': 'nǎi', 'meaning': 'молоко; грудь'},
    '奶奶': {'pinyin': 'nǎinai', 'meaning': 'бабушка (по папе)'},
    '男': {'pinyin': 'nán', 'meaning': 'мужской'},
    '男孩儿': {'pinyin': 'nánháir', 'meaning': 'мальчик'},
    '男朋友': {'pinyin': 'nánpéngyou', 'meaning': 'друг; бойфренд'},
    '男人': {'pinyin': 'nánrén', 'meaning': 'мужчина'},
    '男生': {'pinyin': 'nánshēng', 'meaning': 'ученик (мужского пола)'},
    '南': {'pinyin': 'nán', 'meaning': 'юг, южный'},
    '南边': {'pinyin': 'nánbian', 'meaning': 'южная сторона'},
    '难': {'pinyin': 'nán', 'meaning': 'трудный'},
    '呢': {'pinyin': 'ne', 'meaning': 'конечная модальная частица'},
    '能': {'pinyin': 'néng', 'meaning': 'мочь, быть в состоянии'},
    '你': {'pinyin': 'nǐ', 'meaning': 'ты'},
    '你们': {'pinyin': 'nǐmen', 'meaning': 'вы (множ. число)'},
    '年': {'pinyin': 'nián', 'meaning': 'год'},
    '您': {'pinyin': 'nín', 'meaning': 'Вы (уважительно)'},
    '牛奶': {'pinyin': 'niúnǎi', 'meaning': 'коровье молоко'},
    '女': {'pinyin': 'nǚ', 'meaning': 'женский, женщина'},
    '女儿': {'pinyin': 'nǚér', 'meaning': 'дочь'},
    '女孩儿': {'pinyin': 'nǚháir', 'meaning': 'девочка'},
    '女朋友': {'pinyin': 'nǚpéngyou', 'meaning': 'подруга; герлфренд'},
    '女人': {'pinyin': 'nǚrén', 'meaning': 'женщина'},
    '女生': {'pinyin': 'nǚshēng', 'meaning': 'ученица, студентка'},
    '旁边': {'pinyin': 'pángbiān', 'meaning': 'рядом, сбоку'},
    '跑': {'pinyin': 'pǎo', 'meaning': 'бегать'},
    '朋友': {'pinyin': 'péngyou', 'meaning': 'друг'},
    '票': {'pinyin': 'piào', 'meaning': 'билет'},
    '七': {'pinyin': 'qī', 'meaning': '7, семь'},
    '起': {'pinyin': 'qǐ', 'meaning': 'вставать'},
    '起床': {'pinyin': 'qǐchuáng', 'meaning': 'вставать с кровати'},
    '起来': {'pinyin': 'qǐlai', 'meaning': 'вставать, подниматься; начало действия'},
    '汽车': {'pinyin': 'qìchē', 'meaning': 'автомобиль'},
    '前': {'pinyin': 'qián', 'meaning': 'впереди, до'},
    '前边': {'pinyin': 'qiánbian', 'meaning': 'передняя часть, впереди'},
    '前天': {'pinyin': 'qiántiān', 'meaning': 'позавчера'},
    '钱': {'pinyin': 'qián', 'meaning': 'деньги'},
    '钱包': {'pinyin': 'qiánbāo', 'meaning': 'кошелек'},
    '请': {'pinyin': 'qǐng', 'meaning': 'приглашать; пожалуйста'},
    '请假': {'pinyin': 'qǐngjià', 'meaning': 'просить об отпуске'},
    '请进': {'pinyin': 'qǐng jìn', 'meaning': 'пожалуйста, войдите'},
    '请问': {'pinyin': 'qǐngwèn', 'meaning': 'извините; позвольте спросить'},
    '请坐': {'pinyin': 'qǐng zuò', 'meaning': 'пожалуйста, садитесь'},
    '球': {'pinyin': 'qiú', 'meaning': 'мяч, шар'},
    '去': {'pinyin': 'qù', 'meaning': 'идти, уходить'},
    '去年': {'pinyin': 'qùnián', 'meaning': 'прошлый год'},
    '热': {'pinyin': 'rè', 'meaning': 'горячий, разогревать'},
    '人': {'pinyin': 'rén', 'meaning': 'человек'},
    '认识': {'pinyin': 'rènshi', 'meaning': 'быть знакомым, знать'},
    '认真': {'pinyin': 'rènzhēn', 'meaning': 'серьёзный'},
    '日': {'pinyin': 'rì', 'meaning': 'день, дата'},
    '日期': {'pinyin': 'rìqī', 'meaning': 'срок; дата'},
    '肉': {'pinyin': 'ròu', 'meaning': 'мясо; мякоть (фрукта)'},
    '三': {'pinyin': 'sān', 'meaning': '3, три'},
    '山': {'pinyin': 'shān', 'meaning': 'гора, холм'},
    '商场': {'pinyin': 'shāngchǎng', 'meaning': 'торговый центр'},
    '商店': {'pinyin': 'shāngdiàn', 'meaning': 'магазин'},
    '上': {'pinyin': 'shàng', 'meaning': 'на, над'},
    '上班': {'pinyin': 'shàngbān', 'meaning': 'ходить на работу'},
    '上边': {'pinyin': 'shàngbian', 'meaning': 'выше, над'},
    '上车': {'pinyin': 'shàngchē', 'meaning': 'садиться в транспорт'},
    '上次': {'pinyin': 'shàngcì', 'meaning': 'прошлый раз'},
    '上课': {'pinyin': 'shàngkè', 'meaning': 'приходить на урок'},
    '上网': {'pinyin': 'shàngwǎng', 'meaning': 'заходить в интернет'},
    '上午': {'pinyin': 'shàngwǔ', 'meaning': 'утро, первая половина дня'},
    '上学': {'pinyin': 'shàngxué', 'meaning': 'ходить в школу'},
    '少': {'pinyin': 'shǎo', 'meaning': 'мало'},
    '谁': {'pinyin': 'shéi', 'meaning': 'кто?'},
    '身上': {'pinyin': 'shēnshang', 'meaning': 'на теле; при себе'},
    '身体': {'pinyin': 'shēntǐ', 'meaning': 'тело; здоровье'},
    '什么': {'pinyin': 'shénme', 'meaning': 'что? какой?'},
    '生病': {'pinyin': 'shēngbìng', 'meaning': 'заболеть'},
    '生气': {'pinyin': 'shēngqì', 'meaning': 'злиться, сердитый'},
    '生日': {'pinyin': 'shēngrì', 'meaning': 'день рождения'},
    '十': {'pinyin': 'shí', 'meaning': '10, десять'},
    '时候': {'pinyin': 'shíhou', 'meaning': 'время'},
    '时间': {'pinyin': 'shíjiān', 'meaning': 'время (как отрезок)'},
    '事': {'pinyin': 'shì', 'meaning': 'дело, событие; работа'},
    '试': {'pinyin': 'shì', 'meaning': 'пробовать, примерять'},
    '是': {'pinyin': 'shì', 'meaning': 'быть, являться'},
    '是不是': {'pinyin': 'shì bu shì', 'meaning': 'да или нет?'},
    '手': {'pinyin': 'shǒu', 'meaning': 'рука'},
    '手机': {'pinyin': 'shǒujī', 'meaning': 'мобильный телефон'},
    '书': {'pinyin': 'shū', 'meaning': 'книга'},
    '书包': {'pinyin': 'shūbāo', 'meaning': 'школьный портфель'},
    '书店': {'pinyin': 'shūdiàn', 'meaning': 'книжный магазин'},
    '树': {'pinyin': 'shù', 'meaning': 'дерево'},
    '水': {'pinyin': 'shuǐ', 'meaning': 'вода'},
    '水果': {'pinyin': 'shuǐguǒ', 'meaning': 'фрукт'},
    '睡': {'pinyin': 'shuì', 'meaning': 'спать'},
    '睡觉': {'pinyin': 'shuìjiào', 'meaning': 'спать, идти спать'},
    '说': {'pinyin': 'shuō', 'meaning': 'говорить, рассказывать'},
    '说话': {'pinyin': 'shuōhuà', 'meaning': 'говорить, разговаривать'},
    '四': {'pinyin': 'sì', 'meaning': '4, четыре'},
    '送': {'pinyin': 'sòng', 'meaning': 'доставлять; дарить; провожать'},
    '岁': {'pinyin': 'suì', 'meaning': 'год, лет'},
    '他': {'pinyin': 'tā', 'meaning': 'он'},
    '他们': {'pinyin': 'tāmen', 'meaning': 'они, им'},
    '她': {'pinyin': 'tā', 'meaning': 'она'},
    '她们': {'pinyin': 'tāmen', 'meaning': 'они (ж.р.)'},
    '太': {'pinyin': 'tài', 'meaning': 'слишком, чересчур'},
    '天': {'pinyin': 'tiān', 'meaning': 'день; небо'},
    '天气': {'pinyin': 'tiānqì', 'meaning': 'погода'},
    '听': {'pinyin': 'tīng', 'meaning': 'слушать, слышать'},
    '听到': {'pinyin': 'tīngdào', 'meaning': 'услышать'},
    '听见': {'pinyin': 'tīngjiàn', 'meaning': 'слышать, услышать'},
    '听写': {'pinyin': 'tīngxiě', 'meaning': 'диктовать; диктант'},
    '同学': {'pinyin': 'tóngxué', 'meaning': 'одноклассник'},
    '图书馆': {'pinyin': 'túshūguǎn', 'meaning': 'библиотека'},
    '外': {'pinyin': 'wài', 'meaning': 'снаружи, внешний'},
    '外边': {'pinyin': 'wàibian', 'meaning': 'внешняя часть, снаружи'},
    '外国': {'pinyin': 'wàiguó', 'meaning': 'иностранное государство'},
    '外语': {'pinyin': 'wàiyǔ', 'meaning': 'иностранный язык'},
    '玩儿': {'pinyin': 'wánr', 'meaning': 'играть, развлекаться'},
    '晚': {'pinyin': 'wǎn', 'meaning': 'поздний'},
    '晚饭': {'pinyin': 'wǎnfàn', 'meaning': 'ужин'},
    '晚上': {'pinyin': 'wǎnshang', 'meaning': 'вечер'},
    '网上': {'pinyin': 'wǎng shang', 'meaning': 'онлайн, в интернете'},
    '网友': {'pinyin': 'wǎngyǒu', 'meaning': 'друг в интернете'},
    '忘': {'pinyin': 'wàng', 'meaning': 'забывать'},
    '忘记': {'pinyin': 'wàngjì', 'meaning': 'забыть, запамятовать'},
    '问': {'pinyin': 'wèn', 'meaning': 'спрашивать'},
    '我': {'pinyin': 'wǒ', 'meaning': 'я'},
    '我们': {'pinyin': 'wǒmen', 'meaning': 'мы'},
    '五': {'pinyin': 'wǔ', 'meaning': '5, пять'},
    '午饭': {'pinyin': 'wǔfàn', 'meaning': 'обед'},
    '西': {'pinyin': 'xī', 'meaning': 'запад, западный'},
    '西边': {'pinyin': 'xībian', 'meaning': 'западная сторона'},
    '洗': {'pinyin': 'xǐ', 'meaning': 'мыть; стирать'},
    '洗手间': {'pinyin': 'xǐshǒujiān', 'meaning': 'туалет, уборная'},
    '喜欢': {'pinyin': 'xǐhuan', 'meaning': 'нравится'},
    '下': {'pinyin': 'xià', 'meaning': 'вниз, под; спускаться; заканчивать'},
    '下班': {'pinyin': 'xiàbān', 'meaning': 'уходить с работы'},
    '下边': {'pinyin': 'xiàbian', 'meaning': 'под, внизу'},
    '下车': {'pinyin': 'xiàchē', 'meaning': 'выйти из транспорта'},
    '下次': {'pinyin': 'xiàcì', 'meaning': 'следующий раз'},
    '下课': {'pinyin': 'xiàkè', 'meaning': 'заканчивать урок'},
    '下午': {'pinyin': 'xiàwǔ', 'meaning': 'после обеда, днем'},
    '下雨': {'pinyin': 'xiàyǔ', 'meaning': 'идет дождь'},
    '先': {'pinyin': 'xiān', 'meaning': 'сначала; раньше'},
    '先生': {'pinyin': 'xiānsheng', 'meaning': 'господин'},
    '现在': {'pinyin': 'xiànzài', 'meaning': 'сейчас'},
    '想': {'pinyin': 'xiǎng', 'meaning': 'хотеть; думать'},
    '小': {'pinyin': 'xiǎo', 'meaning': 'маленький'},
    '小孩儿': {'pinyin': 'xiǎoháir', 'meaning': 'ребенок'},
    '小姐': {'pinyin': 'xiǎojiě', 'meaning': 'мисс, девушка'},
    '小朋友': {'pinyin': 'xiǎopéngyǒu', 'meaning': 'ребенок, дети'},
    '小时': {'pinyin': 'xiǎoshí', 'meaning': 'час'},
    '小学': {'pinyin': 'xiǎoxué', 'meaning': 'начальная школа'},
    '小学生': {'pinyin': 'xiǎoxuéshēng', 'meaning': 'ученик начальной школы'},
    '笑': {'pinyin': 'xiào', 'meaning': 'смеяться; улыбаться'},
    '写': {'pinyin': 'xiě', 'meaning': 'писать'},
    '谢谢': {'pinyin': 'xièxie', 'meaning': 'спасибо'},
    '新': {'pinyin': 'xīn', 'meaning': 'новый'},
    '新年': {'pinyin': 'xīnnián', 'meaning': 'Новый год'},
    '星期': {'pinyin': 'xīngqī', 'meaning': 'неделя'},
    '星期日': {'pinyin': 'xīngqīrì', 'meaning': 'воскресенье'},
    '星期天': {'pinyin': 'xīngqītiān', 'meaning': 'воскресенье'},
    '行': {'pinyin': 'xíng', 'meaning': 'ходить; ОК'},
    '休息': {'pinyin': 'xiūxi', 'meaning': 'отдыхать, отдых'},
    '学': {'pinyin': 'xué', 'meaning': 'учить, изучать'},
    '学生': {'pinyin': 'xuésheng', 'meaning': 'ученик, студент'},
    '学习': {'pinyin': 'xuéxí', 'meaning': 'учиться, учеба'},
    '学校': {'pinyin': 'xuéxiào', 'meaning': 'школа'},
    '学院': {'pinyin': 'xuéyuàn', 'meaning': 'институт, академия'},
    '要': {'pinyin': 'yào', 'meaning': 'хотеть; должен'},
    '爷爷': {'pinyin': 'yéye', 'meaning': 'дедушка (по папе)'},
    '也': {'pinyin': 'yě', 'meaning': 'тоже'},
    '页': {'pinyin': 'yè', 'meaning': 'страница, листок'},
    '一': {'pinyin': 'yī', 'meaning': '1, один'},
    '衣服': {'pinyin': 'yīfu', 'meaning': 'одежда'},
    '医生': {'pinyin': 'yīshēng', 'meaning': 'врач'},
    '医院': {'pinyin': 'yīyuàn', 'meaning': 'больница'},
    '一半': {'pinyin': 'yíbàn', 'meaning': 'половина'},
    '一会儿': {'pinyin': 'yíhuìr', 'meaning': 'чуть-чуть, немного'},
    '一块儿': {'pinyin': 'yíkuàir', 'meaning': 'вместе'},
    '一下儿': {'pinyin': 'yíxiàr', 'meaning': 'немного; один раз'},
    '一样': {'pinyin': 'yíyàng', 'meaning': 'одинаковый'},
    '一边': {'pinyin': 'yìbiān', 'meaning': 'с одной стороны'},
    '一点儿': {'pinyin': 'yìdiǎnr', 'meaning': 'немного'},
    '一起': {'pinyin': 'yìqǐ', 'meaning': 'вместе'},
    '一些': {'pinyin': 'yìxiē', 'meaning': 'некоторые, несколько'},
    '用': {'pinyin': 'yòng', 'meaning': 'использовать; с помощью'},
    '有': {'pinyin': 'yǒuxiē', 'meaning': 'иметь немного'},
    '有的': {'pinyin': 'yǒude', 'meaning': 'некоторый'},
    '有名': {'pinyin': 'yǒumíng', 'meaning': 'известный'},
    '有时候': {'pinyin': 'yǒushíhou', 'meaning': 'иногда, временами'},
    '有用': {'pinyin': 'yǒuyòng', 'meaning': 'полезный'},
    '右': {'pinyin': 'yòu', 'meaning': 'правый'},
    '右边': {'pinyin': 'yòubian', 'meaning': 'справа'},
    '雨': {'pinyin': 'yǔ', 'meaning': 'дождь'},
    '元': {'pinyin': 'yuán', 'meaning': 'юань'},
    '远': {'pinyin': 'yuǎn', 'meaning': 'далекий'},
    '月': {'pinyin': 'yuè', 'meaning': 'месяц'},
    '再': {'pinyin': 'zài', 'meaning': 'снова, затем'},
    '再见': {'pinyin': 'zàijiàn', 'meaning': 'до свидания'},
    '在': {'pinyin': 'zài', 'meaning': 'в; находиться'},
    '在家': {'pinyin': 'zàijiā', 'meaning': 'дома'},
    '早': {'pinyin': 'zǎo', 'meaning': 'ранний, рано'},
    '早饭': {'pinyin': 'zǎofàn', 'meaning': 'завтрак'},
    '早上': {'pinyin': 'zǎoshang', 'meaning': 'утром'},
    '怎么': {'pinyin': 'zěnme', 'meaning': 'как? почему?'},
    '站': {'pinyin': 'zhàn', 'meaning': 'остановка, станция'},
    '找': {'pinyin': 'zhǎo', 'meaning': 'искать; давать сдачу'},
    '找到': {'pinyin': 'zhǎodào', 'meaning': 'находить'},
    '这': {'pinyin': 'zhè', 'meaning': 'это, этот'},
    '这边': {'pinyin': 'zhèbiān', 'meaning': 'здесь; на этой стороне'},
    '这里': {'pinyin': 'zhèlǐ', 'meaning': 'здесь; сюда'},
    '这儿': {'pinyin': 'zhèr', 'meaning': 'здесь'},
    '这些': {'pinyin': 'zhèxiē', 'meaning': 'эти'},
    '着': {'pinyin': 'zhe', 'meaning': 'глагольный суффикс продолженного действия'},
    '真': {'pinyin': 'zhēn', 'meaning': 'правда; настоящий'},
    '真的': {'pinyin': 'zhēnde', 'meaning': 'настоящий; действительно'},
    '正': {'pinyin': 'zhèng', 'meaning': 'именно; как раз'},
    '正在': {'pinyin': 'zhèngzài', 'meaning': 'сейчас (в процессе)'},
    '知道': {'pinyin': 'zhīdào', 'meaning': 'знать'},
    '知识': {'pinyin': 'zhīshi', 'meaning': 'знание; интеллект'},
    '中': {'pinyin': 'zhōng', 'meaning': 'середина; в процессе'},
    '中国': {'pinyin': 'Zhōngguó', 'meaning': 'Китай'},
    '中间': {'pinyin': 'zhōngjiān', 'meaning': 'среди, посередине'},
    '中文': {'pinyin': 'Zhōngwén', 'meaning': 'китайский язык; китайская письменность'},
    '中午': {'pinyin': 'zhōngwǔ', 'meaning': 'полдень'},
    '中学': {'pinyin': 'zhōngxué', 'meaning': 'средняя школа'},
    '中学生': {'pinyin': 'zhōngxuéshēng', 'meaning': 'учащийся средней школы'},
    '重': {'pinyin': 'zhòng', 'meaning': 'тяжёлый; важный'},
    '重要': {'pinyin': 'zhòngyào', 'meaning': 'важный'},
    '住': {'pinyin': 'zhù', 'meaning': 'жить, проживать'},
    '准备': {'pinyin': 'zhǔnbèi', 'meaning': 'готовиться; подготовка'},
    '桌子': {'pinyin': 'zhuōzi', 'meaning': 'стол'},
    '字': {'pinyin': 'zì', 'meaning': 'иероглиф, слово'},
    '子': {'pinyin': 'zi', 'meaning': 'суффикс существительных'},
    '走': {'pinyin': 'zǒu', 'meaning': 'ходить (пешком)'},
    '走路': {'pinyin': 'zǒulù', 'meaning': 'идти по дороге'},
    '最': {'pinyin': 'zuì', 'meaning': 'самый'},
    '最好': {'pinyin': 'zuìhǎo', 'meaning': 'лучше всего'},
    '最后': {'pinyin': 'zuìhòu', 'meaning': 'последний; в конце концов'},
    '昨天': {'pinyin': 'zuótiān', 'meaning': 'вчера'},
    '左': {'pinyin': 'zuǒ', 'meaning': 'левый'},
    '左边': {'pinyin': 'zuǒbian', 'meaning': 'слева'},
    '坐': {'pinyin': 'zuò', 'meaning': 'сидеть; ехать на транспорте'},
    '坐下': {'pinyin': 'zuòxia', 'meaning': 'садиться'},
    '做': {'pinyin': 'zuò', 'meaning': 'делать, готовить'},
}
