# Generated by Django 3.1.12 on 2025-07-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='examples',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
