# Generated by Django 3.1.12 on 2025-07-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
