# Generated by Django 3.1.12 on 2025-07-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20250710_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='cards',
        ),
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.JSONField(default=list),
        ),
    ]
