# Generated by Django 3.1.12 on 2025-08-04 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0005_auto_20250710_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='examples',
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(default='HSK1', max_length=50),
        ),
        migrations.AlterField(
            model_name='collection',
            name='cards',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='HSK1', max_length=50)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_answers', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('remaining_cards', djongo.models.fields.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
