# Generated by Django 3.1.12 on 2025-08-10 20:07

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_auto_20250805_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='answer_history',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
