# Generated by Django 3.1.12 on 2025-08-13 19:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_gamesession_answer_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
