# Generated by Django 3.1.12 on 2025-08-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_gamesession_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='session_id',
        ),
    ]
